### ISSUE TITLE
BUG:点击虚拟列表中某一项时，打印的数据不是渲染的结果项

### ISSUE THREAD

**Issue by chenming142** [tangbc/vue-virtual-scroll-list#104]
vue-virtual-scroll-list 设置size=50 remain=10,虚拟列表渲染结果是10条记录，滚动滚动条前面20条点击的结果都是正确的，但是超过20条后再次点击，选中的结果却是前面20条内的记录项；如果再次滚动到前面点击某一项，则会报错Maximum call stack size exceeded

**Comment by tangbc** [comment]
我看看，如果可以最好能给个复现的代码片段或链接。

**Comment by chenming142** [comment]
已经解决了，是因为slot使用v-for没有指定:key
