### ISSUE TITLE
pass event on item-mode

### ISSUE THREAD

**Issue by rezatati** [tangbc/vue-virtual-scroll-list#105]
Hi 
How can I pass an event handler in  item-mode to the Items 

here is my item in usual way 

```
<Item
   @statusUpdated="updateApprovalStatus"
          v-for="item in ListData"
          v-bind:key="item.Type+item.id"
          :currentitem="item"
        ></Item>
```
but How can pass statusUpdated to the items in item-mode ?

**Comment by tangbc** [comment]
You can try this way:

```js
getItemProps (itemIndex) {
    return {
        props: {
            statusUpdated: statusUpdated
        }
    }
}
```

Reference: https://github.com/tangbc/vue-virtual-scroll-list/blob/master/demos/item-mode/App.vue#L58

https://vuejs.org/v2/guide/render-function.html#createElement-Arguments

**Comment by siba2893** [comment]
Could you please revive this example. The github link is broken.

**Comment by tangbc** [comment]
@siba2893 This is old version 1.x, big change now, see readme for guide.
