### ISSUE TITLE
Problem with ie11 not transpiled (src instead of dist on npmjs release)

### ISSUE THREAD

**Issue by lorenzofaresin** [tangbc/vue-virtual-scroll-list#108]
Hi,
using this package from npm I found an issue with IE 11 (syntax error).

I think this is caused by the arrow function not transpiled with babel.

I try to override the fine from node_modules src/index.js with the dist/index.js and it work fine.

Maybe you have to publish dist instead of src on npmjs registry.

My pull request will arrive soon.

Thank you
Lorenzo

**Comment by tangbc** [comment]
I've published 1.3.9 fixed this.
