### ISSUE TITLE
If i don't know each item height, why i still need to assign a value to it ? 

### ISSUE THREAD

**Issue by hereiscasio** [tangbc/vue-virtual-scroll-list#110]
if i don't know each item height ( e.g. Chat App, i can't know each message height before i render it to DOM )

then i think i need to use **_item-mode_**, but seems like i still need set the static value of ` size ` which just like i make a assumption that each message will have same height

so it's still confuse to me, or i miss something ?

**Comment by tangbc** [comment]
Sorry for so long to reply. 

Previously planned to support an `estimateSize`prop, but case many problems, it's under developing.

**Comment by Dagdelo** [comment]
@tangbc I had the same scenario (chat-app), using v-for mode, how to implement it? I mean, how to find the variable size?

**Comment by tangbc** [comment]
@Dagdelo Now not support yet, but planing in new version 2.0

**Comment by Dagdelo** [comment]
Just for asking, item mode nor variable height can handle that right? The best result I can reach it's guessing the size, but it's obviously impractical...

**Comment by tangbc** [comment]
In any case, virtual-list need to know the item height. The difference is whether virtual-list can get the item height by itself. If not, you need to tell virtual-list.

**Comment by Dagdelo** [comment]
@tangbc Just for pure curiosity, what are your thoughts on how to calculate the height of the items? I'm thinking about it for a few days... and find one or two approaches that are not performative (canvas, hide-dom-element).

**Comment by tangbc** [comment]
If item under your control, just use dom api `offsetHeight` in `mounted` hook, but virtual-list unable to do this.

**Comment by tangbc** [comment]
v2.0 almost finished, comming soon...

**Comment by Dagdelo** [comment]
Very glad to read that, I've come to some nasty workarounds with off-document rendering to predict the height of the items.

**Comment by tangbc** [comment]
In new version we don't need care about size.

**Comment by tangbc** [comment]
Already publish first version v2.0.0, welcome to try and report problems.
