### ISSUE TITLE
Possible to have certain items be sticky?

### ISSUE THREAD

**Issue by wpatter6** [tangbc/vue-virtual-scroll-list#111]
Hi, I'm using your awesome tool to scroll through lists of items with headers.  I'd like to have the headers be sticky but it seems that they only stick until they're removed from the DOM, which is not ideal.

See the "Virtual Scrolling" example here: https://codesandbox.io/s/v-super-select-demo-8542r

The headers stick around until the virtual scroller removes them.  Basically, is there a way to force certain items to persist after they've been loaded so they can be sticky?

Thanks!

**Comment by tangbc** [comment]
This component support big data by reuse and cover current items, so everyone will be remove and update to another during scrolling. It is unlikely to be implemented within this components to stick someone.
