### ISSUE TITLE
Possible to replace the <div> by an <ul>?

### ISSUE THREAD

**Issue by vincent-fi** [tangbc/vue-virtual-scroll-list#113]
Since this amazing library renders a list, it would be better (more semantic) to encapsulate list items between `<ul>` tags rather than a `<div>` (rendered by components `<virtual-list>` for example).

**Comment by tangbc** [comment]
You can try use prop `rtag` and `wtag`.

**Comment by vincent-fi** [comment]
Stupid question, thanks! 🙂
