### ISSUE TITLE
v-on problem

### ISSUE THREAD

**Issue by ntoner77** [tangbc/vue-virtual-scroll-list#117]
when the virtual list is used, it is became the parent component and $emit is pointing at the list. How to make virtual list to $emit these events to its parent, whick previous(before using virtual list) was the parent of my component

**Comment by tangbc** [comment]
What about using `event-bus` to notify?

**Comment by ntoner77** [comment]
I ll try it thanks

Αποκτήστε το Outlook για Android<https://aka.ms/ghei36>

________________________________
