### ISSUE TITLE
Cannot read property 'key' of undefined during scrolling

### ISSUE THREAD

**Issue by vladyc9** [tangbc/vue-virtual-scroll-list#118]
![Снимок экрана 2019-08-02 в 15 30 06](https://user-images.githubusercontent.com/5639365/62370780-b2dc7100-b53b-11e9-9506-fabd1544d1e6.png)

I use element-ui <el-collapse> component to expand/collapse lists. It works fine but randomly I get this error during scrolling or leaving page for a while, the lists constantly push/pop users online/offline (about 1000 connections).

After error appeared I cannot open/close collapse component and blocks all interactions with the page need to refresh it.
(BTW: it happens only in production mode, dev works fine, cannot find the workaround of this issue...)

**Comment by tangbc** [comment]
There are no any `key` in this component source code, can you debuger with source-map.

**Comment by vladyc9** [comment]
Sorry, it seems the bug caused by internal logic. I will close the issue.
