### ISSUE TITLE
Infinite loop help

### ISSUE THREAD

**Issue by dudedigital** [tangbc/vue-virtual-scroll-list#120]
I am using item mode. I have a prop within the Item.vue that I need to change to indicate whether it's been checked or not. But the code seems to cause an infinite render loop. Seems no matter how I structure it, if a prop changes the endless loop is triggered. Been experimenting for awhile and any help would be greatly appreciated.

```
props: {
    list: OptionList,
    value: Array,
},
getObjectData(index) {
    console.log('loop');
    let option = this.list.get(index);
    return {
        key: index,
        props: {
            checked: this.value.indexOf(option.value) > -1,
            height: this.itemHeight,
            index: index,
            object: option,
        }
    }
}
```

**Comment by tangbc** [comment]
Can you give a sime reproduce demo in https://codepen.io ?
