### ISSUE TITLE
Is anyone else getting console warning: "[Vue warn]: $attrs is readonly" & "[Vue warn]: $listeners is readonly"?

### ISSUE THREAD

**Issue by lmichetti3** [tangbc/vue-virtual-scroll-list#121]
When I modify array data that vue-virtual-scroll-list renders, I get the following console warning:

**[Vue warn]: $attrs is readonly**
**[Vue warn]: $listeners is readonly**

Maybe unrelated, but from what I've read, this warning is often caused by a package (vue-virtual-scroll-list) calling a second instance of Vue. This warning only occurs if I use vue-virtual-scroll-list. I'm already calling vue in my main.js file like this:

**import Vue from 'vue'**

I'm just wondering if there's anyone that has encountered this warning and how to remove it. There aren't any noticeable issues, but the warning is annoying to see in my console.

**Comment by tangbc** [comment]
What's the detail of `caused by a calling a second instance of Vue`?

Can you tell me more detail or example your repo I can see it?

**Comment by ROTGP** [comment]
@lmichetti3 are you using this in an Electron project? If so, you must add `'vue-virtual-scroll-list'` to the `whiteListedModules` array inside `webpack.renderer.config.js`

**Comment by Blightysoft** [comment]
> 
> 
> @lmichetti3 are you using this in an Electron project? If so, you must add `'vue-virtual-scroll-list'` to the `whiteListedModules` array inside `webpack.renderer.config.js`

Spot on. This solved my problems. Thanks a lot ROTGP!

**Comment by Y80** [comment]
My solution: change the import statement.

import VirtualList from 'vue-virtual-scroll-list'
->
import VirtualList from 'vue-virtual-scroll-list/src'
