### ISSUE TITLE
horizontal example?

### ISSUE THREAD

**Issue by wizardnet972** [tangbc/vue-virtual-scroll-list#122]
Did you have a horizontal example like https://akryum.github.io/vue-virtual-scroller/#/horizontal?

**Comment by tangbc** [comment]
At present not support yet. Some people mentioned it before, but the demand is not large, so there is no continuation. I put it in the next plan.

**Comment by tangbc** [comment]
See https://tangbc.github.io/vue-virtual-scroll-list/#/horizontal
