### ISSUE TITLE
scroll buggy

### ISSUE THREAD

**Issue by dews** [tangbc/vue-virtual-scroll-list#123]
When using vuetify  Vmenu in the vue-virtual-scroll-list and scrolling to top slowly, the content will shake.
Demo https://stackblitz.com/edit/svelte-tjb7cb

**Comment by tangbc** [comment]
I don't know what's the purpose using `window.pageXOffset` in VMenu render function, it's ok when remove it:
```javascript
// window.pageXOffset
```

**Comment by dews** [comment]
Thanks for the reply. The `window.pageXOffset` in VMenu is for detect popup menu position.
It's at VMenu.js -> calculatedLeft -> calcLeft -> calcXOverflow -> getOffsetLeft -> window.pageXOffset
It's embedded in Vuetify so can't remove it. I workaround like this,
```
import Vue from 'vue'
import { VMenu } from 'vuetify/es5/components/VMenu'

export default Vue.extend({
  name: 'CusMenu',
  mixins: [
    VMenu
  ],
  data () {
    return {
      isInited: false
    }
  },
  methods: {
    // Overwrite the getOffsetLeft function in the menuable.js
    // Only do it when init
    getOffsetLeft () {
      if (!this.isInited) {
        this.isInited = true
        return 0
      }

      if (!this.hasWindow) return 0
      return window.pageXOffset || document.documentElement.scrollLeft
    }
  }
})
```

But I wonder why ` window.pageXOffset` cause this issue?

**Comment by tangbc** [comment]
I don't know either...
