### ISSUE TITLE
Scroll bar disappears after upgrading from Chrome 74 to 76

### ISSUE THREAD

**Issue by weebs** [tangbc/vue-virtual-scroll-list#124]
I'm not sure if this issue has occurred to anyone else, because the examples page is still working in my Chrome v76 browser. However in one of our projects the scroll bar for the virtual list has disappeared and users can no longer scroll. I was able to fix this by patching the render function in index.js to use `max-height` instead of `height`.

```javascript
return h(this.rtag, {
    'ref': 'vsl',
    'style': {
        'display': 'block',
        'overflow-y': 'auto',
        'max-height': this.size * this.remain + 'px'
    },
    'on': {
        '&scroll': dbc ? _debounce(this.onScroll.bind(this), dbc) : this.onScroll
    }
}, [
    renderList
])
```

**Comment by tangbc** [comment]
Can no longer scroll? 
It looks like a serious problem, does official demos have the same problem or how can I see the behavior?

**Comment by cainrus** [comment]
> Chrome version 76.0.3809.132 (Official Build) (64-bit)
All demos are ok.
