### ISSUE TITLE
Old list items is not getting removed from DOM

### ISSUE THREAD

**Issue by ItsMos** [tangbc/vue-virtual-scroll-list#126]
Seems like updating the `list` array doesnt remove the previous array from DOM.

i have this search bar, first i search for `crane` then searched for `chair` and as you can see it mixed some of the old search `crane` to the new search
[Screenshot](https://b.imge.to/2019/08/28/vvd0TG.jpg)
and my list array is correct only containing `chair` result, this is just an example.
maybe im using it wrong
```html
<virtual-list class='list' :size='30' :remain='20' :bench='0' wtag='ul'>
  <li v-for='(obj, index) in result'
    :class='{active: selectedObj == index}'
    @click='objectClick(index, obj.obj)'>
    {{obj.obj}}
  </li>
</virtual-list>
```
my list:
```js
list = [
  {obj: 'obj_name'}
]
```

**Comment by xibeizer** [comment]
me too

**Comment by tangbc** [comment]
Can you reproduce in this demos: https://codepen.io/tangbc/pen/NWKgjVo
