### ISSUE TITLE
add a flag to updateVariable to keep scroll position

### ISSUE THREAD

**Issue by nahuel** [tangbc/vue-virtual-scroll-list#128]
Suppose you have a virtual list  with the following items:

A  (not visible)
B  (visible, on viewport)
C (not visible)

If you grow the size of A, then B will be displaced to bottom. It will be nice to call updateVariable(0, keepScrollPosition = true) to ensure B and the other items visible screen position doesn't change after A resizes.

**Comment by tangbc** [comment]
A way is using `start` to keep in viewport after `updateVariable` so far, but it will always place at top of viewport.

To keep the real scroll postion. I'll consider how to deal with it.

**Comment by nahuel** [comment]
Maybe adding an "anchorIdx" property to mark a visible item as an anchor. So if the previous items grows or new items are inserted previous to the anchor item, virtual-list will maintain the anchor item exactly in the previous visible scroll position. 

The general problem is what to do with the scroll position when items change size, are added or removed, to avoid unexpected and unwanted jumps in the visible scroll position.

Another nice behavior to have, for example, is to configure virtual-scroll-list to always auto-scroll to the bottom of the list when items are added at the end of the item list, but only if the user is already viewing the bottom (like console terminals). Or the same inverted, autoscrolling to the recently added first item at the top only if the user is already on top, but if the user scroll position is viewing the middle of the list then not changing the scroll position when the item is unshifted.

**Comment by tangbc** [comment]
This sounds like chat-app. I'll try to add a demo.

**Comment by nahuel** [comment]
@tangbc  note, a chat app only adds items at the bottom (or top) of the list, It will be nice to support add / grow / shrink items at any position without making the scroll jump
