### ISSUE TITLE
wish: emit initial onscroll event on first render

### ISSUE THREAD

**Issue by nahuel** [tangbc/vue-virtual-scroll-list#130]
I'm using the `onscroll` event to background load some content included in the items when they became visible. This works ok but only after the user begins to scroll. So it will be nice to make this component emit a single initial `onscroll` event when is mounted, before the user really starts to scroll, so the listener can begin to work with the initial visible items.

**Comment by tangbc** [comment]
Sorry I don't quite understand your purpose, I think it's not a good program practices to emit a user event even user doesn't really triggles. 

What about handling on `mounted` hooks in parent component ?

**Comment by nahuel** [comment]
I thought about using a mounted hook in the parent component but it seems I can access the vue-virtual-scroll-list element from the parent using a vue $ref but the component doesn't seems to expose a method to synchronously query the current start/end/offset. I'm wrong?

Note maybe at the mount time the item list (with variable heights) is not yet loaded, or it can change after mounting. For example, I presume there is another problem, if an item size changes after mounting, then start/end can change but without emitting an onscroll event (because the user isn't initiating the scroll). I didn't tested that yet, is this the current behavior?

**Comment by tangbc** [comment]
You can get `start / end / offset` via `$ref.vsl.delta` or just console and it.
