### ISSUE TITLE
When ( remain + bench < list.length ), "Animation Frame Fired" keep going.

### ISSUE THREAD

**Issue by junjii0106** [tangbc/vue-virtual-scroll-list#134]
I use item mode with filtering function.

By filtering list, when ( remain + bench < list.length ) "Animation Frame Fired" keep going and 
performance worsens.

**Comment by tangbc** [comment]
More steps or infomation to reproduce? How can I make this problem?

**Comment by junjii0106** [comment]
I show sample code below.

### Parent Component ###
<template>
  <div id="Parent">
    <input type="number" v-model.number="showNum"/>
    <div>
      <virtual-list
        :size="50"
        :remain="10"
        :bench="100"
        :start="0"
        :item="item"
        :itemcount="showData.length"
      />
    </div>
  </div>
</template>
<script lang="ts">
import { Component, Vue, Watch} from 'vue-property-decorator';
import Child from '@/child.vue';
import virtualList from 'vue-virtual-scroll-list';
Vue.component('virtual-list', virtualList);
@Component({
  components: {
    Child,
  },
})
export default class NeedsWantsGroup extends Vue {
  public item = Child;
  private showNum: number = 1000;
  private showData: number[] = [...Array(1000).keys()];
  @Watch('showNum')
  private setShowData() {
    this.showData = [...Array(this.showNum).keys()];
    this.$forceUpdate();
  }
}
</script>

### Child Component ###
<template>
  <div class="child">
    this is Child
  </div>
</template>
<script lang="ts">
import {Prop, Vue} from 'vue-property-decorator';
export default class Child extends Vue {}
</script>

###

When itemcount is lower than 110 (bench + remain), "Animation Frame Fired" keep going.

**Comment by tangbc** [comment]
@junjii0106 Can you offer a live demo link? Such as https://codepen.io/tangbc/pen/XWrveRQ

**Comment by freeall** [comment]
I see the same pattern. My page is very slow when `list.length > remain + bench`
