### ISSUE TITLE
Function to get the index range loaded?

### ISSUE THREAD

**Issue by DanielRivers** [tangbc/vue-virtual-scroll-list#136]
Is there a way to find out what range is currently loaded?

**Comment by DanielRivers** [comment]
I have updated my local version adding the following line to the end of the filter function.

`this.$emit('Update', { start: delta.start, end: Math.ceil(delta.end) })`

Would be a great addition ;)

**Comment by tangbc** [comment]
You can get range in two ways:

1. Get from `onscroll` [prop](https://github.com/tangbc/vue-virtual-scroll-list/releases/tag/v1.1.7) event params;
2. Get start / end / offset via `$ref.vsl.delta` or just console `$ref.vsl` and find it.

**Comment by DanielRivers** [comment]
This is perfect, I have been able to achieve what I was wanting to achieve using both of these.
