### ISSUE TITLE
What is the maximum itemcount?

### ISSUE THREAD

**Issue by StefanoCocomazzi** [tangbc/vue-virtual-scroll-list#141]
I tried loading 4194304 elements but the list stops halfway.
I'm using the item mode.

**Comment by tangbc** [comment]
It seems to depends on browser and complexity of item. 

I test for a very simple list in Chrome maximum is 700,000+, and 800,000+ in Safari, [live-demos](https://github.com/tangbc/vue-virtual-scroll-list#live-demos) just 419,430 in Chrome and same to Safari, only 300,00+ in Edge & IE #82.

So, I think it's an uncertain factor, but I don't know yet :(
