### ISSUE TITLE
Infinite forceRender

### ISSUE THREAD

**Issue by Katochimoto** [tangbc/vue-virtual-scroll-list#144]
1. `getZone()` => 
```
end: start + delta.keeps - 1
```
2. `filter()` => 
```
if (delta.keeps > delta.total) {
   delta.end = delta.total - 1
}
```
3. The condition is satisfied endlessly
`beforeUpdate()` =>
```
delta.end !== zone.end
```

As a result, a memory leak and 100% CPU.

**Comment by tangbc** [comment]
Thank you I will check it.

**Comment by lroal** [comment]
Any news on this one ?

**Comment by tangbc** [comment]
> Any news on this one ?

Busy these days, I plan to check at weekends.

**Comment by tangbc** [comment]
@Katochimoto Has any way to case these endlessly calc? If `delta.end` doesn't match calc `zone.end` then will force match before forceRender:
```
// we'd better make sure forceRender calls as less as possible.
if (
  shouldRenderNextZone ||
  zone.start !== delta.start ||
  zone.end !== delta.end
) {
  delta.end = zone.end // force to equal value here
  delta.start = zone.start
  this.forceRender()
}
```

Function inside `getZone` not change delta.end.

**Comment by Katochimoto** [comment]
> Function inside getZone not change delta.end.

yes, and this is not the reason
you compare `delta.end` and `zone.end`, but `delta` has this condition
```
if (delta.keeps > delta.total) {
   delta.end = delta.total - 1
} 
```
this is a constant condition 
and is not a general condition for both

this is my fix
https://github.com/Katochimoto/vue-virtual-scroll-list/commit/54db5771c9f8c96d3cb5242cdb5d56923feddd43#diff-090b05cdc4c33b5b4d778c13de44d8eaR338

**Comment by scarry1992** [comment]
I have got same situation. Please, fix it.

**Comment by tangbc** [comment]
@scarry1992 new npm version 1.4.5 has published.
