### ISSUE TITLE
Request: Only render lists that are within the viewport

### ISSUE THREAD

**Issue by nchutchind** [tangbc/vue-virtual-scroll-list#145]
I'm currently trying to show multiple lists on one page (a larger list that is grouped by a code). Each sublist is being rendered on its own, but each list is loading all of the remain + bench items even if they're way below the bottom of the screen.

It would be nice if the list took the viewport into account when determining when to initialize the items in the list and only do it if the offset is within a threshold.

**Comment by tangbc** [comment]
What about set `bench=1`?

**Comment by nchutchind** [comment]
That would certainly reduce the number of components created, but the problem is I have a page with components like this:

```
<div v-for="group in groupedItems" :key="group.code">
    <virtual-list :size="100" :remain="10" :bench="5" :item="itemComponent" itemCount="groupedItems[ group.code ].length" :itemProps="getItemPropsForGroup( group.code ) />
</div>
```

`getItemPropsForGroup( group.code )` returns a function that returns the props for an item at an index within the group.

That said, the page can have any number of virtual-lists on it. What I'm saying in this issue is that it would be nice if any virtual-lists or items that aren't within the viewport aren't rendered. If I just change bench to a lower number, the remain prop will still render the initial set of components for each list, even if they're thousands of pixels outside the viewport.

**Comment by nchutchind** [comment]
I had thought to maybe just have one list with sorting and group headers, but I don't really want to override the "item" component. I suppose another option would be changing the virtual-list to account for grouping.

**Comment by tangbc** [comment]
Do you mean nest `virtual-list`? (use another `virtual-list` inside root `virtual-list`)

**Comment by nchutchind** [comment]
No. I think I'm wishing the Intersection Observer worked with this library, so that only an onscreen `virtual-list` is rendered. I currently have 10 `virtual-list` components in my page, each with a `remain` of 10 and a `bench` of 5, so it's rendering 150 components, even though only 10 are on screen at any time.

**Comment by tangbc** [comment]
```bash
        ......
virtual-list-1   outside
virtual-list-2   outside
----------------------------
virtual-list-3      |
virtual-list-4      |
virtual-list-5   viewport
virtual-list-6      |
virtual-list-7      |
----------------------------
virtual-list-8   outside
virtual-list-9   outside
        ......
```

Is this case ?

**Comment by nchutchind** [comment]
Yes, exactly.

**Comment by nchutchind** [comment]
If remain is set to 10 and bench to 5, then each one of those lists, whether they are offscreen or not, will render 15 components. I tried using the Intersection Observer polyfill to change the remain and bench when a list is offscreen, but those properties don't seem to update anything if changed.

**Comment by tangbc** [comment]
> Yes, exactly.

Well, I think you can control and detect which `virtual-list` is being scroll into view and use `v-if` to render them? just handle outside this component?
