### ISSUE TITLE
Itemprops called thousands of times for every new item

### ISSUE THREAD

**Issue by freeall** [tangbc/vue-virtual-scroll-list#146]
I've been debugging a list of items I have, which seems to be quite slow.

For my test I add an item to the the list every 10ms (with a setInterval). Every second I output how many new items have been added, and how many times `:itemprops` have been called.

I've noticed two things.

1. Until the number of items exceeds `remain+bench` it seems to be extremely slow.
2. `:itemprops` is called thousands of times for every insert. From the documentation I can't seem to get this to make sense.

Here is my output that's logged every second.
```
{"newItems":16,"itemPropsCalls":4470}
{"newItems":10,"itemPropsCalls":12797}
{"newItems":7,"itemPropsCalls":16642}
{"newItems":5,"itemPropsCalls":20388}
{"newItems":5,"itemPropsCalls":17035}
{"newItems":3,"itemPropsCalls":15627}
{"newItems":3,"itemPropsCalls":22052}
{"newItems":11,"itemPropsCalls":11352}
{"newItems":35,"itemPropsCalls":5150}
{"newItems":37,"itemPropsCalls":5650}
{"newItems":32,"itemPropsCalls":4700}
... it seems to be steady after this
```

My `:itemprops` is as follows:
``` js
getItemProps (index) {
  return {
    key: index,
    props: {
      key: index,
      i: index,
      selectedItem: this.selectedItem,
      item: this.items[index],
      ...
    }
  }
}
```

In my `vue` file I use it like this:
``` js
<virtual-list
  :size="22"
  :remain="20"
  :bench="30"
  :item="Item"
  :itemcount="items.length"
  :itemprops="getItemProps"
/>
```

Is `getItemsProps` supposed to be called thousands of times whenever an item is added to the list or is there a bug somewhere in my code?

**Comment by tangbc** [comment]
OK, I will check.

**Comment by nahuel** [comment]
@freall Don't sure if related, but I'm seeing a BIG slowdown and too many calls to :itemprops when using vue-virtual-scroll-list versions > 1.4.1, but 1.4.1 works ok. Downgrade to 1.4.1 to check if the bug disappears.

**Comment by tangbc** [comment]
@nahuel It maybe come into some updates > 1.4.1, thanks for providing this infomation.

**Comment by tangbc** [comment]
No itemprop calls in new version, welcome to try and report.
