### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by OverTree** [tangbc/vue-virtual-scroll-list#148]
在demo(1000条数据的)界面滚动
再回到最顶部之后
detach （分离的DOM）达到了4000多

**Comment by tangbc** [comment]
> detach （分离的 DOM）达到了 4000 多
这个你是通过什么工具查看的？能否贴一下图和查看步骤。

**Comment by OverTree** [comment]
chrome 的 profile 工具
https://tangbc.github.io/vue-virtual-scroll-list/demos/vfor-mode

**Comment by OverTree** [comment]
根本原因是 vue  的 VNode， mounted ，虚化部分的组件 链接的 elm 是 null，滚动到视口内 elm 绑定dom，但是 组件销毁的时候，组件的VNode不会销毁，VNode 所绑定的 elm 链接还在

**Comment by tangbc** [comment]
好的，感谢反馈，我看一下。

**Comment by tangbc** [comment]
vfor-mode 确实存在引用没被销毁的情况，后续会解决，item-mode 是没有的。

**Comment by tangbc** [comment]
最新版，已经废弃节点实例创建的方式（vfor），采用了原地复用模式，可以尝试下。
