### ISSUE TITLE
在手机上，快速滚动后放手，滚动条往上往下滚都会在最后卡在离顶部或底部一段距离，需要手动滚多一下才能滚到顶部和底部

### ISSUE THREAD

**Issue by JowayYoung** [tangbc/vue-virtual-scroll-list#149]

**Comment by tangbc** [comment]
这个情况能否录个视频？

**Comment by yslm** [comment]
![GIF 2019-12-9 17-50-48](https://user-images.githubusercontent.com/27502697/70425626-84077600-1aac-11ea-8cdf-ace7cc034e47.gif)
看看这是啥情况

**Comment by tangbc** [comment]
看下最新版还有无问题，欢迎反馈。
