### ISSUE TITLE
List slow scroll if checkbox checked  back fast if remove checked 

### ISSUE THREAD

**Issue by ttcdev** [tangbc/vue-virtual-scroll-list#151]
Hello I have a large list about 10,000 item , it became slow scroll if I mark all checkbox checked , and back fast if I removed checked

**Comment by tangbc** [comment]
Can you offer an demo link with https://jsfiddle.net ?

**Comment by tangbc** [comment]
You can refer to this demo: https://tangbc.github.io/vue-virtual-scroll-list/#/keep-state
