### ISSUE TITLE
I want scrollTo(index) method .

### ISSUE THREAD

**Issue by xxbld** [tangbc/vue-virtual-scroll-list#152]

**Comment by tangbc** [comment]
start prop

**Comment by LouisMazel** [comment]
Example:

```html
<VirtualList
    :start="startItem"
>
```

```js
[...]
mounted () {
    const arrayIndexOfItemSelected = 6
    this.indexItemToShow = arrayIndexOfItemSelected
}
[...]
```

**Comment by sagarrabadiya** [comment]
This is valid use case, I have virtual list having 10k items, and I have keyboard navigation for ex. arrowdown/arrowup changes active item in the list, and when the active item index reaches the index which is not currently in the view then the item can't be seen, I tried `scrollTop` method but i don't understand exact calculation for that

**Comment by sagarrabadiya** [comment]
can you please provide me a way to make any item to show in the scroll view by index for ex. after component is mounted i want to show item with index 1001 in the center of scroll view?

**Comment by swapnil2222** [comment]
> can you please provide me a way to make any item to show in the scroll view by index for ex. after component is mounted i want to show item with index 1001 in the center of scroll view?

Any update on this? How to solve this usecase? I am facing the similar issue.
