### ISSUE TITLE
Scroll jumps when you use Tooltip from vuetify

### ISSUE THREAD

**Issue by Alerion** [tangbc/vue-virtual-scroll-list#154]
I got a strange bug with scrolling top. Use Vuetify and everything works good until I add [Tooltip](https://vuetifyjs.com/en/components/tooltips) to items inside virtual scroll. I spent some time and found out how this happens, but did not know how to fix this.

When new items are rendered inside `$el` this [code](https://github.com/vuetifyjs/vuetify/blob/v2.1.13/packages/vuetify/src/mixins/menuable/index.ts#L292) is executed. This triggers `onScroll` event with wrong `top` [here](https://github.com/tangbc/vue-virtual-scroll-list/blob/aa25f0c930632f1b690a996066b2bcd6686f841d/src/index.js#L262).  `top` is decreasing while scrolling top and then it become equal to `top + this.size`. Maybe accessing to window size triggers some recalculations in browser and `onScroll` event.

Google Chrome is up to date
Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by tangbc** [comment]
Can you give a living demo so I can find problem?

**Comment by Alerion** [comment]
https://github.com/Alerion/vue_virtual_scroll_list_demo

You can find a short video with demonstration in a repo
