### ISSUE TITLE
Is there a way to get Sticky headers with Virtual Scroll

### ISSUE THREAD

**Issue by shikharani16** [tangbc/vue-virtual-scroll-list#155]
Hi . I am using this  component in our application and it si working great.Now we need to implement
Sticky header ( which remain  Sticky with data on horizontal Scroll)
Is it possible with this.
This is the example of what i am looking for.

http://jsfiddle.net/avrahamcool/eZXtq/

**Comment by hacknug** [comment]
Did you try using `table-mode`? https://tangbc.github.io/vue-virtual-scroll-list/demos/table-mode/

**Comment by shikharani16** [comment]
I haven't seen it earlier so my code is currently in v-for mode. I will try it and update. Thank you

**Comment by pipinet** [comment]
https://github.com/tangbc/vue-virtual-scroll-list/issues/171

**Comment by MeirionHughes** [comment]
That table demo seems to have the same issue I'm having - the table header is outside the virtual list, so the headers don't align up when the v-list has a scrollbar.

**Comment by tangbc** [comment]
The original table mode had some problems, because it was contributed by others. I don't know his principle very well. I plan to realize it again this time.
