### ISSUE TITLE
Is possible to use with table with horizontal & vertical scrolls in one time?

### ISSUE THREAD

**Issue by JumpAttacker** [tangbc/vue-virtual-scroll-list#156]
With table its working fine, but if u have more then 6 collumns i cant see needed info from columns, so i need horizontal scroll.

With current example i dunno how to do that
https://github.com/tangbc/vue-virtual-scroll-list/blob/master/demos/table-mode/App.vue

**Comment by tangbc** [comment]
You can try use css to show horizontal scrollbar. 

If you want virtual scroll both horizontal and vertical, it's not support.
