### ISSUE TITLE
scrollelement prop 在容器存在缩放(css transform)的情况下渲染不完整

### ISSUE THREAD

**Issue by mozhs** [tangbc/vue-virtual-scroll-list#159]
### 版本
- vue-virtual-scroll-list@1.4.4
- vue@2.6.11

在线例子：[https://jsfiddle.net/prvjt8ku/](https://jsfiddle.net/prvjt8ku/)

### 问题
scrollelement 属性在容器使用了 `transform: scale()` 样式的情况下，列表项渲染不完整，在例子中可启用缩放选项进行测试，往下滚动可以看到问题。

另外，vue-virtual-scroll-list 似乎在 vue@2.2.1 (jsfiddle 中提供的版本) 不起效，例子可见 [https://jsfiddle.net/439tbyed/](https://jsfiddle.net/439tbyed/)。若是不兼容该版本可否麻烦在 README 中备注兼容的 Vue 最低版本，避免踩坑😝

**Comment by tangbc** [comment]
问题我有时间看下。
最低版本 Readme 有标识的：<img alt="Vue version" src="https://img.shields.io/badge/vue-%3E=2.3.0-brightgreen.svg"/>

**Comment by tangbc** [comment]
已发布最新版本，更新了很多，可以看下还有无问题，欢迎反馈使用意见。
