### ISSUE TITLE
[BUG] Wrong method param set in `@click` event

### ISSUE THREAD

**Issue by LouisMazel** [tangbc/vue-virtual-scroll-list#160]
Hi, 

I use your library in one of mine and I have an issue : 
- The issue : https://github.com/LouisMazel/vue-phone-number-input/issues/68
- DEMO : https://louismazel.github.io/vue-phone-number-input/

All detail is in the issue but : 
On my component, each item on the list is clickable to select it. 
Each item is a button with this event `@click="updateValue(item.iso2)"` 
Implementation here: [](https://github.com/LouisMazel/vue-phone-number-input/blob/master/src/VuePhoneNumberInput/CountrySelector/index.vue#L97)

But the value of `item.iso2` params is wrong. 

Have you a solution for me ? 

Thanks !

**Comment by tangbc** [comment]
It might be fixed in v2.0, welcome to try and report.
