### ISSUE TITLE
[BUG] unexpected behavior under keep-alive component

### ISSUE THREAD

**Issue by FrameJ** [tangbc/vue-virtual-scroll-list#161]
When routes changed under a keep-alive-router-view component, the scroll position of Virtual-List will be reseted, but its contents keep old state, so I will see a blank area in my list before I scroll it again.

**Comment by tangbc** [comment]
Can you give a example repo ov codepen so I can deal with it?

**Comment by FrameJ** [comment]
here is the demo: [https://jsfiddle.net/za9cxsk8/](https://jsfiddle.net/za9cxsk8/)

**Comment by rkuzemsky-softonix** [comment]
> here is the demo: https://jsfiddle.net/za9cxsk8/

Hi everyone. 
This issue happens because the virtual-list component does not save the scrollTop value And on activated hook it is 0. So I found a quick solution to just set it via ref. 
This is working example - https://jsfiddle.net/d46jmy2z/1/

**Comment by tangbc** [comment]
I'll try to keep the position when activated again use with keep-alive.

**Comment by fenghuijiuzhuan** [comment]
I had the same problem

**Comment by tangbc** [comment]
Do you expect to keep scroll position or reset to init state?

**Comment by fenghuijiuzhuan** [comment]
I want it to stay in its current scrolling position, but it goes back to the top and the page is blank, just like you

**Comment by tangbc** [comment]
Now in v2.0.5 support a `reset` method, keep previous position is under developping.

**Comment by tangbc** [comment]
Fixed and published in `v2.0.7`
