### ISSUE TITLE
Is there a way to have headers for each item type?

### ISSUE THREAD

**Issue by supertiger1234** [tangbc/vue-virtual-scroll-list#162]
I want a header such as Online friends and offline, like this below:
![friends list](https://user-images.githubusercontent.com/8193841/74086541-9afe2080-4a7b-11ea-9c62-1f2e4e5da9b6.PNG)

Also heres another example how i want it to be:
![members list](https://user-images.githubusercontent.com/8193841/74086547-a5201f00-4a7b-11ea-9916-141efe9b3ed9.PNG)

Is there anyway to do this?

Thanks.

**Comment by tangbc** [comment]
May be you can look on header as common render item.

**Comment by supertiger1234** [comment]
Thanks a lot but I think I figure it out and the performance is amazing! Thanks.
