### ISSUE TITLE
Hide Elements

### ISSUE THREAD

**Issue by kufdaw** [tangbc/vue-virtual-scroll-list#164]
Hi,

is there a possibility to hide elements dynamically, so I use on the same level as v-for is, v-if and expect to hide elements when I click on a button (basically I have groups and I'm doing feature to hide them).

By default it doesn't work, it just hides elements, but they are there still, (commented out, invisible - v-if default behavior), plugin count them as living elements. I tried to forceRender but that didn't work as well.

**Comment by tangbc** [comment]
Just remove elemeng from items, add back same position index when show.

**Comment by kufdaw** [comment]
> Just remove element from items, add back same position index when show.

Thanks, that just worked as I wanted.

However, I would suggest to add some "if this row should be displayed" optional prop. In my case I have groups and then each of those groups has summary and I just need to take data from original collection to show summary whenever "group" is closed. It is just suggestion and some kind of feature request, thanks for the awesome plugin and fast help :)
