### ISSUE TITLE
Problem with items

### ISSUE THREAD

**Issue by ThreadShakur** [tangbc/vue-virtual-scroll-list#166]
Hi, i need to put items this way:
![image](https://user-images.githubusercontent.com/17909421/75270986-8c01c700-580c-11ea-94f0-97eccf35900c.png)
But i got just this:
![image](https://user-images.githubusercontent.com/17909421/75271008-958b2f00-580c-11ea-8cf4-23d2c41e3a15.png)
Is there some way to do it?

**Comment by hacknug** [comment]
@ThreadShakur is your site live? Mind sharing the URL if so? #PyroGang
