### ISSUE TITLE
在flex布局中的使用，不知道是否正确？

### ISSUE THREAD

**Issue by my3188** [tangbc/vue-virtual-scroll-list#167]
我的页面是flex布局的，滚动容器也是flex布局，也就是说滚动容器的高度是不确定，我有看其他issues,你有回复说是用!important去做一些样式覆盖，在flex布局下，对virtual-list 根元素的样式进行了重新赋值**flex:1 !important; height: initial !important; display：flex !important;**   virtual-list 根元素的父容器是**display：flex;flex:1 !important;**   这样使用不知道是否是一个规范的使用？这样的话，remain感觉就失去意义了，其实对于flex布局下，remain确实是没有意义，因为必须依靠父类的高度去计算应该是多少。按照这样的使用，发现在滚动很快的情况下，突然停下来，然后整个滚动区没有完全填满item.慢一点滚动，不会有这个问题

**Comment by tangbc** [comment]
目前确实需要外容器固定高度才能方便计算，不固定高度理论上是可以的，在规划中。

**Comment by my3188** [comment]
但是目前我按照上面的方案修改了，但是依然存在我上面描述的bug

**Comment by my3188** [comment]
> 目前确实需要外容器固定高度才能方便计算，不固定高度理论上是可以的，在规划中。

但是目前是存在我上面说的那种bug的，很容易复现
