### ISSUE TITLE
Feature Request: Multiple scrolls per line

### ISSUE THREAD

**Issue by Bearfinn** [tangbc/vue-virtual-scroll-list#168]
There are some use cases where there are needs for more than one component in one line, similar to image grids. It would be good if it is able to support this.

**Comment by tangbc** [comment]
I guess just render into one item component.

**Comment by Bearfinn** [comment]
This will complicate when using `v-for` to render the list of items.
Say for example, I need to render three items in each row, it would be difficult to propagate item info if it was in the same component.
