### ISSUE TITLE
Alternating background CSS (e.g. tables) switches randomly

### ISSUE THREAD

**Issue by andreixk** [tangbc/vue-virtual-scroll-list#17]
I have a CSS table colouring as follows:

	.striped:nth-child(odd) {
		background-color:#D7ECF3;
	}
	.striped:nth-child(even) {
		background-color:#f5fbfb;
	}

and the table shows up fine, however when scrolling, my guess is occasionally it adds 1 or 2 rows causing this kind of behaviour. I added a gif showing the behaviour (watch the background of the highlighted row)

Perhaps instead of adding (or removing) exact number of rows at the top, always add the same number?

![jumps](https://user-images.githubusercontent.com/17452117/30348960-2eea1cb0-97df-11e7-8ab9-d35a74031809.gif)

**Comment by tangbc** [comment]
The shown items will change and render to another item when scrolling up or down.

For example, sometimes top index is 5 (odd), and after scrolling it may become 8 (even), this depends on the displacement produced by the scrolling distance.

If you want exact index odd or event, you better handle it according to `index`, such as:
```javascript
<virtualList :size="50" :remain="8" class="vlist">
    <Item 
        v-for="(item, index) in items" 
        v-bind:class="{ odd: index % 2 === 0 }" 
        :key="index"
    ></Item>
</virtualLlist>
```
```css
.odd {
    background: #eee;
}
```
