### ISSUE TITLE
How to add data dynamically. After adding data, the list does not show the new data

### ISSUE THREAD

**Issue by ccz-Eric** [tangbc/vue-virtual-scroll-list#170]
How to add data dynamically. After adding data, the list does not show the new data。
`this.items=this.items.concat([101,102,103,104,105,106])
      this.$refs.list.forceRender()`。
It doesn't work

**Comment by Libidine** [comment]
Hi, how did you solve the problem?

**Comment by tangbc** [comment]
Do you see https://github.com/tangbc/vue-virtual-scroll-list/blob/master/example/src/views/infinite-loading/Main.vue#L98 can help you?

**Comment by Libidine** [comment]
I use Vuex to store data, and send new messages there.

To update the chat data, I have a computed property that is passed to prop.

```
 computed: {
    messageList() {
        some code...
    }
  }
```

I just checked with the console, this property works as it should, and updates the data by sending an updated array to prop.

**Comment by Libidine** [comment]
I don't quite see how this can help, I'm a bit of a novice, sorry.

**Comment by ccz-Eric** [comment]
At that time, it was my improper use that led to problems. You can clone the official example to local and try.
