### ISSUE TITLE
How to properly use with checkboxes

### ISSUE THREAD

**Issue by adin234** [tangbc/vue-virtual-scroll-list#172]
I have a list and I used `item-mode`. When I check items and scroll, the state of the checkbox is not updated. Is there a demo we can check?

Sample Video: https://gyazo.com/af13f79e440152b70904c8d5aa3fb845
JSFiddle: https://jsfiddle.net/tjcd7q6u/3/

**Comment by tangbc** [comment]
Since `item-mode` does't use `v-for` render list, so cannot maintaining inner state, you can use `v-for` mode or waiting v2.0
