### ISSUE TITLE
Request Example: chat-app.

### ISSUE THREAD

**Issue by Dagdelo** [tangbc/vue-virtual-scroll-list#174]
Can U make an example of adding items to the top of data-source? My problem its to use the **offset** optional prop to maintain the scroll-bar position. Like in the old #28 and #128. My scenario it's a chat-app, so basically variable height and additions of elements on both top and bottom of the data-source list of items.

**Comment by tangbc** [comment]
What I come up first is adding a `goToBottom()` public method called by `ref`.

**Comment by Dagdelo** [comment]
Adding to the bottom, it's not a problem. The scroll offset remains the same after adding to the end of the data-sources. The real problem it's when adding to the top of the data-sources (unshif).

**Comment by DengXiaChen** [comment]
I encountered the same problem, when the list length changes, i change offset props, but no scroll. Pull-up loading use totop event, but no trigger.

**Comment by tangbc** [comment]
This should be the most complex application scenario, there are many problems to consider. I will try to add an example but not soon.

**Comment by tangbc** [comment]
Chat-room example has push: https://tangbc.github.io/vue-virtual-scroll-list/#/chat-room

And add some new api to adapt to this complex scenario, see release [v2.1.2](https://github.com/tangbc/vue-virtual-scroll-list/releases/tag/v2.1.2)

Any question or problem wellcome to report a new issue.
