### ISSUE TITLE
Minor glitch/stutter when scrolling through list

### ISSUE THREAD

**Issue by MOSMekawy** [tangbc/vue-virtual-scroll-list#178]
I am using V2.0. So my use case is different than what is mentioned in the documentation. I have a list of items they are the same component but different classes are applied to them depending on the item index. I uploaded an image to elaborate further. https://imgur.com/QY3U0h4. The glitch occurs when scrolling further down and i've reached the bottom of the VirtualListItems.

**Comment by MOSMekawy** [comment]
Trying to find the source of the problem i came upon this. The sizes map found in virtual.js is missing some indices btw i set the key for the list to be the sort order for it so it's the same as the index. you can see what i mean in this screen grap https://imgur.com/a/Hqi30e1.

**Comment by tangbc** [comment]
Sorry, saw two images above, I still don't quite understand, can you explain more details ?

**Comment by Dagdelo** [comment]
@MOSMekawy please provide some reproducible code for us.

**Comment by MOSMekawy** [comment]
When reaching the bottom of the list and the virtual-list component modifies the padding there's a problem with the padding calculation. What i experience is passing by the certain component and after the virtual list re-calculates padding i see the component back in view again. i logged value of the sizes map array in virtual.js file and it looks like the array isn't going in sequence it jumps a couple of indices. in the second image i provided at index 16 the key is 17 which shouldn't be the case since the key provided to virtual list is index `<virtual-list :data-key="'index'">` .

**Comment by tangbc** [comment]
And what's your `data-sources` array structures?

**Comment by MOSMekawy** [comment]
it looks like this
`[{
 Headline: '',
 DisplayDate: '',
 ImageUrl: '',
 index: 0
}]`

**Comment by tangbc** [comment]
Can you give a live demo link or video or gif. let me find out the problem?  It's hard to get.

**Comment by MOSMekawy** [comment]
hope this helps --> https://imgur.com/iu0GGSA, https://imgur.com/iu0GGSA

**Comment by tangbc** [comment]
If item contains image, try preset it's height, such as:
```html
<div class-"img" :style="{ width: imageWidth, height: imageHieght }"><img src="xxx"></div>
```

otherwise it will take a size change after item component mounted.

**Comment by tangbc** [comment]
So I'm going to close this issue, unless there's an live demo that can be reproduced.
