### ISSUE TITLE
当数据载入完后，如何禁止virtual-scroll不再滚动?

### ISSUE THREAD

**Issue by lianghuilin** [tangbc/vue-virtual-scroll-list#18]
如题，当数据载入完毕后，想通过一个标识，禁止virtual-scoll再执行loading操作

**Comment by tangbc** [comment]
你是想禁止滚动还是禁止 loading ？

如果是禁止滚动的话，可以改变一下 rclass 用 CSS 设置 `overflow-y: hidden !important;` 这时候滚动条就没有了；

如果是禁止 loading 的话，`virtual-list` 从没有做 loading 操作，只是滚到底部发个消息出去而已，到底要不要 loading 是你自己的代码决定的。
