### ISSUE TITLE
Fully virtual?

### ISSUE THREAD

**Issue by Lewenhaupt** [tangbc/vue-virtual-scroll-list#180]
Is there any way to use this in a fully virtual way where I want the scrollbar to visually represent a larger set of data then what is currently held in the client?

**Comment by tangbc** [comment]
What's the `fully virtual` means? I don't quite understand.

**Comment by Lewenhaupt** [comment]
Currently it appears that the items that are scrollable all have to be in the same list and the scrollbar is calculated based on the length of this list. What I am looking for is a way to paginate the items on the server but still have the scrollbar visualize the entire list.

**Comment by tangbc** [comment]
What ablout https://tangbc.github.io/vue-virtual-scroll-list/#/infinite-loading ?

**Comment by Lewenhaupt** [comment]
Almost, but I need the user to be able to scroll all the way to the bottom at once if they want to, so I need to scrollbar to represent the full range of data at all times. 
I have list of up to 40 million items :P So asking a user to scroll through them one page at a time won't be possible! ^^

**Comment by tangbc** [comment]
Do you mean just render first page but has a long long scrollbar (look like content has 40 million items)?

**Comment by tangbc** [comment]
If so, it may not be supported, because it'd make virtual-list more complex.
