### ISSUE TITLE
Is it possible to make "scroll to" concrete element index?

### ISSUE THREAD

**Issue by Insolita** [tangbc/vue-virtual-scroll-list#182]
Is it will be possible to create "scroll to" action for the concrete element index? For additional navigation like classic pagination, but for already loaded data?

**Comment by tangbc** [comment]
Yes, it's developing now.

**Comment by tangbc** [comment]
Published in v2.0.5

Details see: https://github.com/tangbc/vue-virtual-scroll-list/tree/v2.0.5#public-methods
