### ISSUE TITLE
Dynamic data update in [data-sources]

### ISSUE THREAD

**Issue by Libidine** [tangbc/vue-virtual-scroll-list#183]
Hi, I have a question, how does your tool automatically update data? The data that was presented in data-sources?

I do a chat, and when a new message appears in the chat, the array update is not passed through props.

Maybe I don't understand something, I apologize in advance.

**Comment by tangbc** [comment]
How do you update your data now?

**Comment by Dagdelo** [comment]
After adding items to the data source, it is necessary to use the new reset method so that they appear in the list. If we add without using this method, although the total number of items has changed, the list continues to show only the initial items.

**Comment by tangbc** [comment]
No, do not use `reset` for udpating, if use `push` and `concat` cannot update list?

**Comment by Dagdelo** [comment]
No.

**Comment by tangbc** [comment]
Is there has any problem?

**Comment by Dagdelo** [comment]
Yeah, after pushing/concat items to the list, the component list doesn't update automatically.

**Comment by tangbc** [comment]
I will check

**Comment by Dagdelo** [comment]
Just for clarification, I used this same strategy a few versions before, I think v2.0.1. And the list was updated automatically when new items were shipped.

**Comment by Libidine** [comment]
I use Vuex to store data, and send new messages there.

To update the chat data, I have a computed property that is passed to prop.

```
 computed: {
    messageList() {
        some code...
    }
  }
```

I just checked with the console, this property works as it should, and updates the data by sending an updated array to prop.

**Comment by Dagdelo** [comment]
@Libidine but the list update as expected? I mean,  in the DOM. In my case, I have to reset the component to show the new items added.

**Comment by Libidine** [comment]
> @Libidine but the list update as expected? I mean, in the DOM. In my case, I have to reset the component to show the new items added.

The DOM is not updated, and I call console. log inside the element that I pass to [data-component].

It shows that this.source has not been updated. Data appears only after the page is reloaded.

On version 1.4.7, I had this code and it worked:
```
  <virtual-list class="message-list" ref="scrollList" :size="65" :remain="12">
    <Message v-for="(message, idx) in messages" 
      :message="message" 
      :key="idx" 
    />
  </virtual-list>
```

**Comment by Libidine** [comment]
Okay, I'm still a big newbie.
My problem was that I passed parameters like this:
```
  <virtual-list
    :size="65"
    :keeps="30"

    data-key="id"
    :data-sources="items"
    :data-component="itemComponent"
  />
  data () {
    return {
      itemComponent: Message,
      items: this.messages,
    }
  },
  props: {
    messages: {
      type: Array,
      required: true
    },
```
Apparently the problem was in: **this.** messages

When I changed it like this:
```
  <virtual-list
    :size="65"
    :keeps="30"

    data-key="id"
    :data-sources="messages"
    :data-component="itemComponent"
  />
  data () {
    return {
      itemComponent: Message,
      // items: this.messages,
    }
  },
  props: {
    messages: {
      type: Array,
      required: true
    },
```
It worked as it should.
I definitely don't know a lot about the keyword **this**, and this is my mistake. Sorry for the inconvenience.
