### ISSUE TITLE
Support vue-class-component

### ISSUE THREAD

**Issue by Christilut** [tangbc/vue-virtual-scroll-list#185]
**Describe**

I'm using [vue-class-component](https://github.com/vuejs/vue-class-component) but this plugin doesn't seem to work with it.

I always get this error: `Invalid prop: type check failed for prop "dataComponent". Expected Object, got Function`

I saw another issue with the same error but I don't think this problem is solved yet.

**To Reproduce**
```
      VirtualList(
        :size='161'
        :keeps='20'
        data-key='id'
        :data-sources='items'
        :data-component='itemComponent'
        )

...

import Item from './Item.vue'

export default class MyClass extends Mixins(MyMixin) {
  itemComponent: any = Item
}
```

```
@Component({})
export default class ResultItem extends Vue {
  @Prop()
  source: any
}
```

**Other**

 - Browser: Electron 6
```
    "vue-virtual-scroller": "^1.0.10",
    "vue-class-component": "7.2.2",
    "vue-template-compiler": "2.6.11",
    "vue": "2.6.11",
```

**Comment by tangbc** [comment]
Fixed in `v2.0.8`

**Comment by Christilut** [comment]
Does this fix it or just remove the warning? Because the plugin doesn't work at all currently with the class component

**Comment by tangbc** [comment]
Yes, just add props type, but I don't know about vue-class-component a lot, so I have to learn more, maybe it will take some time.

**Comment by Christilut** [comment]
I can make a minimal repro if you want. Just let me know 👍

**Comment by ciel69** [comment]
It works for me

```
@Component({})
export default class Item extends Vue {

  @Prop(Number)
  readonly index?: Number;

  @Prop({default: {}})
  source!: Object;

}
```
