### ISSUE TITLE
Inaccurate size detection 

### ISSUE THREAD

**Issue by MOSMekawy** [tangbc/vue-virtual-scroll-list#186]
The problem i was encountering was due to JS height detection. You are probably using offsetHeight to get the height of the elements when they are rendered. The problem i am encountering while you are not in your examples is due to offsetHeight rounding up/down the height of the elements if their height contains fractions which leads to the glitch that i demonstrated before. As you scroll through the list the error accumulates causing the glitchiness to become more prominent. The only solution for this is either making sure ones list elements are whole numbers or if you are aware of another more accurate way to detect element size.

**Comment by tangbc** [comment]
Did you mean use `offsetHeight` sometimes got a decimal height value ?

**Comment by MOSMekawy** [comment]
Not sometimes offsetHeight always ignores decimals. I've found that getBoundingClientRect() is the more accurate providing up to 2 decimal points.

**Comment by MOSMekawy** [comment]
Example 
  element actual size ---> 121.25,  offsetHeight returns either 121 or 122.
  element actual size ---> 121.25,  getBoundingClientRect() always returns 121.25.

**Comment by tangbc** [comment]
But I realize that `offsetHeight` performance is much better than `getBoundingClientRect`, no matter how many items, it is inevitable.

```javascript
var el = document.querySelector('#el')
var counts = 0

counts = 10000
console.time('getBoundingClientRect')
while (counts--) {
  var rect1 = el.getBoundingClientRect().height
}
console.timeEnd('getBoundingClientRect')

counts = 10000
console.time('offsetHeight')
while (counts--) {
  var rect2 = el.offsetHeight
}
console.timeEnd('offsetHeight')
```

Result is:

![image](https://user-images.githubusercontent.com/6846113/79707187-30285b80-82ee-11ea-9dd3-a9d6e505afec.png)


If only 1000 items:

![image](https://user-images.githubusercontent.com/6846113/79707147-11c26000-82ee-11ea-839c-176eaa411ca6.png)

Although it doesn't feel like much on the computer, but on some mobile devices, the gap and smooth behavior can be serious.

So I will consider if need change it to `getBoundingClientRect` or find another way to make it accurate.

**Comment by tangbc** [comment]
The other different is: 

`offsetHeight` return the element's layout height, while `getBoundingClientRect` returns the rendering height. For example, if the element set `height: 100px; transform: scale(0.5);`, `offsetHeight` will return 100 but `getBoundingClientRect` will return 50.

So it's not as simple as just replacing an api.

**Comment by tangbc** [comment]
So I'm going to close this isssue, it does not help too much, but consumes more performance.
