### ISSUE TITLE
Padding offset could be updated

### ISSUE THREAD

**Issue by mgesmundo** [tangbc/vue-virtual-scroll-list#190]
Hi @tangbc 
your new release 2.x rocks! I've used your previous 1.x and now this is a big step forward!
I tried to update my previous component with this new version, but I see a strange behavior on scrolling (see blow).

**Description**

The padding of the virtual component (role = group) containing all items (keeps) is updated to a new value that places the first item to the top of the viewport: see ***image 1*** (before the trigger on scroll) and ***image 2*** (after the trigger).

***Image 1***

<img width="1373" alt="image1" src="https://user-images.githubusercontent.com/1668543/79973554-10349b80-8498-11ea-9f58-8e58d00af414.png">

***Image 2***

<img width="1373" alt="image2" src="https://user-images.githubusercontent.com/1668543/79973587-1fb3e480-8498-11ea-82ba-f5a62c953923.png">

I think that after the first initial scroll, the padding should be computed to repositioning the items like you see in the ***Image 3***, triggering a new value update when the first visible item has scrolled to the trigger positions (red arrows). In this way when the list is scrolled up or down, some items are available to render. The same behavior should be applied to the horizontal items.

**Image 3**

![VueVirtualScroller](https://user-images.githubusercontent.com/1668543/79975368-2859ea00-849b-11ea-8c6f-b4d1ac88677a.png)

**Image 4**

<img width="940" alt="Image4" src="https://user-images.githubusercontent.com/1668543/79975206-e5981200-849a-11ea-960e-192deba9ff94.png">

**Demo**

Below the render problem using functional components as items (stateless). The ***image 4*** shows an item structure example. I tried to increase the `keeps` prop's value, but this only helps the scroll down behavior (not the scroll up's one). The behavior is still the same using 1.000 or 100.000 items.

![VueVirtualScroller](https://user-images.githubusercontent.com/1668543/79974869-51c64600-849a-11ea-96bf-5090e5dc2b9c.gif)

**Other**

 - Version: 2.0.9
 - Browser: Chrome (see the video) and Safari (in this case the scroll is jerky on padding update)

Thank you.
All the best!

**Comment by tangbc** [comment]
I'm a little busy now, I will check what you aim at above.

If open Chrome's devtool it will bricks browser performance.

We cannot control the scrolling inertia of browser, we can only minimize the memory used and time consumed by each rendering.

You can try `v2.1.0` to see if performance get better?

**Comment by mgesmundo** [comment]
Hi @tangbc thank you for your super fast answer!
I've bad news: the 2.1.0 lost the extra-props passed to the item component.

**Comment by tangbc** [comment]
Oh... it's so funny, I have published again.

**Comment by tangbc** [comment]
v2.1.1

**Comment by mgesmundo** [comment]
Ok now it works again 😃
Thanks!

**Comment by tangbc** [comment]
What's the device in your demo gif (last image) use? The flicker looks serious.

**Comment by mgesmundo** [comment]
It's a MacBook Pro 16" i7 6 core 2,6 GHz 16GB RAM

**Comment by tangbc** [comment]
Is still happen in v2.1.0 and close devtool?

**Comment by mgesmundo** [comment]
Yes of course.
When I try to open again the devtool to make a performance test, I get this:

<img width="1357" alt="Schermata 2020-04-23 alle 12 17 50" src="https://user-images.githubusercontent.com/1668543/80089180-d29a4600-855d-11ea-9927-dcabc37054e9.png">

<img width="1357" alt="Schermata 2020-04-23 alle 12 17 55" src="https://user-images.githubusercontent.com/1668543/80089221-e04fcb80-855d-11ea-8871-ed8f96fbb0f2.png">

<img width="1357" alt="Schermata 2020-04-23 alle 12 18 04" src="https://user-images.githubusercontent.com/1668543/80089251-ea71ca00-855d-11ea-9b92-c0159629745e.png">

**Comment by tangbc** [comment]
How can I run your test in my local?

**Comment by tangbc** [comment]
It's troublesome because I can't reproduce it 😂

**Comment by mgesmundo** [comment]
I will try to build a minimal demo project to reproduce it. Anyway the problem is related to the item layout compute that appear too late when I scroll back.

**Comment by mgesmundo** [comment]
If you try the `Item` component below and you open the devtools, you see a behaviour very close to the real production component behavior with the devtools closed.

```vue
<template>
  <div class="item-inner">
    <div class="smart-listitem overflow-hidden flex-vstack tablet:mx-3 listitem select-none">
      <div class="flex-vstack flex-auto">
        <div
          class="flex-hstack flex-auto overflow-hidden tablet:rounded-t-lg slot-content-top-init slot-content-bottom-init"
        >
          <div class="fullitem flex-auto flex-vstack">
            <div class="flex-hstack border-gray-200 bg-bright">
              <div class="ml-3 flex-hstack flex-auto min-h-12 border-b-1/2">
                <div class="slot-default pr-3 flex-vstack flex-auto">
                  <div
                    class="smart-layout-root slot-default-init flex-vstack flex-auto justify-center select-none"
                  >
                    <div class="smart-layout-root px-0 flex-vstack flex-auto justify-center">
                      <span
                        class="smart-layout-editor title-area truncate min-w-0 is-readonly no-phone select-none"
                      >{{ source.name }}</span>
                      <span
                        class="smart-layout-editor subtitle-area text-xs font-light truncate min-w-0 is-readonly no-phone select-none"
                      >{{ source.desc }}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "dynamic-size-item",

  props: {
    source: {
      type: Object,
      default() {
        return {};
      }
    }
  }
};
</script>

<style lang="less" scoped>
.item-inner {
  .head {
    font-weight: 500;
  }
  span:first-child {
    margin-right: 1em;
  }
  .desc {
    padding-top: 0.5em;
    text-align: justify;
  }
}
</style>
```

**Comment by tangbc** [comment]
I have try your complex item, flicker serious only open with devtools Elements tab, close devtool or switch to Console tab is working well.
