### ISSUE TITLE
Native browser search functionality is gone

### ISSUE THREAD

**Issue by tomasdev** [tangbc/vue-virtual-scroll-list#192]
**Description**
When using the library, items that are off-screen will not be searchable anymore by any browser's native search functionality. For example, Chrome's CMD + F / CTRL + F

**To Reproduce**

1. Open https://tangbc.github.io/vue-virtual-scroll-list/#/fixed-size
2. CMD / CTRL + F
3. Enter "Nancy"
4. Observed: no results
5. Expected: a Nancy is found

NOTE: the entries are random, but in all my tests there was at least 1 Nancy in some position.

**Other**

 - Version: ALL
 - Browser: ALL

**Comment by tomasdev** [comment]
Another way to reproduce:
1. Scroll all the way to the bottom.
2. Copy the name of the 10,000th entry.
3. Scroll all the way to the top
4. Search for the value copied (a.k.a. paste it in the search field)

Observed: no results
Expected: scroll to item 10,000.

**Comment by tangbc** [comment]
This component just render part of list, out of screen items is destroy, so it cannot search by native cmd + f
