### ISSUE TITLE
How does [keeps] work?

### ISSUE THREAD

**Issue by Libidine** [tangbc/vue-virtual-scroll-list#193]
Hi, it's me again, big newbie.

I have some problems with :keeps

For some reason, the number in :keeps limits the number of items displayed in the v-list
I thought that if I load 30 items into it, then with :keeps="10", it would keep 10 div in the DOM, but display all 30 when scrolling.

Once again, I expect that by loading an array with 30 items, they will all display as in your live demo with 10000.

So what am I doing wrong? What do I understand wrong?

Sandbox: https://codesandbox.io/s/keeps-nvofi?file=/src/App.vue

**Comment by tangbc** [comment]
Now `keeps` is constant value, cannot change after initial.

**Comment by Libidine** [comment]
I don't change it.

The problem is that I load an array with 30 elements and only the first 10 are displayed, so what's the problem?

In your example here: https://tangbc.github.io/vue-virtual-scroll-list/#/fixed-size
You load 10,000 items, your example shows all 10,000, I can scroll through these items.

In my example, I can't scroll through my elements.

**Comment by tangbc** [comment]
Can you show your code here?

**Comment by Libidine** [comment]
> Can you show your code here?

Here: https://codesandbox.io/s/keeps-nvofi?file=/src/App.vue

This is a simplified representation of what I currently have in my project, with the names and structure saved.

**Comment by tangbc** [comment]
I found that scroll event doesn't fire:

![image](https://user-images.githubusercontent.com/6846113/80283335-4fd5de80-8749-11ea-8df7-4c8d662f8383.png)


Maybe your other component prevent it?

You can try a pure environment without any other component.

**Comment by Libidine** [comment]
Nothing has changed, here is a new version, with a clean environment: https://codesandbox.io/s/clean-environment-0bwkh?file=/src/App.vue

I cleared the environment and left only:
```
"dependencies": {
  "vue": "2.6.11",
  "vue-virtual-scroll-list": "2.1.2"
},
```
But you can see it for yourself in the package.json

I also changed the import and registration method for the component, as done in your example on the main page.

But the result has not changed. What did I do wrong?

**Comment by tangbc** [comment]
The problem is your work makes virtual-list no scrollbar (you set it outside), just add class `saves-list` at virtual-list:

```html
<virtual-list class="saves-list"
    ......
/>
```

Besides, it is not recommended to set `size` to `0`

Here is the fork demo: https://codesandbox.io/s/clean-environment-xymjw?file=/src/App.vue:85-89

**Comment by Libidine** [comment]
Again, my inexperience was to blame.

Thank you for helping me.
