### ISSUE TITLE
performance monitor watch DOM Nodes

### ISSUE THREAD

**Issue by DengXiaChen** [tangbc/vue-virtual-scroll-list#194]
In chat room DEMO, Fast continuous click send one random button, will get this result, Can the 
DOM nodes quantity be optimized?

![image](https://user-images.githubusercontent.com/13409926/80307187-232dcf80-87fa-11ea-90b7-8ebe789c9279.png)

**Comment by tangbc** [comment]
Chat-room demo set `keeps` to 30, nodes increase before messages length getting 30, after over 30, vue component reuse strategy make nodes stable.

**Comment by DengXiaChen** [comment]
Intuitively only 30 message item nodes, the picture above has a maximum of 3000 nodes, the number of nodes is much greater than 30 message item nodes, the largestfast and continuous generation message will get this result.

**Comment by tangbc** [comment]
What are your steps, empty type or other first?

**Comment by DengXiaChen** [comment]
In chat room DEMO, fast continuous click send one random button, [chat room demo](https://tangbc.github.io/vue-virtual-scroll-list/#/chat-room)

**Comment by tangbc** [comment]
![image](https://user-images.githubusercontent.com/6846113/80447396-e40f9380-894b-11ea-9b3b-83e306fc646d.png)

Except for setting keeps to 30, it's reuse strategy within Vue by default, I didn't know much why there was a rise and then a fall width DOM nodes, but this is not a serious. If you know, please let me know.

By the way, I don't know the way how Performance monitor counts DOM nodes length, but it's sure that not a same way with `document.querySelectorAll('*').length`. Just for guess, it includes every text, so random messages maybe few or lot of textNodes.
