### ISSUE TITLE
Main browser scrollbar and scrollToBottom

### ISSUE THREAD

**Issue by smakinson** [tangbc/vue-virtual-scroll-list#198]
**Describe**

When scrollToBottom is called and the browser window is scrolled down the page, calling scrollToBottom() jumps the main browser scrollbar to the top.

**To Reproduce**

Goto the chat example:
1. https://tangbc.github.io/vue-virtual-scroll-list/#/chat-room
2. Add enough messages to see a scroll bar on the virtual list.
3. Make the window short enough to see a scrollbar on the main window.
4. Scroll the virtual scroll list up
5. scroll down the page
6. Type a message and send it
7. Notice the browser window is scrolled up as well as the virtual list is scrolled to the bottom.

**Other**
 - Browser: chrome, safari

**Comment by smakinson** [comment]
Helpful?
https://stackoverflow.com/questions/11039885/scrollintoview-causing-the-whole-page-to-move

**Comment by tangbc** [comment]
Yes, it would be the side effect using `scrollIntoView`, I will fix it.

**Comment by tangbc** [comment]
Fixed in v2.1.4

**Comment by smakinson** [comment]
Thank you
