### ISSUE TITLE
No pagemode for v2?

### ISSUE THREAD

**Issue by bbbford** [tangbc/vue-virtual-scroll-list#199]
Hello, I am trying to use the browser window as the list container. It appears in v1 you had the option for pagemode. Why is there no similar option in v2?

**Comment by tangbc** [comment]
Page-mode and table still under developing.

**Comment by bbbford** [comment]
Thank you!

**Comment by tangbc** [comment]
Supported in v2.1.7
Here is the demo: https://tangbc.github.io/vue-virtual-scroll-list/#/page-mode
