### ISSUE TITLE
Handle dynamic lists

### ISSUE THREAD

**Issue by jamesAtcodeninja** [tangbc/vue-virtual-scroll-list#20]
Use case is when list length changes after mount. 
i.e. `remain` and `bench` are updated. 

Fixed this locally by setting watchers for `remain` and `bench` properties, and then executing the delta initialization that's done in `beforeMount`

p.s. thanks for the great component, it's a real life saver.

**Comment by tangbc** [comment]
I've thought about it before, but I think this feature is not so necessary 😂. 

Since it is useful, I plan to support it in next version .

**Comment by tangbc** [comment]
Already supported in [`v1.1.6`](https://github.com/tangbc/vue-virtual-scroll-list/releases/tag/v1.1.6)

**Comment by tangbc** [comment]
Here is a example: https://jsfiddle.net/cxbhd44v/1/
