### ISSUE TITLE
template with quotes fails to draw correctly

### ISSUE THREAD

**Issue by tiptronic** [tangbc/vue-virtual-scroll-list#203]
## Describe
Adding quotes in a template doesn't work... The quoted string is included in the output:
```vue
const itemComponent = {
  name: 'item-component',
  template: '<div><img src="{{ source.src }}" />  {{ index }} - {{ source.id }} </div>',
...
}
```

creates:
`
<img src="{{ source.src }}"   0 - image.png 245512>
`

**Comment by tiptronic** [comment]
Update: If I use vue's binding inside the template it works..., but that somehow doesn't feel right...

```vue
const itemComponent = {
  name: 'item-component',
  template: '<div><img :src="{{ source.src }}" />  {{ index }} - {{ source.id }} </div>',
...
}
```

**Comment by tangbc** [comment]
It seems not this component problem?

**Comment by tiptronic** [comment]
I don't think so.
@tangbc Yes - I think you are right - I was thinking in 'handlebars' not in 'vue' :/

**Comment by tiptronic** [comment]
Just to update to the proper syntax:

```vue
const itemComponent = {
  name: 'item-component',
  template: '<div><img :src="source.src" />  {{ index }} - {{ source.id }} </div>',
...
}
```
