### ISSUE TITLE
 Please consider the parent element style to be relative when page mode is applied.

### ISSUE THREAD

**Issue by baco16g** [tangbc/vue-virtual-scroll-list#204]
## Describe
* In page mode, **offsetTop** is set as slotHeaderSize.
* However, there is a problem if the **parent element style** is set to `position: relative`.
  * [_topPos is the number of pixels from the top of the closest relatively positioned parent element._](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetTop)

https://github.com/tangbc/vue-virtual-scroll-list/blob/f4d9be6616d920e21404bba9a9c8aa3281c2d257/src/index.js#L71-L83

## To Reproduce
1. Apply page mode.
2. Wrap the `vue-virtual-scroll-list` with an element.
3. Set `margin-top: 300px;` and` position: relative;` to the element.
4. When scrolling, there is an error in the range switching timing.

## Reproduce demo
https://codesandbox.io/s/live-demo-virtual-list-ickof

## Other
 - Version: 2.1.9
 - Browser: chrome, safari

**Comment by tangbc** [comment]
OK, I will fix it soon.

**Comment by tangbc** [comment]
Fixed and published in v2.2.0

Here is the latest version forking demo: https://codesandbox.io/s/live-demo-virtual-list-5zmj4

Also, in page mode if offsetTop change (we cannot detect a element position change in javascript), you shoud call [public mehod](https://github.com/tangbc/vue-virtual-scroll-list#public-methods) `updatePageModeFront ()` to update manually.

**Comment by baco16g** [comment]
Thanks for implementation!
