### ISSUE TITLE
 Please remove the scroll event applied to the document in the `beforeDestroy` hook.

### ISSUE THREAD

**Issue by baco16g** [tangbc/vue-virtual-scroll-list#205]
## Describe
* In page mode, scroll event is added to `document`.
* But **when the VirtualList is Unmounted, its event handler is not removed.**

https://github.com/tangbc/vue-virtual-scroll-list/blob/f4d9be6616d920e21404bba9a9c8aa3281c2d257/src/index.js#L71-L75

https://github.com/tangbc/vue-virtual-scroll-list/blob/f4d9be6616d920e21404bba9a9c8aa3281c2d257/src/index.js#L85-L87

## To Reproduce
1. Prepare a Switcher to display / hide the VirtualList.
2. Scroll when VirtualList is hidden.
3. See TypeError

## Reproduce demo
https://codesandbox.io/s/live-demo-virtual-list-28trm

## Other
 - Version: 2.1.9
 - Browser: Chrome, Safari

**Comment by tangbc** [comment]
OK, I will fix it soon.

**Comment by tangbc** [comment]
Fixed and published in v2.2.0
