### ISSUE TITLE
If the size of item is 0, EstimateSize will be used as a fallback.

### ISSUE THREAD

**Issue by baco16g** [tangbc/vue-virtual-scroll-list#207]
## Describe
* Consider a pattern in which an item component does not render content under certain conditions.
  * For example, in a list that renders only text, an empty string height is 0.
* In the short circuit evaluation below, **EstimateSize** is used as the offset value, even if I purposely set the size to 0.

https://github.com/tangbc/vue-virtual-scroll-list/blob/095a5d5f57b89fbe897e8e77b3116c8ec5c4fbc4/src/virtual.js#L220-L224

## To Reproduce
1. Scroll down to index 10. Although it is a buffer value, range does not change.
2. Scroll down to index 14.  The range has finally changed, but the padFront value seems to be incorrect.

## Reproduce demo
* I only set height to 0 for items with even indices.
* https://codesandbox.io/s/live-demo-virtual-list-dulih

## Other
 - Version 2.2.0
 - Browser chrome, safari

**Comment by tangbc** [comment]
This scene is so special but need fix.

**Comment by tangbc** [comment]
New version 2.2.1 fix it.
