### ISSUE TITLE
When the page scrolls to the bottom, the interface is called to load the next page. In this case, V-for is used for rendering. When scrolling to the bottom, the data of the next page is pushed into the array, and then the data at the bottom is pushed to the top. Is there a solution

### ISSUE THREAD

**Issue by diyiduanfa** [tangbc/vue-virtual-scroll-list#208]

**Comment by tangbc** [comment]
I don't understand your quesion, please describe clearly.

**Comment by diyiduanfa** [comment]
you can look this video
[QQ录屏20200508151936.zip](https://github.com/tangbc/vue-virtual-scroll-list/files/4597562/QQ.20200508151936.zip)

**Comment by tangbc** [comment]
Like https://tangbc.github.io/vue-virtual-scroll-list/#/infinite-loading
