### ISSUE TITLE
Checkbox state refreshes on scroll

### ISSUE THREAD

**Issue by madforstrength** [tangbc/vue-virtual-scroll-list#21]
Hi, I am using this plugin to display list with checkboxes.

But the state of checkbox is lost when scrolling down and scrolling back up.

Can you tell me how can I fix this?

**Comment by tangbc** [comment]
Did you use `:key` on `v-for` list ?

**Comment by madforstrength** [comment]
Well I have fixed the issue by using :checked attribute
