### ISSUE TITLE
Nothing shown, some errors in console

### ISSUE THREAD

**Issue by Aterr** [tangbc/vue-virtual-scroll-list#210]
Hello there @tangbc !
I am trying to get in touch with this plugin, but no success. Also tried to search through created issues here, but didn't found anything. Could you help me please with getting started.

I receive this error 3 times:
`TypeError: Cannot read property 'padFront' of null`

My code goes here:
```
<virtual-list :size="40" :remain="5" style="flex: 1;overflow-x: hidden;">
    <custom-component
        :type="row.type" 
        :locations="locations" 
        :assetStatuses="rows"
        :data="item" 
        :reasonMaintenanceList="reasonMaintenanceList"
        :canEditEquipment="false"
        @changeAsset="changeAsset"
        @toggleActive="toggleActive"
        :active="activeId == item.id"
        :key="index"
        v-for="(item, index) in sortAndFilter(row)"
    />
</virtual-list>
```

As a result I get nothing rendered.

Btw: I have 3 virtual lists on the page (may this be an issue maybe) ?

Hope, it's a minor one.
Thanks in advance!

**Comment by tangbc** [comment]
The `v2.0` is not compatible with `v1.x`, please refer to new document if upgrade to 2.0.
