### ISSUE TITLE
data-key without string does not support?

### ISSUE THREAD

**Issue by ducvietsqt** [tangbc/vue-virtual-scroll-list#211]
I has data with primary key is `id` has type is Integer then by binding data list with data-key props but that not working? pls help let me how to binding data-key is Number will passing conditions data-key library 
ex:
`[{id: 12, value: 'fdsfdsfdsfdsdfs'}, {id: 4: value: 234567}]`

**Comment by tangbc** [comment]
It's ok width number: https://codesandbox.io/s/live-demo-virtual-list-4xbm6?file=/src/data.js:134-156

Has any warnings or errors?

**Comment by ducvietsqt** [comment]
@tangbc 
Yea! I tried but look at the console we are see warning from vue warn, that does not make app stuck but list of warning on console are unfriendly, i think need resolve issue on that console.
Preview:
https://imgur.com/hc85HUr

**Comment by tangbc** [comment]
New version 2.2.2 already publish to remove these warnings.
