### ISSUE TITLE
:page-mode="true" throws warning/TypeError

### ISSUE THREAD

**Issue by ipartola** [tangbc/vue-virtual-scroll-list#213]
## Describe
I keep seeing `TypeError: handler.apply is not a function` when enabling page mode.

## To Reproduce
Go to https://codesandbox.io/s/live-demo-virtual-list-e1ww1?file=/src/App.vue and add `:page-mode="true"`. Watch the console output to see the warning/error show up.

## Reproduce demo
https://codesandbox.io/s/live-demo-virtual-list-ex77l

**Comment by tangbc** [comment]
If using page-mode, you must remove container scrollbar.

In this demo, just remove `style="height: 360px; overflow-y: auto;"`

But it's better to throw a warning if developer using a wrong way, I will consider it.
