### ISSUE TITLE
原传入的数组数据, 重新排序后再传入, 显示有变动, 但显示排序和实际传入数据对象不一致

### ISSUE THREAD

**Issue by lzf1201** [tangbc/vue-virtual-scroll-list#216]
使用dataSources传入数据 , 单条数据用dataComponent渲染

## To Reproduce
1. Click on '....'
2. Scroll down to '....'
3. See error

## Reproduce demo
Providing a reproduce demo of this bug, that will help me solve the problem more quickly. You can fork by this online demo: https://codesandbox.io/s/live-demo-virtual-list-e1ww1 

## Other
 - Version [e.g. 2.0]

**Comment by tangbc** [comment]
麻烦弄个复现 demo 比较好查。

**Comment by lzf1201** [comment]
可能我搞错了, 是老组件的问题.
