### ISSUE TITLE
Vuex getters not working.

### ISSUE THREAD

**Issue by ykamal** [tangbc/vue-virtual-scroll-list#222]
## Describe
Project done with electron-nuxt.
Error getting:
![image](https://user-images.githubusercontent.com/50125998/82734899-aaaa2800-9d3f-11ea-8278-37a2c9d6b1f4.png)

## To Reproduce
Any sort of vuex getter/action/state access returned as undefined.

Thanks for any advice!

**Comment by tangbc** [comment]
Try remove this warning first: https://github.com/tangbc/vue-virtual-scroll-list/issues/184#issuecomment-615982427
