### ISSUE TITLE
Limit number of items loaded

### ISSUE THREAD

**Issue by chrissyast** [tangbc/vue-virtual-scroll-list#226]
I am not sure if vue-virtual-scroll-list does not do what I expected, or maybe I have implemented it incorrectly.

I currently have a `v-for` where there are around 40 items. Each item is an instance of component, and that component has an API call in the mounted 

**index.vue**
```
<div v-for="(item) in items">
   <another-component
    :prop="item"
    >
</div>

```

**AnotherComponent.vue**
```
...
async mounted() {
   this.property = await someApiCall
}

```
Rather than doing this for 40 items, I wanted to only do it for the first 5 or 6 that will be visible at the top, and then create more instances when the user scrolls down through the list.

After implementing vue-virtual-scroll-list I see in the Network tab of DevTools that the call is still being made for all of the items. Do I need to impose some kind of limit?

**Comment by tangbc** [comment]
It's a bit of a puzzle, you can't use item component `mounted` hook in this library, becasue most of are not triggered.

**Comment by chrissyast** [comment]
> @tangbc  you can't use item component mounted hook in this library, becasue most of are not triggered.
It seems I have the opposite problem. The mounted hook is being triggered when I don't want it to be.

> (Me) Rather than doing this for 40 items, I wanted to only do it for the first 5 or 6 that will be visible at the top, and then create more instances when the user scrolls down through the list.

Is what I want to do possible in this library?

**Comment by tangbc** [comment]
It's hard to do such a special thing.

**Comment by chrissyast** [comment]
> It's hard to do such a special thing.

@tangbc you have an [example](https://tangbc.github.io/vue-virtual-scroll-list/#/infinite-loading) where this exact thing happens. The loading extra items is done [outside of this plugin](https://github.com/tangbc/vue-virtual-scroll-list/blob/master/example/src/views/infinite-loading/Main.vue#L85) so I'm still not entirely sure what the purpose of this library but your communication is very poor so I can see I'm wasting my time.

**Comment by tangbc** [comment]
Sorry for that, my english is poor, so I can't get what your description accurately.
