### ISSUE TITLE
Get access for previous/next item

### ISSUE THREAD

**Issue by kirillarutyunov** [tangbc/vue-virtual-scroll-list#230]
## Describe the feature request

It will be great to add some props for enable props with previous or next elements. Sometimes I need to get access prev or next item to make some compares.

For example:
```
<VirtualList
  class="stream scroll-touch"
  :class="{ overflow: listOverflow }" ref="vsl"
  :data-key="'id'"
  :data-sources="items"
  :data-component="itemComponent"
  :estimate-size="100"
  :enablePreviousItem
/>
```

If `enablePreviousItem` set to `true`, than I get `previousSource` prop in my ItemComponent. So the same we can do with nextSource.

What do you think? Or is it possible now?

**Comment by kirillarutyunov** [comment]
I've just try to implement this feature. If it is ok, I will create PR.
Just let me know :)

**Comment by tangbc** [comment]
Maybe you can get previous or next by a more efficient way like this:

```vue
<template>
  <div>
    <virtual-list
      ...
      :extra-props="{ getPrevious, getNext }"
    />
  </div>
</template>

<script>
  export default {
    ...
    methods: {
        getPrevious (index) { ... }
        getNext (index) { ... }
    }
  }
</script>
```

Then in item component you can call `getPrevious` and `getNext` with `index` form props.

**Comment by kirillarutyunov** [comment]
Hmm. Looks good, I will test it 🤔
Thanks for this idea!
