### ISSUE TITLE
V2 only renders keep number of rows

### ISSUE THREAD

**Issue by camhart** [tangbc/vue-virtual-scroll-list#235]
## Describe
Only the {keep} number of rows are being rendered in v2 for me.  For example, if keep is set to 30 I get 30 rows rendered.  Continuing to scroll just shows white space and the items aren't ever updated.

## Other
 - Version 2.2.7
 - Browser chrome

**Comment by camhart** [comment]
This is due to not setting a explicit height value for the `virtual-list` element.  Unfortunately this used to not be necessary--previously I could embed it all within a full-screen dialog and it would work.  In v2 this no longer is the case.

**Comment by tangbc** [comment]
Did you mean use `height: 300px; overflow-y: auto` works well but use `height: 100%; overflow-y: auto` is broken?

**Comment by camhart** [comment]
In v1 I didn't need to set an explicit height for the virtual-list element (whether 300px or 100%).  In v2 it appears to be required.

**Comment by tangbc** [comment]
In v1 use `remain` × `size` to set an explicit height for the list. 

Can you give a demo reproduce your problem?

**Comment by asheb** [comment]
For me it always renders only `keeps` number of elements, even with `height: 100%` or `height: 100%` set for the `virtual-list` element's style. Additionally, when scrolling, even less number of elements is visible...

**Comment by tangbc** [comment]
Prop `keeps` is not data-reactive.

**Comment by asheb** [comment]
Ok, thanks for clarifying! I've ended up calculating it from the screen height, so it seems to work pretty well now.

**Comment by tangbc** [comment]
Yes, `keeps` just a prop to control how many DOMs be rendered, it's no significance in user interface.

**Comment by CBulFel** [comment]
In v2,  I use page mode, but it would appear a blank area under page below. i also make  value of 'keeps' more bigger, also not solved.
