### ISSUE TITLE
Doesn't work on iPads and iPhones in page mode

### ISSUE THREAD

**Issue by aarrttzz** [tangbc/vue-virtual-scroll-list#236]
## Describe
The library doesn't works on iPads and iPhones in page mode
I tried almost all physical and virtual devices

## To Reproduce
1. Open browser in iPhone or iPad
2. Go to https://tangbc.github.io/vue-virtual-scroll-list/#/page-mode
3. Scroll down

The list show only first 30 items, after blank list
![image](https://user-images.githubusercontent.com/7055992/84142762-0d990000-aa5e-11ea-8119-8e4abf9ec770.png)

**Comment by tangbc** [comment]
That maybe some with #206

**Comment by tangbc** [comment]
Fixed in new version v2.2.8, please see if solved.
