### ISSUE TITLE
列表中滚动到最后一页会发现概率性缺失，range计算错误

### ISSUE THREAD

**Issue by youzime** [tangbc/vue-virtual-scroll-list#238]
## Describe
通过下拉混动条、事件scrollToBottom、手动滚动到底部过程中会出现页面下半部分白屏现象，当滚动到最底部时会有几条数据没展示（其中手动滑轮滚动的缺失条数每次不一样，下拉滚动条和事件触发都是恒定n条，其中Mac和window下试过不一样，Mac通过事件是能展示全的）

## To Reproduce
```
<virtual-list
      ref="listWrapper"
      style="height: 600px;"
      class="scroll-wrapper"
      :data-key="'value'"
      :data-sources="lists"
      :data-component="itemComponent"
      :estimate-size="18"
    ></virtual-list>
```
下面是itemComponent
```
<template>
  <el-checkbox
    :label="source.value"
    :key="source.value"
    :value="source.checked"
    @change="changeCheck"
  >{{ source.value }}</el-checkbox>
</template>
```
最后一页的时候data中range计算值为(实际上有1000条数据)
{"start":967,"end":996,"padFront":17426,"padBehind":54}

## version
list：v2.2.8
vue:  v2.6.11
chrome: 83.0.4103.97

**Comment by tangbc** [comment]
能在 demo 中复现吗？https://tangbc.github.io/vue-virtual-scroll-list/#/fixed-size

或者你的使用场景比 demo 有什么特殊布局吗？

**Comment by youzime** [comment]
https://codesandbox.io/s/live-demo-virtual-list-gfu9d  我把代码放上去了可以复现，就使用了element的多选框。然后在滑轮滚动过程中下方间距计算错误，导致没展示全，可以上下多滚动几次。

**Comment by towry** [comment]
![截屏2020-06-12 14 04 02](https://user-images.githubusercontent.com/8279858/84470291-9b225d00-acb5-11ea-8054-fe2a11bcfcc7.png)


的确有问题，向上滚动的时候。

**Comment by tangbc** [comment]
看了下是因为你设定的外容器是 600px 高度太高了，然后每个选项的高度大约是 22px，默认渲染数量 keeps 为 30，也就是 30 × 22 = 660px，组件内部为了渲染性能会有一个 keeps ➗ 3 的滚动 buffer，也就是 10 × 22 = 220px，所以你的外容器高度最好不要超过 660-220 = 440px。

你可以设置外容器高度小一点，或者设置 keeps 大一点，或者每个选项的高度设置大一点。

**Comment by youzime** [comment]
> 看了下是因为你设定的外容器是 600px 高度太高了，然后每个选项的高度又太小了大约是 22px，默认渲染数量 keeps 为 30，也就是 30 × 22 = 660px，组件内部为了渲染性能会有一个 keeps ➗ 3 的滚动 buffer，也就是 10 × 22 = 220px，所以你的外容器高度最好不要超过 660-220 = 440px。
> 
> 你可以设置外容器高度小一点，或者设置 keeps 大一点，或者每个选项的高度设置大一点都行。

感谢，已经解决！

**Comment by CBulFel** [comment]
我是用page-mode的模式也会出现这个问题，外容器高度就是页面的高度，这个怎么解决？

**Comment by CBulFel** [comment]
![image](https://user-images.githubusercontent.com/18042532/92070749-800c4880-eddf-11ea-9b74-b1a13be944a3.png)

**Comment by CBulFel** [comment]
在chorme下会偶现，在safari下会必现，你给的demo也会出现

**Comment by tangbc** [comment]
好的有空我查一下。

**Comment by tangbc** [comment]
@CBulFel 你截图的是 infinite-loading 这个是已知问题（滚动回弹）正在处理。但是 page-mode 应该是没有问题的，复现不了，具体怎样复现？

**Comment by CBulFel** [comment]
@tangbc 我这里用到的是page mode里面的滚动回弹

**Comment by siyuewuyu** [comment]
我删除数据后出现这种情况了  dom展示计算失误的 下面留白了
