### ISSUE TITLE
render a plain list without additional group or root node...

### ISSUE THREAD

**Issue by tiptronic** [tangbc/vue-virtual-scroll-list#239]
How can I get rid of the 'role=group' wrapper?

Reason:
I want to render a list, like so:
```
<div id="existing node">
<ul>
  <li>...</li>
</ul>
... here are other ul and they need to stay at the same level, so I need the structure above...
```
It seems, I can't get that to work. VSL always renders a 'group' node between `<ul>` and `<li>` or it adds an additional root node above `<ul>`...

Is there any way I can just create a simple list and attach it to an existing root node? (without additional nodes?

thx

**Comment by tangbc** [comment]
What about `root-tag`, `wrap-tag` and `item-tag`?

**Comment by tiptronic** [comment]
Sorry, maybe I was not really clear on this....

-> The incoming data is an array and I need just 2 tags `<ul>` and `<li>`..
If I do this:
`:data-sources="arrItems" root-tag="ul" root-class="todo-list"  wrap-tag="li" wrap-class="todo-item" item-tag="div"`

Then it renders the array inside the `<li>` element:

<img width="329" alt="image" src="https://user-images.githubusercontent.com/80752/84633859-4d923400-aef1-11ea-82c4-6898c75f7a02.png">

If I do this:
`root-tag="div" wrap-tag="ul" item-tag="li"`

then it renders with the extra div

<img width="354" alt="image" src="https://user-images.githubusercontent.com/80752/84634773-97c7e500-aef2-11ea-8e73-daa90576e69f.png">

**Comment by tangbc** [comment]
Current structure is:
```html
<RootForMakeScrolling>
  <GroupForContainsAllList>
    <ListItemWraperForDetectSizeChange>
      <YourCustomItem />
    </ListItemWraperForDetectSizeChange>
    <ListItemWraperForDetectSizeChange>
      <YourCustomItem />
    </ListItemWraperForDetectSizeChange>
    ... ...
  </GroupForContainsAllList>
</RootForMakeScrolling>
```

If you need 2 tags <ul> and <li>, it's hard to structure it.

**Comment by jzstern** [comment]
How would you customize CSS on the element containing `role="group"`?

```<RootForMakeScrolling>
  <GroupForContainsAllListAndEnableScoll>
    <ListItemWraperForDetectSizeChange>
      <YourCustomItem />
    </ListItemWraperForDetectSizeChange>
    <ListItemWraperForDetectSizeChange>
      <YourCustomItem />
    </ListItemWraperForDetectSizeChange>
    ... ...
  </GroupForContainsAllListAndEnableScoll>
</RootForMakeScrolling>
```

It looks like `<GroupForContainsAllListAndEnableScoll>` is the wrapper that @tiptronic and I are referring to.

I'm trying to render a list of images that is 3 images wide and scrolls endlessly, but I'm not sure how to add CSS to the wrapper element that contains `role="group"`.

**Comment by tangbc** [comment]
@jzstern see [optional-props](https://github.com/tangbc/vue-virtual-scroll-list#optional-props) `wrap-style` and `wrap-class` maybe can help.
