### ISSUE TITLE
Is there any way to get an update event

### ISSUE THREAD

**Issue by sstenn** [tangbc/vue-virtual-scroll-list#241]
I'm using this to render a table. For the `<thead>` I've made an extra table where the column width is synchronised to the virtual list table.

Every time when the DOM changes, the virtual list table changes the column width. I need an update event here so I can synchronise the `<thead>` column width.

**Comment by tangbc** [comment]
Maybe `resized` event helps.

And chat-room demo always detect every message updated: 
https://github.com/tangbc/vue-virtual-scroll-list/blob/deab7207f44a6d732ebcd8c7eb12d7e61dca2020/example/src/views/chat-room/Main.vue#L111-L123
