### ISSUE TITLE
Force render of items

### ISSUE THREAD

**Issue by Luiz-N** [tangbc/vue-virtual-scroll-list#243]
I have items that wait on a async call for data after rendering. I would like to refresh the UI after the data has returned. is there a way to force a refresh? I tried `$forceUpdate` but that did not work. The only way I can see any changes is if I scroll enough to force new items to be added.

**Comment by tangbc** [comment]
Just change `data-sources` array items.

**Comment by Luiz-N** [comment]
ok i just realized the view was not updating because I called `Object.freeze()` on the items array before setting them into vuex for performance reasons. This is what gets fed into the virtual list via a mapped getter. I thought the properties for each individual item would still be reactive since they get fed individually into the itemComponent but that does not seem to be the case... 

Any suggestions or workarounds for this?

**Comment by Luiz-N** [comment]
I was able to solve my problem by using a watcher in my item component that does the async upon creation
