### ISSUE TITLE
当滚动到会触发更新列表的位置时，会重新渲染 list,而不是只渲染新增的 item，dataComponent 复杂时会有明显卡顿

### ISSUE THREAD

**Issue by fzred** [tangbc/vue-virtual-scroll-list#244]
## Describe
似乎是vnode算法不起作用？

## Other
 - Version 2.3.0

**Comment by tangbc** [comment]
这个原理其实并不是只渲染新增的元素，而是根据滚过的距离不断更新渲染的区间：
```html
1                  4
2                  5
3                  6
4                  7
5                  8
6    scroll =>     9
7                  10
8                  11
9                  12
10                 13
11                 14
12                 15
```

所以更新时必然是所有一起更新，但 Vue 底层策略对于这些 vnode 是最大化复用的，如果 component 很复杂的话快速滚动，虚拟列表是避免不了卡顿的，freeze 数据会好点，不过目前内部也还尚未达到最理想的性能，有优化空间。

**Comment by fzred** [comment]
keeps 值大的时候会卡顿会更严重，值小的话就会比较频繁触发更新也有点卡顿。
我正在看源码，请问有没有能优化的方法指点一下。

**Comment by tangbc** [comment]
参数 `data-sources` 的数据被 watch 有可能是性能损失最大的地方，因为如果数据越复杂，Vue 的数据监听就越多内存消耗也会越大。

之前有种方案是参数不传数组数据，而是用方法调用获取，实现 0 数据监听，具体可以看下 v1.x 的 `item-mode` 使用方式：[item-mode](https://github.com/tangbc/vue-virtual-scroll-list/blob/master/v1.x.md#item-mode)。这种方式应该是性能最好的，但是有个非常不好的地方：无法监听列表数据变化，数据更新的同时需要手动调用强制更新，使用体验太不友好，所以 v2.0 抛弃了这个模式。
