### ISSUE TITLE
Vue warn: $attrs $listeners is readonly

### ISSUE THREAD

**Issue by MikhailYermolenko** [tangbc/vue-virtual-scroll-list#245]
## Describe
In my project I use more than one instance of Vue and i need  ability to become attached to different instance.
 ![image](https://user-images.githubusercontent.com/8962979/85871983-d6ee1400-b7d7-11ea-9b07-51def91ec57d.png)

[This](https://github.com/tangbc/vue-virtual-scroll-list/issues/184#issuecomment-615982427) solution not working for me.
Maybe you have any suggestions?

**Comment by tangbc** [comment]
Is your project has more than one `package.json` have dependencies Vue? 

Need more than one instance of Vue, but unnecessary including Vue to every `package.json`, just put it in root `package.json`.

**Comment by MikhailYermolenko** [comment]
My project is divided into several small ones, and each has own package.json. And every small projects has test coverage, for tests I need to include Vue in every package.json. That's why i cant put Vue in root package.json

**Comment by tangbc** [comment]
I think just include only one Vue on top/root dir package.json is ok because node_module is finding module automatic by parent dir.

If cannot make that, can you upload a simple demo repo?
