### ISSUE TITLE
extra-props

### ISSUE THREAD

**Issue by dcartier-mandiant** [tangbc/vue-virtual-scroll-list#246]
How do you pass props to the item component?

I noticed there is a key word extra-props.  However, in the prop section of the component, what would be the receiving value?

**Comment by dcartier-mandiant** [comment]
Nevermind, figured it out out.  the receiving end will be the key-value pairs within the object assigned to extra-props.

**Comment by ahhmino** [comment]
> key-value pairs within the object assigned to extra-props

@dcartier-mandiant Can you clarify this part? Let's say I have an extra-props like so:
`:extra-sources="{test: 'hello'}"`

What would the expected prop on the receiving end be? Something like this?
```  
props: {
    source: Object,
    test: String
  },
```
