### ISSUE TITLE
TypeError: Unable to get property 'slotHeaderSize' of undefined or null reference

### ISSUE THREAD

**Issue by conlanpatrek** [tangbc/vue-virtual-scroll-list#247]
## Describe
Seeing this stacktrace in logs:
```
TypeError: Unable to get property 'slotHeaderSize' of undefined or null reference
  at value(./node_modules/vue-virtual-scroll-list/dist/index.js:229:9)
  at this(./node_modules/vue-virtual-scroll-list/dist/index.js:203:9)
  at this(./node_modules/vue-virtual-scroll-list/dist/index.js:194:11)
  at methods.onScroll(./node_modules/vue-virtual-scroll-list/dist/index.js:824:9)
```

EDIT: I am running in page mode, here are the details
```
<virtual-list
      class="leaderboard__container"
      page-mode
      :style="{ minWidth }"
      :data-sources="rows"
      :data-key="row => row.user.id"
      :data-component="Item"
      :extra-props="{
          //...
      }"
      :keeps="100"
      @expand="expanded = $event"
      @selectVideo="$emit('selectVideo', $event)"
/>
```

## To Reproduce
Haven't been able to reproduce myself, but I only see two spots in the codebase where the scroll event might fire while virtual.param is null:

https://github.com/tangbc/vue-virtual-scroll-list/blob/master/src/index.js#L81-L86
-- Please consider unregistering the scroll event before calling virtual.destroy()

https://github.com/tangbc/vue-virtual-scroll-list/blob/master/src/index.js#L186-L190
-- Unlikely to be causing my issue. reset() isn't called in this codebase and we're not using a component ref
-- Please consider installing the new Virtual instance before scrolling, or deregistering scroll handlers during this operation

## Reproduce demo
Unable

## Other
 - Version 2.3
 - Browser IE11 from what I can see

Thank you

**Comment by tangbc** [comment]
OK, I will fixed it.
