### ISSUE TITLE
ItemComponent

### ISSUE THREAD

**Issue by sadelokiki** [tangbc/vue-virtual-scroll-list#248]
How do you listen for an event from ItemComponent? E.g, when an item from the list is clicked and you want to listen for that click event

**Comment by tangbc** [comment]
Refer to https://github.com/tangbc/vue-virtual-scroll-list/issues/237#issuecomment-641935872 or [keep-state](https://tangbc.github.io/vue-virtual-scroll-list/#/keep-state).
