### ISSUE TITLE
How to deal with Ansi terminal ?

### ISSUE THREAD

**Issue by Seraf** [tangbc/vue-virtual-scroll-list#249]
Hello,

I'm currently writing a console that is streaming terminal output.
When showing a Jest output that is like 8k lines, the browser started to be really laggy, that's why I had a look on your (fantastic) library.

I'm currently giving computed props to the component that contains the list of messages.
The problem I'm facing is that it's ANSI, and then, it could rewrite the terminal output using special commands like 1A, K.
Doing this, I'm rewriting some rows. While it seems to be working (I know that's not the best thing to do), the lib seems to complain: `index.js?89c1:881 Cannot get the index '61' from data-sources`

It seems to happen on https://github.com/tangbc/vue-virtual-scroll-list/blob/master/dist/index.js#L882
Do you have some suggestions on how could I handle it? Would there be a way to at least ignore the warning?

Thank you!

**Comment by tangbc** [comment]
The direct reason is that the specific item of index 61 is not found in `data-sources`(total length less than 61) while list rendering, and the specific reason is not easy to judge and should be inferred according to the actual use scene.

It's good to work out if you can provide an reproduce demo to me.

**Comment by Seraf** [comment]
Hello @tangbc,

Sorry for the delay, here is the reproduced code: https://jsfiddle.net/30yovezw/6/

My code as you can imagine is a bit more complex but I tried to reproduce the behavior.
As I want to show a terminal, when the terminal cursor move above the line, erase the line, then move above, etc.

I'm reproducing here the behavior of a terminal, I'm not sure I should keep empty lines there. WDYT?

**Comment by Seraf** [comment]
@tangbc were you able to reproduce/understand my problem ? do you need more info ?

**Comment by tangbc** [comment]
Sorry for long time, My network can't open website jsfiddle, can you use codepen(https://codesandbox.io/s/live-demo-virtual-list-e1ww1)?

**Comment by Seraf** [comment]
Sure ;-) here it is : https://codepen.io/Seraf42/pen/ZEQZmLp

**Comment by tangbc** [comment]
Why don't you use `splice` to update data?

```js
generateData() {
  // delete this.ansiLines[9];
  // this.$set(this.ansiLines, 8, { id: 'identifier-8', log:'this line has been rewritten'})
  
  this.ansiLines.splice(9, 1, { id: 'identifier-8', log:'this line has been rewritten'})
}
```

**Comment by Seraf** [comment]
Hello, I'm sorry I didn't had the time to answer.
I finally succeeded to implement something like that even if it wasn't the best way ^^
Thanks for the suggestion :+1:
