### ISSUE TITLE
Items are missing

### ISSUE THREAD

**Issue by James-Hudson3010** [tangbc/vue-virtual-scroll-list#256]
## Describe
I should be able to scroll and see 60 items.

## To Reproduce
I have a CodePen at:

https://codepen.io/james-hudson3010/pen/MWygQoO

## Reproduce demo
When scrolling the list, the last items that appears is #29

## Other
 - Version https://unpkg.com/vue-virtual-scroll-list@2.3.0/dist/index.js
- Latest version of Chrome

**Comment by tangbc** [comment]
Adding a fixed size such as `height: 400px` to `<virtual-list/>` style:

```html
<virtual-list 
    ......
    style="overflow-y: auto; height: 400px"
    ......
>
</virtual-list>
```
