### ISSUE TITLE
listitem height calculated wrong

### ISSUE THREAD

**Issue by mozartilize** [tangbc/vue-virtual-scroll-list#258]
## Describe
Most of my item components have height of 0, some of them have heights round to scroller's scrollHeight.
Have a look to your examples, all have height equal to its inner element.
Dont know exactly why but my item component uses lot of v-if and v-else-if and inside of them are kind of different (div, video, img...)

## Other
 - Version newest
 - Browser: chrome, firefox

**Comment by tangbc** [comment]
There maybe some problems with v-if or v-show which toggle display frequently, this library suitable for layout static item. But how can I reproduce your problem.

**Comment by mozartilize** [comment]
I'll try to add an example in this weekend

**Comment by mozartilize** [comment]
I tried to make an example here https://codesandbox.io/s/live-demo-virtual-list-forked-3x7x9?file=/src/App.vue but cant reproduce what happened in my work project. I think the reason is img and video tags are loaded later and the heights of items get changed after that. But it's not reproduced in the example therefore I think there's maybe something wrong with our code. Now I dont maintain the project so I just close it.
