### ISSUE TITLE
Display problems in multi list switching

### ISSUE THREAD

**Issue by aisin** [tangbc/vue-virtual-scroll-list#26]
I have two lists (short-list & long-list) that need to be displayed, and I encountered a display problem when I was switching them.

Demo: https://jsfiddle.net/aisin/7y8h2q1k/3/

**How to recurrence:**

- At first, SHORT-list will be displayed.
- click `show LONG-list` button to display it.
- Scroll down at least more than 3 items.
- click `show SHORT-list` button.
- click `show LONG-list` button.

Now, You should see only the first 6 items are displayed, until scrolling down you can see all of them.
How to support the correct display of multi list switching?

**Comment by tangbc** [comment]
Thanks for reporting this bug, fixed in [v1.1.8](https://github.com/tangbc/vue-virtual-scroll-list/releases/tag/v1.1.8)
