### ISSUE TITLE
Animation for scrollTo methods

### ISSUE THREAD

**Issue by stefandesu** [tangbc/vue-virtual-scroll-list#260]
## Describe the feature request

Hi, it would be nice to have animated scrolling with the `scrollToBottom/Index/Offset` methods. Maybe this could even improve `scrollToIndex` because during animation it could recheck whether the estimated scroll position is correct and readjust if necessary (I noticed that if `estimate-size` is too far off, it doesn't scroll to the correct item). I would suggest a second parameter with the scroll duration in milliseconds.

Thanks for this great library! When I tried out several such libraries last year, none of them met the requirements we needed to be integrated into our project. But I've tried this one out again today and it seems to have it all now! Animated scrolling is the only thing that I was missing that would be a nice feature.

**Comment by tangbc** [comment]
The experience and performance may not be great if use animation with virtual list because in animate duration maybe see blank items.

**Comment by stefandesu** [comment]
That's true, I haven't considered the blank items. Maybe it would be possible to show something like a fake scrolling animation with placeholders? The programmatic scrolling is important in our application and the animation can show the user that something actually happened there.

Maybe I can try to implement something myself, but I don't have much experience with DOM manipulation and scrolling.

**Comment by tangbc** [comment]
I think you can fork this repo and and implement it, if experience is good you can make a pr.

**Comment by kgrosvenor** [comment]
This would be nice in horizontal mode ngl, i only want to skip two items at a time
