### ISSUE TITLE
Height Issue

### ISSUE THREAD

**Issue by bionicode** [tangbc/vue-virtual-scroll-list#261]
Hi I'm using this inside a b-list-group, and I made my Item a b-list-group-item.  It works amazingly fast for a large array.

My only problem is that before when I was using v-for on b-list-group-item, albeit painfully slow, it did correctly calculate the height for the b-list-group for me.

Not sure how to get around this fixed height for the list.

Just to be clear.  I'm not talking about the size of each item in the list.  I'm talking about the size of the container (virtual-list), which seems to have a fixed height in all the examples.

**Comment by tangbc** [comment]
In all examples use a fixed height on outer container just make sure list scollable, you can use percent height or other ways but not recommended to change outer container height frequently.

**Comment by bionicode** [comment]
When I try to use percent height, everything looks correct, but the list items disappear soon after I start scrolling.  With fixed height it works, but the layout in my sidebar is clunky when the screen is resized.

**Comment by slidenerd** [comment]
can the outer container use flex 1?

**Comment by tangbc** [comment]
> When I try to use percent height, everything looks correct, but the list items disappear soon after I start scrolling. With fixed height it works, but the layout in my sidebar is clunky when the screen is resized.

er.. I will try to seem that problem, but they it's better if you can give me a example.
