### ISSUE TITLE
Get first element displayed. 

### ISSUE THREAD

**Issue by starfear** [tangbc/vue-virtual-scroll-list#262]
I tried to listen to event `onscroll`. Second argument data is `{ start: 0, end: 7, padFront: 0, padBehind: 0 }` even if the first element displayed has index 2 or 3.

I understand it's something like range of rendered nodes in dom, but can I get really displayed indexes using this library? Or should I do it myself ?

**Comment by tangbc** [comment]
Now no public api offer that, but you can judge form offset data.
