### ISSUE TITLE
表格内容部分实现虚拟列表

### ISSUE THREAD

**Issue by zhuyinjing** [tangbc/vue-virtual-scroll-list#264]
你好，我现在页面上有一个 table ，我想实现这个表格里的内容部分是虚拟列表。我将如何添加代码？谢谢。
我使用的代码如下：
`<virtual-list style="height: 360px; overflow-y: auto;"
      :data-key="'uid'"
      :size="40"
      :remain="8"
      :data-sources="items"
      :data-component="itemComponent"
    />`

**Comment by zhuyinjing** [comment]
如果我把teble标签放在 itemComponent 里，那么页面会循环生成很多表格。

**Comment by tangbc** [comment]
这个只能靠业务侧尝试分开布局了，内部不太好保留整体结构的情况下实现部分虚拟列表，实现起来挺难也没必要这么做。
