### ISSUE TITLE
Not working with tables as expected

### ISSUE THREAD

**Issue by bhargavr445** [tangbc/vue-virtual-scroll-list#268]
When rendered data using div tags this is working fine, but when rendering with table tag this is not working as expected. After 7th record it is not displaying 8th record. It is displaying last 20 records(Ex- If I have 100 records it is displaying 1-7 records and after scroll it is displaying from 70-100 records in table).

**Comment by tangbc** [comment]
Table mode not support yet.

**Comment by brizer** [comment]
> Table mode not support yet.

How about now, it is supported ?
