### ISSUE TITLE
can i pass extra-props inside virtual list item component ?

### ISSUE THREAD

**Issue by mamiaro** [tangbc/vue-virtual-scroll-list#271]
Hi, i have a question.. I cant find the way to pass data through extra props..
source and index works fine.. but if i try "props: ['extraProps']" inside component appears like "undefined".. any help ?

**Comment by tangbc** [comment]
```vue
<VirtualList style="height: 360px; overflow-y: auto;" // make list scrollable
  :data-key="'uid'"
  :data-sources="items"
  :data-component="item"
  :extra-props="{ otherProp, onItemClick: onClickDefineInRoot }"
></virtual-list>
```

**Comment by samuelbeaulieu** [comment]
Hi, I've been scratching my head for a while now, do you have an exemple on how to get the extra-props values in the component?

**Comment by creativalab** [comment]
Hi, can i use v-model on extra-props?

**Comment by ketewan** [comment]
Are there any secretes for using extra-props after?

Inside my data-component in mounted I write something like this:
`mounted() {
    console.log('in mounted', JSON.stringify(this.source), JSON.stringify(this.extraProps))
  },`

And I get correct data for source and undefined for extraProps. Why could it be like that?

**Comment by bloor** [comment]
I can confirm it's definitely a bug. 
![image](https://user-images.githubusercontent.com/1420653/207132221-9645a36d-238b-4f08-a2df-6eb1cd87cb30.png)

The extra-props is sent as empty/undefined.

**Comment by bloor** [comment]
> Are there any secretes for using extra-props after?
> 
> Inside my data-component in mounted I write something like this: `mounted() { console.log('in mounted', JSON.stringify(this.source), JSON.stringify(this.extraProps)) },`
> 
> And I get correct data for source and undefined for extraProps. Why could it be like that?

I failed to understand that either. but i debugged the code and found the proper way of usage:
You don't call `this.extraProps` you call `this.otherProp` and `this.onItemClick`  from the example above.
