### ISSUE TITLE
Two way scroll - Forward and reverse paging

### ISSUE THREAD

**Issue by jandieg** [tangbc/vue-virtual-scroll-list#272]
Hello, thanks for such great library.

I would like to know if it is possible to achieve fetching pages in 2 directions.

In other words, say user lands in **Page 2** and he could scroll either **UP** or **DOWN**, visually this would be the case:

![two-way-scroll](https://i.imgur.com/ZIUnTrk.png)

`* Gray color is virtual`

**Comment by tangbc** [comment]
Does prop `offset` or `start` help you?
