### ISSUE TITLE
Multiple data key

### ISSUE THREAD

**Issue by supertiger1234** [tangbc/vue-virtual-scroll-list#273]
I have array like this:
```
[
{tabName: "Owner", tempID: 123},
{username: "Supertiger", id: 1 }
]
```
I wanna use or statement `tempID || id` and decide which one to use. is there anyway?

**Comment by tangbc** [comment]
This is a very strange demand. I think you should think about whether your scene is wrong 😂.

**Comment by supertiger1234** [comment]
I liked the old version of vue virtual list better, it was more flexible.
