### ISSUE TITLE
Can you help me with how use data-key like function please

### ISSUE THREAD

**Issue by JuanDa90laq** [tangbc/vue-virtual-scroll-list#275]
I have the next implementation for virtual scroll list 

<virtual-list
               ref="scrollChat"
                :data-key="dataKey"
                :data-sources="chatObject"
                :data-component="itemComponent"
                :keeps="keeps"
                :estimate-size="estimateSize"
                :offset="offSet"
                @totop="nextPage"
                @tobottom="prevPage"
                @openComponent="openComponent"
                item-class="messages-list"
/>

My data-key is a function and is this the next:

dataKey(data){
 let key= data.Messages.map((item) => item.Messages.map(message => message.MessageId));
 return key
}

But is not working the component show a warning like 

Cannot get the data-key 'function () { [native code] }' from data-sources.

Can you help me please

**Comment by tangbc** [comment]
Refer to https://codesandbox.io/s/live-demo-virtual-list-forked-n8i1w?file=/src/App.vue
