### ISSUE TITLE
跳转指定位置有时候位置不正确

### ISSUE THREAD

**Issue by frzz** [tangbc/vue-virtual-scroll-list#276]
我在做一个很长的联系人列表，右侧有ABC...Z
用于定位。测试过程中，跳转到某个字母索引有时候位置不对，因为列表中的字母索引占了一定高度且动态出现。
导致跳转到某个索引会差几十个像素的高度，例如本来要调到B这个位置，差了一点。但是再次点击B跳转就可以精准跳转到B这个位置

**Comment by frzz** [comment]
代码以及效果图，先点击靠后的字母，再点击靠前的比较容易复现，或者多次上下滚动后
![code1](https://user-images.githubusercontent.com/19322467/94330141-1ce38f80-fff4-11ea-8fe6-4a08d9957946.png)
![code2](https://user-images.githubusercontent.com/19322467/94330142-20771680-fff4-11ea-9293-4f560db7c2c8.png)
![sim](https://user-images.githubusercontent.com/19322467/94330143-23720700-fff4-11ea-90a6-1d6168c40f6e.png)

**Comment by tangbc** [comment]
我看你这个列表的每一项都是固定高度对吧？按理说不应该出现这个问题的，我有时间看下；如果选项是动态高度这个问题是无法避免的。

**Comment by frzz** [comment]
> 我看你这个列表的每一项都是固定高度对吧？按理说不应该出现这个问题的，我有时间看下；如果选项是动态高度这个问题是无法避免的。

这个例子里面是固定，本来我是要做不固定的，但是我后来发现固定高度也会。

其实我的每个项算是半固定高度，例如每个高度都是60px，但是首次出现A/B/C..等就要高个30px。我觉得问题可能在getEstimateSize这里，按理说我的需求是可以实现的，因为什么时候首次出现字母是已知的。
 有没有什么办法我自己改一下源码可以适应这个需求？感谢！

**Comment by frzz** [comment]
我把用到getEstimateSize的方法改写了一下，hardcode了一个高度，貌似解决了，不知道会不会引起其他问题？
**function getIndexOffset**(givenIndex) {
        if (!givenIndex) {
          return 0;
        }

        var offset = 0;
        var indexSize = 0;

        for (var index = 0; index < givenIndex; index++) {
          // this.__getIndexOffsetCalls++
          indexSize = index % 500 == 0 ? 104 : 84;
          offset = offset + (typeof indexSize === 'number' ? indexSize : this.getEstimateSize(window.iindex));
        } // remember last calculate index


        this.lastCalcIndex = Math.max(this.lastCalcIndex, givenIndex - 1);
        this.lastCalcIndex = Math.min(this.lastCalcIndex, this.getLastIndex());
        // console.log(givenIndex,offset)
        return offset;
      } // is fixed size type

 **function getPadBehind()** {
        var end = this.range.end;
        var lastIndex = this.getLastIndex();

        if (this.isFixedType()) {
          return (lastIndex - end) * this.fixedSizeValue;
        } // if it's all calculated, return the exactly offset


        if (this.lastCalcIndex === lastIndex) {
          console.log((lastIndex - end) * this.getEstimateSize())
          return this.getIndexOffset(lastIndex) - this.getIndexOffset(end);
        } else {
          // if not, use a estimated value
          var arr = window.letterList,count = 0;//letterList,首次出现不同字母的index组成的数组,用来计算非常规高度
          for(let i = 0; i < arr.length; i++){
            if(arr[i].id>=end){
              count+=20//非常规高度为20
            }
          }
          return (lastIndex - end) * 84 + count;//padding-bottom高度
          // return (lastIndex - end) * this.getEstimateSize();
        }
      } // get the item estimate size

**Comment by tangbc** [comment]
这也太暴力了只能适用于你的这个场景。

**Comment by tangbc** [comment]
「半固定高度」其实就是不固定了，只要有一个不同的高度出现就是动态高度列表。
