### ISSUE TITLE
iOS键盘弹起之后滚动到底部没有触发range的变化

### ISSUE THREAD

**Issue by avennn** [tangbc/vue-virtual-scroll-list#278]
## Describe
iOS键盘弹起之后滚动到底部没有触发range的变化，导致最新的消息在有键盘的情况下没显示出来

## To Reproduce
iOS safari浏览器
聊天室的场景下，往上滚动多条历史消息，点击页面底部的输入框，键盘弹起后调用`this.$refs.vsl.scrollToOffset(this.$refs.vsl.getScrollSize())`滚动到底部，最新的消息没有显示出来。

问题出现在这段代码：
<img width="823" alt="WechatIMG28" src="https://user-images.githubusercontent.com/14135956/94262860-bc5a4100-ff66-11ea-9424-20ed093d3a8e.png">

把红框中的代码注释掉就行了，因为iOS上键盘弹起之后clientSize没有变化，导致`offset+clientSize>scrollSize+1`。请问能修复一下吗？

**Comment by tangbc** [comment]
红框的代码确实是有 bug 的，因为 iOS 滚动回弹的特性会导致方向判断错误进而导致 range 渲染错误，不过去掉也会有 bug 的，这里修改了很多次，有空再看下如何完全解决。
