### ISSUE TITLE
手机上快速滚动白屏

### ISSUE THREAD

**Issue by frzz** [tangbc/vue-virtual-scroll-list#280]
手机上快速滚动的时候，容易出现白屏，有没有改进方法？或者能不能代理滚动事件禁止快速滚动？

**Comment by tangbc** [comment]
无解，瞬间的白屏是虚拟列表无法避免的，机器性能越差越容易白屏，有些机器甚至全量渲染时滚动也会瞬间白屏。

**Comment by frzz** [comment]
> 无解，瞬间的白屏是虚拟列表无法避免的，机器性能越差越容易白屏，有些机器甚至全量渲染时滚动也会瞬间白屏。

我在看另一个插件iscroll的 infinite—scroll不会白屏，好像不能快速滚动，可能是处理了滚动事件。不过那个插件好像只能用于固定高度的项目。
