### ISSUE TITLE
如果需要知道用户点击了哪一项，有没有什么方法可以实现？

### ISSUE THREAD

**Issue by Fanyeyuan** [tangbc/vue-virtual-scroll-list#284]
我有一个需求是这样的，我滚动的内容是一个导航栏，我希望再用户点击了某一个行内容的时候，反馈一个事件给父组件，然后进行相应的界面切换，但是我并没有看到这一块的api，是否有什么方法可以实现呢？

**Comment by tangbc** [comment]
发事件，比如：
https://github.com/tangbc/vue-virtual-scroll-list/blob/b9fa42896a2f438e1e59c210d525b36c0f63cb08/example/src/views/keep-state/Item.vue#L32
