### ISSUE TITLE
为什么虚拟滚动到底部，加载数据后，会出现整个虚拟滚动往上跳动呢？

### ISSUE THREAD

**Issue by LLLLLamHo** [tangbc/vue-virtual-scroll-list#285]
## Describe
滚动到底部后触发tobottom，然后加载数据，数据加载后，会出现虚拟滚动区域跳动到其他地方，非第一屏的底部位置

## Other
 - Version 2.3.1
 - Browser phone（chrome, safari）

**Comment by tangbc** [comment]
来个 demo 吧，不然不好查

**Comment by LLLLLamHo** [comment]
https://tangbc.github.io/vue-virtual-scroll-list/#/infinite-loading
你自己的官网demo在手机上，例如iphone里面用微信或者safari打开，就会看到在多滚动几个屏幕后，就会出现白屏的情况了

**Comment by azhengyongqin** [comment]
> 来个 demo 吧，不然不好查

就是项目Readme里面那个实例都是整个bug

**Comment by azhengyongqin** [comment]
@tangbc 
就是项目Readme里面那个实例，运行就是这个bug

**Comment by tangbc** [comment]
#278 原因大概是这个，iOS 会回弹，导致方向判断错误，暂时还没有想到两全的解决办法，后面有时间在看了。

**Comment by TinaSprunt** [comment]
> #278 原因大概是这个，iOS 会回弹，导致方向判断错误，暂时还没有想到两全的解决办法，后面有时间在看了。

@tangbc web端谷歌浏览器也出现这个问题，比如单页100条，触底获取下一页数据。
几百条的没问题，几千条就会发生滚动条位置乱跳的情况（获取完数据后，滚动条位置不在上次的位置，直接跳回顶部），请问现在这个问题有什么进展吗？或者解决思路

**Comment by TinaSprunt** [comment]
@tangbc web端谷歌浏览器也出现这个问题，比如单页100条，触底获取下一页数据。
几百条的没问题，几千条就会发生滚动条位置乱跳的情况（获取完数据后，滚动条位置不在上次的位置，直接跳回顶部），请问现在这个问题有什么进展吗？或者解决思路

示例：每次在获取数据后，都调用this.$refs.virtualListRef.getOffset()获取当前偏移量，但有时候获取不到真实的偏移量，会拿到0

**获取数据后，打印当前 getOffset 及 getScrollSize的值**
![5](https://github.com/tangbc/vue-virtual-scroll-list/assets/38268966/09fcaaa6-e970-4c8a-8290-f710fa3893a3)

**实际元素高度**
![6](https://github.com/tangbc/vue-virtual-scroll-list/assets/38268966/5f53d429-a009-4e8c-a146-a5c384727c1b)
