### ISSUE TITLE
滚动展示的内容是否支持使用slot

### ISSUE THREAD

**Issue by yqh708** [tangbc/vue-virtual-scroll-list#287]
在virual-list标签内，滚动的内容是否支持使用slot插槽。使用 :data-component="item"功能太受限了。

**Comment by tangbc** [comment]
#237 肯定有其他的绕道解法，只是不用 slot 确实不太像 Vue 的风格，其实更像 React 的风格。

**Comment by yuanjianhua** [comment]
> #237 肯定有其他的绕道解法，只是不用 slot 确实不太像 Vue 的风格，其实更像 React 的风格。

怎么可以使component组件里面的支持slot的呢

**Comment by yuanjianhua** [comment]
@tangbc
