### ISSUE TITLE
Grid Layout

### ISSUE THREAD

**Issue by MentalGear** [tangbc/vue-virtual-scroll-list#289]
Hey there, Is a grid layout (vertical scroll) like this also possible with this lib ?

<img width="367" alt="Screenshot 2020-11-25 at 19 11 54" src="https://user-images.githubusercontent.com/2837147/100387165-b399f000-3027-11eb-81d6-e3f940ea6324.png">

**Comment by tangbc** [comment]
Not support yet.

**Comment by seeratawan01** [comment]
Work Around: https://github.com/seeratawan01/Virtual-Scroll-Playground
