### ISSUE TITLE
IE11 Issue

### ISSUE THREAD

**Issue by roboriaan** [tangbc/vue-virtual-scroll-list#29]
Unable to get example to run in IE11.

Running example :
https://tangbc.github.io/vue-virtual-scroll-list/examples/finite/

in Internet Explorer 11 produces :

`SCRIPT1003: Expected ':'`

Typical IE error. Means nothing. Can't give more info sorry.

**Comment by tangbc** [comment]
Maybe babel plugin compile failed.

**Comment by tangbc** [comment]
Babel compie fail to es5 if less a `.babelrc` file in project. 

This problem may caused by:
```javascript
data () {}
```
```javascript
data: function data () {}
```
