### ISSUE TITLE
Jumps in scrolling

### ISSUE THREAD

**Issue by chgold** [tangbc/vue-virtual-scroll-list#291]
When i scroll the library with the mouse, then the scroll sometimes jumps and scrolls a larger number of rows in the list. (It jumps both scrolling up and scrolling down, at certain points in the list, even though there is nothing special about these items in the list).
The problem was with version 1, and now I have upgraded to the latest version (2.3.2) and the problem still exists.
Has anyone encountered such a problem and can direct me to a solution?
Thanks.

**Comment by chgold** [comment]
This is the link to the problem
https://www.karyera.org.il/jobs.php

**Comment by TudorPetrariu** [comment]
Same issue here, everything works well but it seems to jump sometimes when scrolling. Any ideas ?

**Comment by chgold** [comment]
I upgraded a version. In the new version it's fine.

**Comment by TudorPetrariu** [comment]
Can you please tell which version are you using ? And there were no need to change anything after the update ?
    <virtual-list
          ref="scroller"
          style="scroll-behavior: smooth;"
          class="scroller"
          :data-key="'stop_id'"
          :data-sources="stops"
          :data-component="itemComponent"
          :estimate-size="146"
          page-mode
          :keeps="40"
          @loaded="onCardLoaded"
          @updated="scrollToStop"
        />

This would be my setup

**Comment by chgold** [comment]
Also 2.3.2
Now I checked again, there are still jumps
(From my previous review, it also depends on what screen width it is).
Bug in the library.

**Comment by loaded** [comment]
please don't say @loaded . it wake me up

**Comment by TudorPetrariu** [comment]
Can you please elaborate Adnan  ?

**Comment by TudorPetrariu** [comment]
I have found a workaround. For some reason adding margins between items makes the list jump while scrolling, not sure if because the list is dynamically created so it self computes the alignments ?

I am looking still for further explanations.

Anyway, my fix was to remove the margins between items and add a break element(Now I have space between items and no jumping around.

**Comment by chgold** [comment]
I did not understand what caused and how you corrected. If you can upload a picture

**Comment by TudorPetrariu** [comment]
I still don't completely understand what causes this effect.
I am using Nuxt and Tailwind.

My List Component  

  <virtual-list
          ref="scroller"
          class="scroller"
          :data-key="'stop_id'"
          :data-sources="stops"
          :data-component="itemComponent"
          :estimate-size="146"
          page-mode
          :keeps="40"
          @loaded="onCardLoaded"
          @updated="scrollToStop"
        />

My Single Item Component(itemComponent)- a part of it but enough to get the point ?

  **FROM**

 <div :id="`stop_${source.stop_id}`" class="card mb-8" > /// mb-8 was causing the issue for me
      <div class="card_body">
        <div class="card_row">
          <div class="flex flex-wrap w-3/4">
            <div class="card_row_item-px flex-initial">
              <div
                :class="[
                  'btn btn-icon btn-secondary p-3',
                  { ['btn-secondary-outline bg-transparent']: summaryOptionState },
                ]"
                @click="summaryOption"
              >
                <div v-html="require('~/assets/svg/icon-driver/icon_32x32-option.svg')"></div>
              </div>
            </div>
</div>

**TO**

<div> // Added another Div element to wrap my single item
   <br />  //And a break element to keep the items spaced between
<div :id="`stop_${source.stop_id}`" class="card" > // Removed the margin-bottom
      <div class="card_body">
        <div class="card_row">
          <div class="flex flex-wrap w-3/4">
            <div class="card_row_item-px flex-initial">
              <div
                :class="[
                  'btn btn-icon btn-secondary p-3',
                  { ['btn-secondary-outline bg-transparent']: summaryOptionState },
                ]"
                @click="summaryOption"
              >
                <div v-html="require('~/assets/svg/icon-driver/icon_32x32-option.svg')"></div>
              </div>
            </div>
        </div>
 </div>

I have never posted like this but I hope it helps.

**Comment by TudorPetrariu** [comment]
I still don't completely understand what causes this effect.
I am using Nuxt and Tailwind.

My List Component  

  <virtual-list
          ref="scroller"
          class="scroller"
          :data-key="'stop_id'"
          :data-sources="stops"
          :data-component="itemComponent"
          :estimate-size="146"
          page-mode
          :keeps="40"
          @loaded="onCardLoaded"
          @updated="scrollToStop"
        />

My Single Item Component(itemComponent)- a part of it but enough to get the point ?

  **FROM**

 <div :id="`stop_${source.stop_id}`" class="card mb-8" > /// mb-8 was causing the issue for me
      <div class="card_body">
        <div class="card_row">
          <div class="flex flex-wrap w-3/4">
            <div class="card_row_item-px flex-initial">
              <div
                :class="[
                  'btn btn-icon btn-secondary p-3',
                  { ['btn-secondary-outline bg-transparent']: summaryOptionState },
                ]"
                @click="summaryOption"
              >
                <div v-html="require('~/assets/svg/icon-driver/icon_32x32-option.svg')"></div>
              </div>
            </div>
</div>

**TO**

<div> // Added another Div element to wrap my single item
   <br />  //And a break element to keep the items spaced between
<div :id="`stop_${source.stop_id}`" class="card" > // Removed the margin-bottom
      <div class="card_body">
        <div class="card_row">
          <div class="flex flex-wrap w-3/4">
            <div class="card_row_item-px flex-initial">
              <div
                :class="[
                  'btn btn-icon btn-secondary p-3',
                  { ['btn-secondary-outline bg-transparent']: summaryOptionState },
                ]"
                @click="summaryOption"
              >
                <div v-html="require('~/assets/svg/icon-driver/icon_32x32-option.svg')"></div>
              </div>
            </div>
        </div>
 </div>

I have never posted like this but I hope it helps.

**Comment by TudorPetrariu** [comment]
> I did not understand what caused and how you corrected. If you can upload a picture

I still don't completely understand what causes this effect.
I am using Nuxt and Tailwind.

My List Component  

  <virtual-list
          ref="scroller"
          class="scroller"
          :data-key="'stop_id'"
          :data-sources="stops"
          :data-component="itemComponent"
          :estimate-size="146"
          page-mode
          :keeps="40"
          @loaded="onCardLoaded"
          @updated="scrollToStop"
        />

My Single Item Component(itemComponent)- a part of it but enough to get the point ?

  **FROM**

 <div :id="`stop_${source.stop_id}`" class="card mb-8" > /// mb-8 was causing the issue for me
      <div class="card_body">
        <div class="card_row">
          <div class="flex flex-wrap w-3/4">
            <div class="card_row_item-px flex-initial">
              <div
                :class="[
                  'btn btn-icon btn-secondary p-3',
                  { ['btn-secondary-outline bg-transparent']: summaryOptionState },
                ]"
                @click="summaryOption"
              >
                <div v-html="require('~/assets/svg/icon-driver/icon_32x32-option.svg')"></div>
              </div>
            </div>
</div>

**TO**


<div> // Added another Div element to wrap my single item
   <br />  //And a break element to keep the items spaced between
<div :id="`stop_${source.stop_id}`" class="card" > // Removed the margin-bottom
      <div class="card_body">
        <div class="card_row">
          <div class="flex flex-wrap w-3/4">
            <div class="card_row_item-px flex-initial">
              <div
                :class="[
                  'btn btn-icon btn-secondary p-3',
                  { ['btn-secondary-outline bg-transparent']: summaryOptionState },
                ]"
                @click="summaryOption"
              >
                <div v-html="require('~/assets/svg/icon-driver/icon_32x32-option.svg')"></div>
              </div>
            </div>
        </div>
 </div>

I have never posted like this but I hope it helps.

**Comment by TudorPetrariu** [comment]
> I did not understand what caused and how you corrected. If you can upload a picture

I still don't completely understand what causes this effect.
I am using Nuxt and Tailwind.

My List Component  

  <virtual-list
          ref="scroller"
          class="scroller"
          :data-key="'stop_id'"
          :data-sources="stops"
          :data-component="itemComponent"
          :estimate-size="146"
          page-mode
          :keeps="40"
          @loaded="onCardLoaded"
          @updated="scrollToStop"
        />

My Single Item Component(itemComponent)- a part of it but enough to get the point ?

  **FROM**

 <div :id="`stop_${source.stop_id}`" class="card mb-8" > /// mb-8 was causing the issue for me
      <div class="card_body">
        <div class="card_row">
          <div class="flex flex-wrap w-3/4">
            <div class="card_row_item-px flex-initial">
              <div
                :class="[
                  'btn btn-icon btn-secondary p-3',
                  { ['btn-secondary-outline bg-transparent']: summaryOptionState },
                ]"
                @click="summaryOption"
              >
                <div v-html="require('~/assets/svg/icon-driver/icon_32x32-option.svg')"></div>
              </div>
            </div>
</div>

**TO**


```
<div> // Added another Div element to wrap my single item
   <br />  //And a break element to keep the items spaced between
<div :id="`stop_${source.stop_id}`" class="card" > // Removed the margin-bottom
      <div class="card_body">
        <div class="card_row">
          <div class="flex flex-wrap w-3/4">
            <div class="card_row_item-px flex-initial">
              <div
                :class="[
                  'btn btn-icon btn-secondary p-3',
                  { ['btn-secondary-outline bg-transparent']: summaryOptionState },
                ]"
                @click="summaryOption"
              >
                <div v-html="require('~/assets/svg/icon-driver/icon_32x32-option.svg')"></div>
              </div>
            </div>
        </div>
 </div>
```

I have never posted like this but I hope it helps.

**Comment by chenlevy** [comment]
I'm using version 1.3.9 and the UI is jumping when scrolling sometimes, especially when the item size is large (sometimes larger than the screen height). I see some change in the padding when the jump occurs. Adding here a screenshot from Chrome devtools of before/after the jump occurs.

Did someone encounter this problem and know how to handle it?
I don't see any redundant margins

![jumps scrolling](https://user-images.githubusercontent.com/733719/106114546-579f3500-6158-11eb-80ba-c11adbc3ea77.png)

**Comment by remixer-dec** [comment]
I faced the same issue and found a solution. The reason of jumping was inaccurate position calculation, not including margins of the root data-component and images with dynamic heights. To solve this, I set display:flex for the item wrapper element (set as :item-class) and set the height of all images to a fixed constant value.

**Comment by AdRSTiN** [comment]
I was having similar issue and got it solved by adding **'scroll-behavior: smooth'** to the **style** param like so:

<virtual-list
...
**style="scroll-behavior: smooth;"**
...
/>
