### ISSUE TITLE
The content inside the virtual scroll is flickering

### ISSUE THREAD

**Issue by invisor** [tangbc/vue-virtual-scroll-list#294]
The problem is in flickering content inside the virtual scroll (VS)
I have complicated items for VS. Each item is a page that contains about 20 stones. So in VS I keeping only 3 pages at once. When I'm on a border between two pages the VS starts unmounting invisible pages and mounting new ones. At this moment I experiencing content flickering. This is not good. This happens b/c you mounting/unmounting pages in the viewport as well. I think the solution is to stop mounting/unmounting visible items in the viewport and start changing items order in DOM. Unmount only items outside of the viewport.
I've recorded a video for you. I've added mounted/destroy events for each item (page), thus you may see events in the console. As you can see there are a lot of mounts/unmounts for all items, even for visible in the viewport

https://www.loom.com/share/562713a8e15240f78e9f5e34e265c542

**Comment by tangbc** [comment]
You can see this line: 
https://github.com/tangbc/vue-virtual-scroll-list/blob/2ef187e4607b0be615db6ad0385ff4a6666b5c1f/src/index.js#L269

Flickering may due to each item has many images but they don't have `key` prop, try set an unique `key` with each image?

**Comment by invisor** [comment]
No, this is refreshing `pageComponent`. And as result, all images refreshing as well. Each page has about 20 ring items with images. All these items have unique GUID. Each page component has a unique GUID as well. Here is how my listing component looks, it seems all props should be fine:

![Screenshot 2020-12-22 at 11 55 42](https://user-images.githubusercontent.com/10770118/102869451-ab797880-444c-11eb-9656-8f4cc89570f8.png)

I've started keeping 5 items (5 pages). When I scrolling down and pages adding one by one everything seems fine until I reach the 6th page. If I understand right at this point the 1st page should be destroyed and only the 6th page should be added. But all pages start destroying and mounting again. I've added an output to the console `mounted` and `beforeDestroy` hooks. All page's GUID is static and not changing during time. Please see the video below

https://www.loom.com/share/777d9aa7330e43eea57241a9c9771872

**Comment by invisor** [comment]
I even removed all items from the pages. But the pages remounting anyway

https://www.loom.com/share/63c38603642744da84d91f64829a1982

**Comment by invisor** [comment]
@tangbc any progress here?

**Comment by me-majidi** [comment]
I'm facing the same issue. All item components are being created and destroyed repeatedly, even those inside the viewport.

**Comment by tangbc** [comment]
#310

**Comment by herbert-hbt** [comment]
I'm facing the same issue too,  the reason is that those components (have been rendered already) are not reused because the lack of 'key' (diff calculation will revolves),  just put a key prop will work. 

<img width="947" alt="WeChat532b6361e46f22b064367d0f1f7ad111" src="https://user-images.githubusercontent.com/55829086/117393655-2daf9880-af27-11eb-8539-1c396d927a08.png">
