### ISSUE TITLE
Is it possible to pass an emit event through this component?

### ISSUE THREAD

**Issue by RizaHKhan** [tangbc/vue-virtual-scroll-list#296]
Trying to communicate between the component inside `vue-virtual-scroll-list` and its parent (diagram for clarity).

1. parent
2. vue-virtual-scroll-list
3. child

The child wants to talk to the parent via an `emit`. Is that possible to listen for an event on (#2) virtual-scroll-list. 

<VirtualList @randomEvent="dosomething"></VirtualList>

My understanding is that these following methods are native to virtual scroll list:

![image](https://user-images.githubusercontent.com/51720003/103024271-856fd900-451d-11eb-98ff-827bf2c4efa9.png)

Thank you!

**Comment by invisor** [comment]
@RizaHKhan you can do something like event using `item-scoped-slots`

**Comment by Dagdelo** [comment]
You can use [dispatch ](https://github.com/tangbc/vue-virtual-scroll-list/blob/b9fa42896a2f438e1e59c210d525b36c0f63cb08/example/src/mixins/index.js)to back-propagate the event to the desired component.
