### ISSUE TITLE
Dynamic content loading.

### ISSUE THREAD

**Issue by milochristiansen** [tangbc/vue-virtual-scroll-list#30]
Looking at your documentation, there does not seem to be any way to support dynamically loaded content, where the total number of items is know at the start, but the actual information needs to be loaded just before it is shown.

Bascially I have an array of IDs, and just before the item is shown I need to load the actual information from the DB.

Basically I need the list to call a function every time it needs new data. Is there a way to supply a per-element rendering callback or some such? (For example: [the way this library does it](https://github.com/tbranyen/hyperlist))

**Comment by tangbc** [comment]
> just before the item is shown I need to load the actual information from the DB.

You can get the actual render index zone data `start` and `end` via `onscroll ` props, see [here](https://github.com/tangbc/vue-virtual-scroll-list/releases/tag/v1.1.7). 

And the init zone you can calculate from the value of `bench` and `remain` props.

Here we cannot trigger every item when they are going to be rendered.
