### ISSUE TITLE
求助，滚动时闪烁+跳跃

### ISSUE THREAD

**Issue by wjzhang-ty** [tangbc/vue-virtual-scroll-list#301]
## Describe
列表在滚动时会有跳跃和闪烁现象，我尝试修改了keeps和estimate-size但是依旧没有效果，详见下方视频。目前没有头绪，希望可以得到一些帮助，十分感谢！

## Reproduce demo
https://www.bilibili.com/video/BV1FX4y1N7HR/

**Comment by XavierShi** [comment]
顶一下 今天也出现了这个问题

**Comment by XavierShi** [comment]
@wjzhang-ty 你看一下你的渲染item组件，是不是有加margin值。我把我渲染组件的margin上下的值换成padding就没有出现跳跃和闪烁现象

**Comment by wjzhang-ty** [comment]
> @wjzhang-ty 你看一下你的渲染item组件，是不是有加margin值。我把我渲染组件的margin上下的值换成padding就没有出现跳跃和闪烁现象

谢谢老哥，是有效的 非常感谢！~   *★,°*:.☆(￣▽￣)/$:*.°★* 。

**Comment by wjzhang-ty** [comment]
The “margin” in the <itemComponent> will cause screen skipping，try to use "padding" "border"
