### ISSUE TITLE
getSize img size

### ISSUE THREAD

**Issue by kjk515** [tangbc/vue-virtual-scroll-list#305]
I am trying to put a component that contains a img tag in the data-component.
When I call 'this.$refs.vsl.getSize()', components containing img tags do not have the exact image height.
Is there a way to get the exact image height?

**Comment by tangbc** [comment]
Under normal circumstances, you should not make the size of the picture dynamic, it should be fixed size before loaded, otherwise, no one knows how much it will stretch before the loading is completed.
