### ISSUE TITLE
是否有一行多个元素的无限加载DEMO

### ISSUE THREAD

**Issue by yudan215** [tangbc/vue-virtual-scroll-list#307]
例如一个图片库·一行有4个·可动态添加删除，这样如何使用vue-virtual-scroll-list？是否有相关DEMO

**Comment by tangbc** [comment]
把 4 个图片 UI 实现放到一个 item 里面去就行了，总之一行就是一个 item component，数据结构可以用二维数组，第一层渲染虚拟列表，第二层在 item 里面分 4 个图片布局。
