### ISSUE TITLE
visible elements

### ISSUE THREAD

**Issue by Nexvelius** [tangbc/vue-virtual-scroll-list#31]
Hi!

I'm using your library and I like it very much, but 
don't know how to get the list of visible elements.

I have a page with a large number of virtual lists.

Have tried to use some ready libraries. They are bind to the scrolling of the main window and do not work with the virtual list.

The libraries I have seen do not offer the possibility to call the function compulsory visibility calculation (maybe I did not see), otherwise I would have tried it in the event onscroll.

Do you have any ideas?
I hope your answer, thank you.

**Comment by tangbc** [comment]
I think this case is a little strange and unclear, because it's difficult to define whether list item is shown or hidden, for example if an item is scrolled over in 50% or 99% at the edge of top we should judge it shown or hidden ?

**Comment by Nexvelius** [comment]
If a list item is a little bit falls within an area of visibility, it is considered visible. 

In advance excuse me for my English. It's not my native language.

Here's an example of how this is done here:
https://github.com/BKWLD/vue-in-viewport-mixin

I would like something similar for elements of the virtual list.

Why do I need it?
I have a tree list of the servers, server groups, and contact groups. For the contact groups I use your library. Each contact has a status (online/offline/etc). Contacts can be very large (1000-10000+). Receiving the status for all users can be resource intensive and I would like to streamline the process only for vidimykh contacts.

**Comment by Nexvelius** [comment]
I found a way to implement this, but I'm not sure this is a good way.

Pass in the element data scroll through the properties. Using the $watch we expect a visibility state.

```javascript
scroll_data(value, old_value) {
    let view_size = 728;
    let view_top = value.offset;
    let view_end = value.offset + view_size;
    let item = this.$el.offsetTop;

    if (item > view_top && item < view_end) {
        if (this.isVisible === false) {
            this.$set(this, 'isVisible', true);
        }
    } else {
        this.$set(this, 'isVisible', false);
    }
}
```

At this stage, it solves my need.
Thank you.
