### ISSUE TITLE
滑动vue-virtual-scroll-list白色没有文字区域没法滑动

### ISSUE THREAD

**Issue by LongLongLongLongLongLongLongLongLong** [tangbc/vue-virtual-scroll-list#315]
滑动vue-virtual-scroll-list白色没有文字区域没法滑动，如果滑动被文字填充的区域则可以滑动，请问问题原因是什么，怎么解决

**Comment by tangbc** [comment]
可以具体点吗，一句话判断不出来。

**Comment by LongLongLongLongLongLongLongLongLong** [comment]
就是在vue-virtual-scroll-list中添加了一些控件，比如编辑框，lable等，有的控件中填充了文字，滑动的时候点击有文字的地方可以滑动，没有文字的地方滑动不了，会一直卡着，很难滑动
