### ISSUE TITLE
超过最大值分层 这是怎么回事啊。大佬，求帮助，这个高度estimate-size 支持rem吗

### ISSUE THREAD

**Issue by hongdundada** [tangbc/vue-virtual-scroll-list#316]
![image](https://user-images.githu
[十分简单的代码.zip](https://github.com/tangbc/vue-virtual-scroll-list/files/6215703/default.zip)
busercontent.com/61041443/112721991-f4583600-8f41-11eb-8b83-1015cf7a47a0.png)

**Comment by tangbc** [comment]
不支持 `rem` 因为需要 JS 运算
