### ISSUE TITLE
Problem with flex design

### ISSUE THREAD

**Issue by daiyanze** [tangbc/vue-virtual-scroll-list#32]
Just saw that the wrapper div and root div bind with style (display: block). I think it would be better if we use classes instead of style for those who wants to make alignments in box style.

**Comment by tangbc** [comment]
Does `!important` works ?

**Comment by daiyanze** [comment]
Yes. It works. Mine is only a suggestion, though...

**Comment by daiyanze** [comment]
Thanks for your support.
