### ISSUE TITLE
Why is data-key needed?

### ISSUE THREAD

**Issue by patchthecode** [tangbc/vue-virtual-scroll-list#326]
Thanks for this library. It is well done.

I have a question on design.
Why is the data-key needed? 

you said this
> it is used for identifying item size.

I was just wondering if this was the only reason. It is a little difficult i think that the data needs to always have this when it is unnecessary (from the data's end).

Is there a way to assign some default ID for data that does not have force someone to change to data in order to use the library?

I am thinking that it might be better if there was an option if the component asked for the key on each iteration. This was, I can provide some arbituary ID instead of modufying the data.  What are your thoughts?

**Comment by tangbc** [comment]
Its ok without `data-key` if item size is fixed size, otherwise if dynamic size list it need identify each item size.
