### ISSUE TITLE
[suggestion] Sorting ?

### ISSUE THREAD

**Issue by arnoldtkl** [tangbc/vue-virtual-scroll-list#33]
Thanks for your great work! Is it possible add sorting function to the item at infinite data? By default, need set a max value for the item then sort it.

**Comment by tangbc** [comment]
I'm sorry I don't quite understand what you mean `sorting function` ? 

There is no relationship between this component and what order data list. If you want to sort list, just handle with the list data only. The component just render list base list slots, doesn't care about their order or any.

**Comment by arnoldtkl** [comment]
Ok, I think is me, not fully understand how the component works. 👏
