### ISSUE TITLE
How to add keyup or keydown events to the virtual scroller? Programmatically or on template?

### ISSUE THREAD

**Issue by slidenerd** [tangbc/vue-virtual-scroll-list#349]
- I apologize for this question, it is already referenced in
-  #89  
- #152 
- #329 
- but none of the issues show how and where they are adding this
- I tried adding @keydown to the virtual list but the event is not fired
```

  <virtual-list
    :style="style"
    scrollable
    :data-key="'uid'"
    :data-sources="items"
    :data-component="itemComponent"
    :footer-class="'loader-wrapper'"
    v-on:tobottom="onScrollToBottom"
    @keydown='onKeyDown'
  >
    <div slot="footer" class="loader"></div>
  </virtual-list>
```

I basically want to use the arrow keys to scroll up and down instead of the scrollbar. How do I achieve this with the virtual scroll list?

**Comment by dancingbannana** [comment]
did you ever figure this out?
