### ISSUE TITLE
[help] can you give me an example about onscroll function?

### ISSUE THREAD

**Issue by arnoldtkl** [tangbc/vue-virtual-scroll-list#35]
Can I use the onscroll function to get the users scrolling index? I thinking to bookmark the row index, so the user can starts where they left. In my case, the user may scroll the virtual scroll list until a certain row of data, then the user will navigate to another page when the user returns back to the virtual scroll list page, the data will start from index 0 again. Can you guide me how to make a bookmark about this?

**Comment by tangbc** [comment]
You can store the scroll offset as `userScrollOffset` in `onscroll` prop (function), params detail is [here](https://github.com/tangbc/vue-virtual-scroll-list/releases/tag/v1.1.7). 

If user navigate to another page and user returns back, you can set the `virtual-scroll-list` prop `offset`as `userScrollOffset` stored from above.

**Comment by arnoldtkl** [comment]
Sorry about this, I still cannot get it. So, initially, I have to define that 4 params on my data vue ?

**Comment by arnoldtkl** [comment]
Thanks, I already get it.
