### ISSUE TITLE
How to handle events emited by the Item Component?

### ISSUE THREAD

**Issue by AllanOricil** [tangbc/vue-virtual-scroll-list#354]
I did not understand how the parent component will handle events from the Item component. Is it not possible? Why didn't you use a slot and scoped slots for it?

**Comment by Szymon-dziewonski** [comment]
Im also wondering, unfortunately because of that I wont use this lib :( Passing component via prop is just wrong

**Comment by pluxain** [comment]
I think this is possible now with Slot API. see #237

**Comment by axetroy** [comment]
Before the implementation of the new API, is there a solution currently?
