### ISSUE TITLE
动态添加聊天数据问题

### ISSUE THREAD

**Issue by lanmeizi** [tangbc/vue-virtual-scroll-list#357]
发送第一条聊天数据显示空白，再发送第二条聊天数据，两条数据又一起正常显示出来了。这是为啥呢
<virtual-list
        ref="virtualListComp"
        class="list-dynamic beautiful-scorll-bar"
        :data-key="'_id'"
        :data-sources="chatDatas"
        :data-component="itemComponent"
        :estimate-size="80"
        :keeps="30"
        :extra-props="{
          imagePreview: imagePreview,
          userId: userId
        }"
      />
点击发送时，给chatDatas数组push数据

**Comment by howyhuang** [comment]
有搞定吗，我也是有空白

**Comment by lanmeizi** [comment]
> 有搞定吗，我也有空闲

没有呢

**Comment by Evanzew** [comment]
> 发送第一条聊天数据显示空白，再发送第二条聊天数据，两条数据又一起正常显示出来了。这是为啥呢 点击发送时，给chatDatas数组push数据

我也有这个问题，添加keeps的值就解决了。
