### ISSUE TITLE
bugs in variable height mode

### ISSUE THREAD

**Issue by johnwaynerui** [tangbc/vue-virtual-scroll-list#36]
As i see from your guide, in variable height mode for this component, we need to pass prop **variable** as a function (or boolean) to it, but for your example, you just know all the item's height before you render it(or before they get inserted into DOM tree), so you can get right calculation. But in most cases, we don't know how height the item is before it was inserted into DOM tree, then how could i get that height and return it from function **variable** as what you did  [here](https://github.com/tangbc/vue-virtual-scroll-list/blob/master/examples/variable/variable.vue) Actually i tried  as follows:
```
getVariableHeight (index) {
                var instance = null;
                var dom = null;
                var height = 0;
                if (instance = this.$refs.vsl.$slots.default[index].componentInstance) {
                    dom = instance.$el;
                    height = dom.getBoundingClientRect().height;
                }
                return height;
            }
```
The above ```getVariableHeight```function also comes from above link, but i rewrote it to meet my scenario. But it does not work. Can you please tell me what is the best practice in my situation?

**Comment by tangbc** [comment]
The method `element.getBoundingClientRect` cannot get height (or other properties) if the element is not exist in real document. In this component scroll behavior we need know all the items each height so that can calculate all the padding (scroll position) exactly.

**Comment by johnwaynerui** [comment]
But in most common cases, we just load data asynchronously and build DOM from it.We don't know the exact height for those DOMS before they were inserted in to DOM tree, then how can i just pass height to variable item like what you did in your example? I am not sure if you know what i mean. But if you do, you just tell me can this component handle the situation that was described above.

**Comment by johnwaynerui** [comment]
Seems i found a solution to solve my problem.At first, i need to pass a predefined fixed height to component item(or return a fixed num,eg:200 in getVariableHeight) ,code like below:
```
getVariableHeight (index) {
                var instance = null;
                var dom = null;
                var height = 0;
                if (this.$refs.vsl && this.$refs.vsl.$slots && (instance = this.$refs.vsl.$slots.default[index].componentInstance)) {
                    dom = instance.$el;
                    height = dom.getBoundingClientRect().height;
                    return height;
                }
                else {
                    return 200;
                }
            }
```
then when component gets updated(or scroll handler was called), i call ```updateVariable``` method on the component instance manually to update every item's height with their real height which was calculated from above ```getVariableHeight```  That is all what i came out to satisfy need in my scenario. So am i in right place or missing something? Hope you can point it out. thank you!

**Comment by tangbc** [comment]
It looks like a good idea！

That is similar to `varAverSize` in source delta [here](https://github.com/tangbc/vue-virtual-scroll-list/blob/master/index.js#L67): give a estimate height before real calculate.

**Comment by johnwaynerui** [comment]
I read your source code for this component, there are some confusions for some specific codes.Here are some my views:

- As for ```VUE``` recommendation, it would be better to emit ```event``` from child component to send result to parent.And in your code, you pass function as prop to child, it works, but not ```VUE``` style.

- [Here](https://github.com/tangbc/vue-virtual-scroll-list/blob/master/index.js#L239) you pass ```delta.total```to ```getVarOffset```, which caused that we got out-range index [here](https://github.com/tangbc/vue-virtual-scroll-list/blob/master/examples/variable/variable.vue#L63),where we would expect ```0 ~ delta.total - 1```(I notice that in your example [here](https://github.com/tangbc/vue-virtual-scroll-list/blob/master/examples/variable/variable.vue#L65), you solved this problem with special conditional ```target && targte[index]``` statement, but it seems a tricky. Actually this can be solved in source code level)

- Guess you can just return ```0``` [here](https://github.com/tangbc/vue-virtual-scroll-list/blob/master/index.js#L239). And [here](https://github.com/tangbc/vue-virtual-scroll-list/blob/master/index.js#L241), i think it would be more reasonable with ```return this.getVarOffset(delta.end) + (delta.total - delta.end) * (delta.varAverSize || this.size)``` than ```return this.getVarOffset(delta.start) + (delta.total - delta.end) * (delta.varAverSize || this.size)```

Anyway, above are just my suggestions(maybe some of them are a mistake), and you really made an awesome, elegant lib for us ,hope it will be better, thank you!

**Comment by tangbc** [comment]
Thank your advise, I will check it !

**Comment by tangbc** [comment]
For props or event can see this [discussion](https://forum.vuejs.org/t/events-vs-callback-props/11451/2) it just semantics different, maybe I wrote React leads for it :)

The method `getVarOffset(index)` will not reach the index in [for-loop](https://github.com/tangbc/vue-virtual-scroll-list/blob/master/index.js#L179) that use to get all offsets **before** index, not include, I wrote `target && targte[index]` just habitual ^^
