### ISSUE TITLE
What to do with :data-component prop when using item slot API?

### ISSUE THREAD

**Issue by adriaan** [tangbc/vue-virtual-scroll-list#364]
I'm using the item slot API introduced in https://github.com/tangbc/vue-virtual-scroll-list/pull/337
However, `VirtualList` has a required prop `:data-component`.
As I'm defining my list component in the slot, I don't know what to do with the `:data-component` prop. 
Omitting it works but leads to a validation error, and it doesn't accept `null`.
Any suggestions?

**Comment by adriaan** [comment]
I ended up just passing in an empty object. Not very elegant, but hey. 
I'll try and get a PR up to add better support for the slot API.

**Comment by fanckush** [comment]
@adriaan can you provide a snippet on how you used the slot api?
