### ISSUE TITLE
图片重复请求问题

### ISSUE THREAD

**Issue by dzyook** [tangbc/vue-virtual-scroll-list#377]
即使设置了较大的keeps，每次改变datasources的时候都会触发所有的图片重新请求。想问下这个是我使用不当造成的嘛

**Comment by liuchang-only** [comment]
这种情况让后端配置响应头实现浏览器缓存。

**Comment by tangbc** [comment]
是不是开启了 Chrome 的开发者工具，并且把“停用缓存”勾上了？
生产环境也不需要后后台配置，相同的 URL 默认会缓存的。
