### ISSUE TITLE
Allow to pass styles parameter - example display

### ISSUE THREAD

**Issue by globsecure** [tangbc/vue-virtual-scroll-list#38]
Today as the display is automatically set: block the table adjusts itself, it would be interesting to be able to pass this information as a parameter.

Today:
![screen shot 2018-01-15 at 16 33 45](https://user-images.githubusercontent.com/1958192/34956833-08c1fc20-fa12-11e7-80f8-2e3d7f6ea601.png)

Changed:
![screen shot 2018-01-15 at 16 33 52](https://user-images.githubusercontent.com/1958192/34956840-0f021494-fa12-11e7-9e4e-d8dca23d462b.png)

**Comment by tangbc** [comment]
Did you try use classname (prop wclass) set it's style?
