### ISSUE TITLE
fixed size demo 滚不动，鼠标动一下就滚动了，不知是我电脑问题还是demo问题。

### ISSUE THREAD

**Issue by wucyAAA** [tangbc/vue-virtual-scroll-list#384]
## To Reproduce
1. Click on '....'
2. Scroll down to '....'
3. See error

## Reproduce demo
Providing a reproduce demo of this bug, that will help me solve the problem more quickly. You can fork by this online demo: https://codesandbox.io/s/live-demo-virtual-list-e1ww1 

## Other
 - Version [e.g. 2.0]

**Comment by hehexiaohei** [comment]
+1
fix size的版本滚动就有这个问题，感觉像是在加载dom数据卡顿了一下一样

**Comment by wucyAAA** [comment]
我自己实现虚拟列表也会有这样的问题，我把v-for的key设为index就不会卡，设为数据里的特定id值就会卡。

**Comment by wucyAAA** [comment]
今天chrome更新了，更新就没问题了，更新chrome就好了！
