### ISSUE TITLE
谷歌新版本 虚拟滚动不流畅

### ISSUE THREAD

**Issue by chenglie33** [tangbc/vue-virtual-scroll-list#388]
## Describe
测试了低内核版本未发现问题，在高版本的情况下，滚轴滚动到一段距离就无法滚动，需要移动鼠标在滚动
## To Reproduce
demo均可复现

## Reproduce demo
Providing a reproduce demo of this bug, that will help me solve the problem more quickly. You can fork by this online demo: https://codesandbox.io/s/live-demo-virtual-list-e1ww1 

## Other
 - Version [e.g. 2.0]

**Comment by chenglie33** [comment]
mac无法复现 windows稳定复现

**Comment by wucyAAA** [comment]
解决了吗？兄弟

**Comment by chenglie33** [comment]
> 解决了吗？兄弟

谷歌自动会升级 目前确定的是102的内核版本是有问题的， 但是在103的版本就ok ，老的版本的内核也没问题（不清楚有问题的版本具体范围是多少）目前推测也是这个月才有的问题 #384 这个提的时间线推测的

**Comment by wucyAAA** [comment]
直接给谷歌提issue吧(狗头)

**Comment by wucyAAA** [comment]
> > 解决了吗？兄弟
> 
> 谷歌自动会升级 目前确定的是102的内核版本是有问题的， 但是在103的版本就ok ，老的版本的内核也没问题（不清楚有问题的版本具体范围是多少）目前推测也是这个月才有的问题 #384 这个提的时间线推测的

今天更新了chrome，没有问题了。
