### ISSUE TITLE
Multiple column flex layout

### ISSUE THREAD

**Issue by daniandl** [tangbc/vue-virtual-scroll-list#39]
Hey, so after a lot of tweaking and hacking, I put together this codepen.
https://codepen.io/daniandl/pen/opZGMd?editors=1010

How it is right now is already very good, this is the only lib I got this far in, *but* when you do 1 scroll tick (very slight scroll to just trigger 1 dom node recycle), you can see that the 7 jumps to 30 (depends on your window size). When scrolling back up though, it cycles through the numbers one by one. That would be what I'm trying to achieve.

Its not like the 31 wasn't in the screen before, so the user *could* see it... but what could i change to improve this?

Thanks, great lib!

**Comment by tangbc** [comment]
Sorry I don't quite understand what's the main question and demand, but I copy you example into local file to reproduce it, it good if you can explain me more imformation 😂

**Comment by daniandl** [comment]
No problem!
To simplify it: when you scroll down in my codepen, the items skip 10-20 numbers and when i scroll up they go 1 by 1.
Here is a GIF example: https://gyazo.com/d606c02e8417c4339167748acadc67dd

I want scrolling down to also be 1 by 1.

**Comment by tangbc** [comment]
Now I see that every item use one scroll slot, why not try to put 0 ~ 7 in one scroll slot. 

```
-----------------------
0 1 2 3 4 5 6 7
-----------------------
8 9 10 11 12 13 14 15
-----------------------
16 17 18 19 20 21 22 23 
-----------------------
```

**Comment by d4n1b** [comment]
Hi, @tangbc

I know this is an old thread, but would it be possible add an example of the "scroll slot"?

Thanks in advance

**Comment by d4n1b** [comment]
Sorry, I just realised that this is regarding the old version of the library. Is it possible to illustrate the same behaviour with the latest version?

Thanks
