### ISSUE TITLE
可以在移动端上支持回弹效果吗?

### ISSUE THREAD

**Issue by leiyunkang7** [tangbc/vue-virtual-scroll-list#397]
## 可以在移动端上支持回弹效果吗?

有些交互场景当滚动到顶部时再继续往上拉触发动作, 比如上拉刷新

**Comment by tangbc** [comment]
回弹是 iOS 的系统特性，有些 UI 库可以支持，但是不是这个库需要做的，这个库主要还是专注于长列表渲染性能。
