### ISSUE TITLE
items will disappear when list quickly scroll in iphone

### ISSUE THREAD

**Issue by feinimoshu753** [tangbc/vue-virtual-scroll-list#43]

**Comment by tangbc** [comment]
After all, the performance of the simulation scoll can't be exactly the same as fulldata render.

**Comment by fergardi** [comment]
I suffer of this as well. It seems that, when scrolling down, it only gets the next batch of items and refreshes the table if the scroll is past the 1/2 of the current elements of the table, so my users can see a huge white space indefinitely if they don't continue scrolling past the middle.

I've tried changing the bench and/or debounce variables, but nothing solves it.

Any help on this?

**Comment by tangbc** [comment]
@fergardi can you give a screenshot or video? I can't reproduce in my iPhone.
