### ISSUE TITLE
麻烦问下作者，virtual-list的高度必须是固定的吗？

### ISSUE THREAD

**Issue by lison16** [tangbc/vue-virtual-scroll-list#44]
我的需求是表格高度和页面高度一样，但是浏览器页面高度是不确定的，所有需要设置容器高度为100%。我设置virtual-list的高度为100%情况下，v-for循环的元素是全量渲染的，请问这样的效果没办法做到吗

**Comment by tangbc** [comment]
组件容器是必须固定高度才能计算虚拟滚动条，如果高度不确定可以通过动态修改 `remain` × `size` 的值达到你的目的，但是如果考虑到 `window.onresize` 的话性能和体验就差很多了。

**Comment by lison16** [comment]
好的，谢谢

**Comment by qiuyongzhan1999** [comment]
麻烦问下作者 <DynamicScroller class="scroller" :items="overhaulDetail" :min-item-size="40" key-field="erpsqid">

**Comment by qiuyongzhan1999** [comment]
麻烦问下作者<DynamicScroller class="scroller" :items="overhaulDetail" :min-item-size="40" key-field="erpsqid">  这个属性:min-item-size="40" 不设置值可以吗，如何让他高度自适应呢，现在加上这个属性也不是最小直接就是40px了
