### ISSUE TITLE
Any way to programmatically scroll to an item?

### ISSUE THREAD

**Issue by zxc23** [tangbc/vue-virtual-scroll-list#45]
Say, by providing a function to evaluate a match.

**Comment by zxc23** [comment]
Hmm, the docs made it sound like `start` only affects the initial scroll. What I'm after is the ability to scroll to an item at any point after mounting the component.

**Comment by tangbc** [comment]
No, not only affects in first render, if data (`start`) **change**, it will scroll to `start` index. Such as [example](https://tangbc.github.io/vue-virtual-scroll-list/examples/variable/).

**Comment by zxc23** [comment]
Fantastic. I think this aspect could be made clearer in the docs, but I'm happy it works this way. Thanks.
