### ISSUE TITLE
Animation on start change?

### ISSUE THREAD

**Issue by afontcu** [tangbc/vue-virtual-scroll-list#47]
Hi, thanks for your plugin, is great.

I was wondering if there's an easy way to add some kind of animation when mutating `start` prop. I'm scrolling when clicking some button, and I want the list to smoothly scroll to the element.

I tried adding `animation: all ease 0.3s;` to the virtual-list item wrapper element class, but with no luck.

Thanks!

**Comment by tangbc** [comment]
Hmmm, this plugin using `scrollTop` to handle mutating `start` or `offset`, it's a dom level api, not css property.

If want to add animation when change `scrollTop`, it must add a JavaScript animate engine (use third library or write one). 

Let me consider it.

**Comment by tangbc** [comment]
Unfortunately, Even if add animation the scroll behavior can't be smooth. Because this plugin just render a small part of full data, if scroll to a unrender item it will be drop frame while animate doesn't finish.

**Comment by afontcu** [comment]
Yeah, that's what I experienced too. Well, thank you for your time! I'll still use your plugin thou :)

**Comment by slidenerd** [comment]
does this mean smoothScrollIntoView is not possible? i was about to open an issue but checked out of curiosity?

**Comment by slidenerd** [comment]
@afontcu add the style attribute scroll-behavior': 'smooth , [refer to this answer](https://github.com/tangbc/vue-virtual-scroll-list/issues/291#issuecomment-757435289)
