### ISSUE TITLE
Fixed column

### ISSUE THREAD

**Issue by fergardi** [tangbc/vue-virtual-scroll-list#48]
Hello! Nice plugin!

I was wondering if it is possible to have a fixed column to the left right this example http://jsfiddle.net/4kpzN/437/ with the current functionality.

I cannot achieve the same result due to the "display: block" that the plugin force attaches to the wrapper div.

Thanks in advance.

**Comment by tangbc** [comment]
Sorry for long time, this looks no way to achive your case. You just can use scroll x at every item.
