### ISSUE TITLE
Support of grid (multiple items in row)

### ISSUE THREAD

**Issue by drozdzynski** [tangbc/vue-virtual-scroll-list#49]
Hello,
library is amazing, but I need the support of multiple items in the single line, did you considering this?

**Comment by tangbc** [comment]
Is `multiple items in row` you mean like this?
```
--------------------------
<item0> <item1> <item2>
--------------------------
<item3> <item4> <item5>
--------------------------
<item6> <item7> <item8>
--------------------------
```

**Comment by drozdzynski** [comment]
Yes

**Comment by tangbc** [comment]
This component focus at single item and fixed height, so this feature is not in the plan now.

**Comment by skjnldsv** [comment]
Hey @tangbc!
I think that would be very nice :)
Even fixed height css grid would really benefit from your library. For something like a photo gallery ? :thinking:

**Comment by camhart** [comment]
I would benefit from this as well.

**Comment by tangbc** [comment]
I'm planing a new version to support it, maybe come up in several weeks.

**Comment by skjnldsv** [comment]
@tangbc can we help in any way? :)

**Comment by simonspa** [comment]
Hi @tangbc - any news on this? If this is still planned, would it make sense to reopen the issue to keep it on your to-do list?

**Comment by dassio** [comment]
@tangbc can you reopen this issue in case of you forgetting this one?

**Comment by tangbc** [comment]
There is already an open issue about table layout. Thank you support this lib but I'm busy with my work now, so I can't find time to support it.

**Comment by waqasd4int** [comment]
+1

**Comment by seeratawan01** [comment]
Work Around : https://github.com/seeratawan01/Virtual-Scroll-Playground

**Comment by cioroianudenis** [comment]
@tangbc any news regarding this issue?

**Comment by muyu66** [comment]
@tangbc any news regarding this issue? i watching
