### ISSUE TITLE
variable list content size?

### ISSUE THREAD

**Issue by Textras** [tangbc/vue-virtual-scroll-list#5]
Is there a way to not specify the item height? We are loading a lot of items with a different content size which essentially means different item heights.

As the ag-grid component explains here https://www.ag-grid.com/javascript-grid-row-height/?framework=vue#gsc.tab=0, You cannot use variable row height when doing virtual paging or viewport. This is because these row models need to work out the position of rows that are not loaded and hence need to assume the row height is fixed. They use getRowHeight() callback, wondering if we can use something similar here?

**Comment by tangbc** [comment]
@Textras thank you for providing this, consider to put it in the feature plan.

**Comment by tangbc** [comment]
For variable row height, I looked at the implementation of other libraries, most implementations have only two ways, one is that you mentioned above `getRowHeight` callback, and the other is give an array contains the heights of all items. 

So I think these two ways can implement together by supporting prop `size` for `Number`, `Array` and `Function` value type, that should be done well.

**Comment by andreixk** [comment]
This would be an awesome feature. Here's another idea of how to possibly implement it: 
the padding on top and bottom don't need to reflect the "actual" height of all those elements, they simply need to reflect the relative position of the visible chunk within the list. so if there are 30000 elements and the visible ones are 300-308, then there should be about 10% of padding on top and about 90% of padding on the bottom. so when the user gets to item #15000 then you'll have 50% on top and 50% on the bottom regardless of how tall each element actually is.

**Comment by tangbc** [comment]
@andreixk Thank your idea, I plan to finish it recently.

**Comment by andreixk** [comment]
I mocked up a sample [here](https://jsfiddle.net/oah89oyp/) but it only works when you scroll relatively slowly - fails when you scroll fast.

**Comment by tangbc** [comment]
Already supported in [`v1.1.6`](https://github.com/tangbc/vue-virtual-scroll-list/releases/tag/v1.1.6)

**Comment by tangbc** [comment]
I mainly implement by two methods:

First, use binary search to calculate scrolled over items, then can be work out the `start` and `end`. 

Second, use estimate padding avoid too much calculate, it always use a estimate padding until really scrolled to it.
