### ISSUE TITLE
Make virtual list to use all parent height

### ISSUE THREAD

**Issue by ocassio** [tangbc/vue-virtual-scroll-list#51]
Hi.

Sorry for a silly question, but is there any way to stretch virtual list component across all parents height? It seems to be forcing fixed height style automatically.

Demo: https://codesandbox.io/s/o7q5v4nqvz

**Comment by tangbc** [comment]
Generally speaking, this component only support fixed height for scroll offset calculation.

But there is a way by `remain` × `size` to change view height.

**Comment by ocassio** [comment]
Hmm... Not the most convenient solution, but it works.
Thanks for your help!

**Comment by rijkvanzanten** [comment]
> But there is a way by changing remain and size to stretch dynamic height.

@tangbc Do you have an example of this _way_ of achieving this? I've tried reading the window's height programmatically and substracting the right values based on it's surrounding elements, but that's far from ideal nor does it work properly.. 😞

**Comment by ocassio** [comment]
@rijkvanzanten, here is a very simple unoptimized example: https://codesandbox.io/s/lyv8pqyl69.
Maybe @tangbc can provide a better solution, though.

**Comment by rijkvanzanten** [comment]
Ahhhhhh you use the parents height instead of the window. That makes way more sense. Thanks 🙂 

I think this would be a very nice addition to have in the plugin by default if that's possible somehow. Either way, this works for me 🎉

**Comment by zxc23** [comment]
I achieved this quite simply by using flexbox. Parent style:

```
.parent {
  display: flex;
}
```

and a class for the virtual scroller:

```
.list {
  flex: 1;
}
```

**Comment by zxc23** [comment]
My above solution doesn't work well when trying to implement a custom scrollbar.

The problem is that Remain must be set, yet a very common use case involves using the parent's height because of responsive layouts.

**Comment by slidenerd** [comment]
@ocassio your items are fixed height, what if each item has a different size, what is remain and size then?
