### ISSUE TITLE
组件能支持滚动到底部吗

### ISSUE THREAD

**Issue by RyanLeeLY** [tangbc/vue-virtual-scroll-list#53]
组件能支持滚动到底部吗？

**Comment by tangbc** [comment]
支持，不过你的具体场景是？

**Comment by RyanLeeLY** [comment]
场景就是不断会有数据通过websocket过来，列表做展示，希望能让scroll list一直保持滚动到底部。
我这两天初学web前端，很多事情还不太明白，可以跟我具体讲一下吗，谢谢了！

**Comment by tangbc** [comment]
数组新增数据时，更改 `start` 为最后一个。

**Comment by JElaine** [comment]
更改了start没有任何效果

**Comment by tangbc** [comment]
@JElaine 能给个简单的复现 demo 么？
