### ISSUE TITLE
Set scroll position to end of list

### ISSUE THREAD

**Issue by sigalalg1** [tangbc/vue-virtual-scroll-list#56]
We would like to use the virtual list like in a window which is similar to linux tail command. We would like the scroll to be positioned at the bottom of the window by default.
We tried to use :start and :offset with no success.
Can you please advise if this is possible and how?

**Comment by tangbc** [comment]
Do you mean set position at scroll bottom(last item) at initial?

**Comment by sigalalg1** [comment]
Yes

**Comment by tangbc** [comment]
That's a situation, I plan add a prop `reverse`.

**Comment by ohadmo** [comment]
I'd like to use a `reverse` property as well, when is it planned to be implemented?

**Comment by tangbc** [comment]
@ohadmo maybe a couple of days.

**Comment by tangbc** [comment]
@sigalalg1 @ohadmo , At present, you can use `:offset="size * items.length"` to set position at bottom .
