### ISSUE TITLE
Is there any way to use this component with items that the height is not known ?

### ISSUE THREAD

**Issue by darkopetreski** [tangbc/vue-virtual-scroll-list#58]
I have read the docs and it clearly stated that the height of the items needs to be know.

But I like to ask you directly, if there is any way, to use this component with items that the height cannot be known in advanced ?

The problem is that I am showing a book with chapters. Each chapter is shown in a card paragraph, but the height is not known. The book may have up to 2000 chapters. (each chapter is not longer then few sentences)

Rendering 2000 chapters takes up to 10-15 sec and freezes the browser. I do not like to use pagination, so I was thinking to use the virtual scroll. But the problem is that I do not know the height of the chapter in advanced because it can vary based on the text and also based on the view pot width.

So my question is, is there any way to use this component with items that the height is not know ? Maybe I can calculate the height run time ?

**Comment by tangbc** [comment]
The prop `variable` assign a height getter function, is called when item before render.
