### ISSUE TITLE
Missing required prop: "remain"

### ISSUE THREAD

**Issue by zangxx66** [tangbc/vue-virtual-scroll-list#59]
我通过NPM安装了组件，dev的时候报Missing required prop: "remain"这个错误

**Comment by tangbc** [comment]
`remain` 和 `size` 是必须的，有传吗？

**Comment by zangxx66** [comment]
谢谢，还有个问题，渲染出来以后的div的overflow-x要怎么隐藏

**Comment by tangbc** [comment]
可以定义 `wclass` 指定 CSS 类名，在 CSS 中隐藏。

**Comment by zangxx66** [comment]
谢谢你，可以正常使用了，不过我发现一个问题，data数组变化的时候DOM会被重复渲染

**Comment by tangbc** [comment]
数组变化肯定要重新渲染当前的元素，而不是整个组件。
