### ISSUE TITLE
Issue when filtering list results in zero elements

### ISSUE THREAD

**Issue by getflourish** [tangbc/vue-virtual-scroll-list#6]
I’m using this component with a list that can be filtered. It is possible that the filtered list returns an array of zero items which results in:

`[Vue warn]: Error when rendering component <vue-virtual-scroll-list>`
`TypeError: undefined is not an object (evaluating 'slots.length')`

I guess, we can’t assume that slots are always available as you try here:
https://github.com/tangbc/vue-virtual-scroll-list/blob/master/index.js#L108

**Comment by tangbc** [comment]
Thank your report, already [fixed](https://github.com/tangbc/vue-virtual-scroll-list/commit/f5de02719d08d21213e111264452f9584301d4a9) it on v1.0.7

**Comment by getflourish** [comment]
Thank you!
