### ISSUE TITLE
Is there any way to change props size & remain dynamically?

### ISSUE THREAD

**Issue by tony1157** [tangbc/vue-virtual-scroll-list#62]
Thanks for this component, it works well in my project.
and still, I have a question, is there any way to change props size & remain dynamically?
in my project, the list displays in two styles: text list and thumbnail. so the two props should be changed dynamically. 
I tried to make function and inset props but not work, it seems that the two props are bound on load.
could you give some advice? thanks

**Comment by tangbc** [comment]
Of course! but what the case you can't change props?

```vue
<template>
    <div>
        <virtual-list :size="mySize" :remain="myRemain">
            <item v-for="item of items" :key="item.id" />
        </virtual-list>
    </div>
</template>

<script>
    import item from '../item.vue'
    import virtualList from 'vue-virtual-scroll-list'

    export default {
        data () {
            return {
                mySize: 40,
                myRemain: 8
                items: [...]
            }
        }
    }
</script>
```
