### ISSUE TITLE
Reverse List?

### ISSUE THREAD

**Issue by lih1989** [tangbc/vue-virtual-scroll-list#65]
Hi!
I'm writing a chat, I ran into the problem that the component does not support scrolling up (to old messages). Can I add this function? "GoogleTranslate"

_Привет!
Пишу чат, столкнулся с проблемой что компонент не поддерживает прокрутку вверх(к старым сообщениям). Можно ли добавить такую функцию? "Original"_

**Comment by tangbc** [comment]
You can try to use `:offset="size * items.length` to set position at bottom .

**Comment by lih1989** [comment]
> You can try to use :offset="size * items.length to set position at bottom .
This will work if the list is received completely. My list loads as I scroll.
Otherwise, in any way? "GoogleTranslate"

**Comment by tangbc** [comment]
Is there will be some chat records when the chat window is initialized ? 

Then use `:totop` hooks to load prev messges.

**Comment by lih1989** [comment]
> Is there will be some chat records when the chat window is initialized ?

No
> Then use `:totop` hooks to load prev messges.

I do not understand((( Can I add an example to the Live demos component?

**Comment by tangbc** [comment]
You can add and run demos on your local.

**Comment by tangbc** [comment]
er.. the case you described is not support  now.
