### ISSUE TITLE
question:横向滚动应该怎么处理slot

### ISSUE THREAD

**Issue by sally2015** [tangbc/vue-virtual-scroll-list#66]
最近项目有一个展示大量横向数据的需求，数据结构如下
```js
data=[
  [1, 2, 3, 4,……]，
   [1, 2, 3, 4,……]，
……
]
```
希望在你的组件上改成这样使用
```js
<virtual-list : :size="size" :remain="remain" :bench="50" :onscroll="onscroll">
    <tr v-for="(cols, rowIndex) in virtualList" :key="rowIndex">
        <td v-for="(content, contentIndex) in cols" :key="contentIndex">
            {{content}}
          </td>
      </tr>
</virtual-list>
```
![image](https://user-images.githubusercontent.com/14807468/45725480-a97d3b00-bbed-11e8-82b4-9b5bfde519ee.png)

但是在处理slot上面有些疑问
![image](https://user-images.githubusercontent.com/14807468/45725079-94071180-bbeb-11e8-8c20-7fc913d6a957.png)
对于横向数据来说这时的slot是tr那一层，但实际上我需要裁切td那一层
尝试过将slot的children.slice(start, end)但是这样会引起render再渲染一次，导致padding值不对，请问有没有什么好的办法处理

**Comment by tangbc** [comment]
@sally2015 目前组件只支持竖向滚动，之前考虑到横向滚动场景不多就没加上，后面有空可以考虑支持！

**Comment by tangbc** [comment]
实现起来应该不难，增加一个 `direct` prop，然后 render 和 scroll 的时候做下区分就好了。

**Comment by sally2015** [comment]
![image](https://user-images.githubusercontent.com/14807468/45736496-b3b72d80-bc1d-11e8-90a3-60c0f7024fae.png)
> 对于横向数据来说这时的slot是tr那一层，但实际上我需要裁切td那一层
尝试过将slot的children.slice(start, end)但是这样会引起render再渲染一次，导致padding值不对，请问有没有什么好的办法处理

主要是在slot上处理，不知道怎么实现

**Comment by erweixin** [comment]
@sally2015 
你可以试下转换数据结构，然后按照这个组件的思路实现横向多列。
```
data=[
   [1, 2, 3, 4,……]，
   [1, 2, 3, 4,……]，
……
]
```
转换成：
```
data=[
   [1, 1, 1, 1,……]，
   [2, 2, 2, 2,……]，
   [3, 3, 3, 3,……]，
……
]
```

**Comment by sally2015** [comment]
@erweixin 感谢你增加的横向功能，但是exmaple是单维数组的实际上没有解决到我早前提出的多维数组的问题。像是下面这样我有二维数组的时候表现的形式都是在一行上渲染，因为在render方法上就只用了一个tag
![_15390692868564](https://user-images.githubusercontent.com/14807468/46652603-2476b780-cbd6-11e8-812d-fb1a78bc4470.png)

**Comment by erweixin** [comment]
@sally2015 我在项目中实现是按照以下思路：
先将
```
data1=[
   [1, 2, 3, 4,……]，
   [1, 2, 3, 4,……]，
……
]
```
转换成：
```
data2=[
   [1, 1, 1, 1,……]，
   [2, 2, 2, 2,……]，
   [3, 3, 3, 3,……]，
……
]
```

data2中的每一项作为横向时的Item（展现到页面上就是列）。
主要是将原本以行为单位转换成以列为单位。
![default](https://user-images.githubusercontent.com/20252915/46654337-2ee78000-cbdb-11e8-8270-4eb50a766e51.PNG)

**Comment by tangbc** [comment]
#122 重复需求移到这里。
