### ISSUE TITLE
Property start not working fine

### ISSUE THREAD

**Issue by mysla** [tangbc/vue-virtual-scroll-list#69]
This link https://codesandbox.io/s/myjvm3pmm8

Go to components -> HelloWorld.vue

I'm use :start property and asing value 17, pre last element.

But on page list started from third element of list.

**Comment by tangbc** [comment]
Because your list just 18 items, `start` for 17 will be calc to last zone.

Your need set `:offset=items.length*size`

**Comment by mysla** [comment]
@tangbc Big thx. It's perfect.
