### ISSUE TITLE
dev 文件夹在哪里呢，有分模块的源码看吗？

### ISSUE THREAD

**Issue by tcdona** [tangbc/vue-virtual-scroll-list#70]
RT 还发现，example 编译后只有 js ，示例 html 要自己编写，是不是还有好些文件没有放上来啊

**Comment by tangbc** [comment]
源码就是根目录下的 `index.js` 而已。

**Comment by tcdona** [comment]
ok
我自己搭建了个，学习研究下
高质量的项目，多谢！
