### ISSUE TITLE
Load items above "remain"

### ISSUE THREAD

**Issue by superMDguy** [tangbc/vue-virtual-scroll-list#74]
Hi, thanks for creating this. It's been working well for me so far. However, I had one question. Would you be open to adding an option to load elements above the "remain" section? It'd be like the bench, but above the currently viewed section instead of below. Currently, scrolling down then scrolling quickly up will cause the list to temporarily go blank. If you'd like, I could probably implement it, but I wanted to get your opinion first.

**Comment by tangbc** [comment]
Yes, that will be fine! Now scrolling up and down is using the same way to calc render zone, if handle them apart will work well for scrolling up.

**Comment by superMDguy** [comment]
I started to work on implementing it, but I'm confused about the difference between `delta` and `zone`. Can you help me understand it?

**Comment by tangbc** [comment]
Usually they are the same. But `delta` is using for store calculation info, after scroll, they could be old data, so use `updateZone` to keep they correct, and `zone` is the right range for rendering items, it could aviod over index such as `start` less than 0, `end` greater than items.length.
