### ISSUE TITLE
请问下包含子节点的情况下虚拟列表无法触发怎么解决？

### ISSUE THREAD

**Issue by tony1157** [tangbc/vue-virtual-scroll-list#75]
结构大致是这样的
`<virtual-list 
				:size="10" 
				:remain="100" 
				wtag="div" 
				ref="vsl"                    
			>
				
				<div v-for="(item, index) of dataArr" 
		            :key="index" 
		            :index="index"
		        >	
				<dl>
					<dt>{{item.date}}</dt>
				</dl>
				<div>
		        	<div v-for="children in item.childrens">
						<span class="describe">{{children.name}}</span>
					</div>
				</div>
	        </div>
		</virtual-list>`
数据如下
`dataArr : [{
"date" : '2018-11-11',
"childrens" : [{
  "id":1,
  "checked" : false,
  "name": name
},
{
  "id":2,
  "checked" : false,
  "name": name
},
......
]},
{
"date" : '2018-11-12',
"childrens" : [{
  "id":1,
  "checked" : false,
  "name": name
},
{
  "id":2,
  "checked" : false,
  "name": name
},
......
]},
`
item下的子节点childrens可能有几百上千条数据，但是item的话数量很少，虚拟列表没法触发，还是全部加载了内容。
请问有什么办法可以让item下的childrens触发列表滚动吗？

**Comment by tangbc** [comment]
看上去你是要子节点应用虚拟列表了吧？而不是最外层。

**Comment by tony1157** [comment]
还是需要最外层应用，数据相当于某个日期下有数量不等的记录，要展示所有日期的记录。
我试过将虚拟列表应用到子节点，但这样的话就只有某个日期能以虚拟列表方式展示。

**Comment by tony1157** [comment]
上面的代码好像被吃掉了虚拟列表部分
完整的大概是这样的
<virtual-list 
    :size="size" 
    :remain="remain" 
    :bench = "bench"
    wtag="div" 
    ref="vsl"                    
>                   
    <div v-for="(item,index) of dataArr"
        :key="index" 
        :index="index"                      
    > 
        
        <dl class="timetag">
            <dt>{{item.date}}</dt>
            <dd><span>20</span></dd>
        </dl>
        
        <div v-for="(children,index) in item.childrens"
            :key="index" 
            :index="index"
        >
            <span class="describe">{{children.name}}</span>
        </div>
    </div>

</virtual-list>

期望的显示效果类似
![uuuuuuuu](https://user-images.githubusercontent.com/5188621/48453751-9baff480-e7ef-11e8-88d5-3e5d55912575.png)

浏览器源码里面好像把最外层节点识别为数量，试过只有一层节点的情况下显示没问题，这种数据结构下外层节点很少，子节点比较多，然后没法触发虚拟列表的机制。
请问有什么办法能解决吗？

**Comment by tangbc** [comment]
这个组件设计只针对一层列表，既然外层节点少，子节点多那么应该是子节点用虚拟列表才对，但是你这个场景子节点出现滚动条（内外双层滚动）又不符合交互规范，所以这个组件无法满足你的这个场景需求。

**Comment by tony1157** [comment]
感谢，看来得另想办法解决了
谢谢回复！
