### ISSUE TITLE
[Vue warn]: Error in nextTick: "NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node."

### ISSUE THREAD

**Issue by quereus** [tangbc/vue-virtual-scroll-list#76]
If new array item is added with unshift while scrolling i get the following error.
How can i prevent the error?

![vue](https://user-images.githubusercontent.com/45661737/49587729-cc5df680-f975-11e8-9758-6033b9daecf1.png)

**Comment by chenjing1552** [comment]
同问

**Comment by tangbc** [comment]
@quereus @chenjing1552 

I try and can not reproduce this warning, can you give a demo online ?
