### ISSUE TITLE
When the item height is greater than the list height, item positions will jump

### ISSUE THREAD

**Issue by lkho** [tangbc/vue-virtual-scroll-list#77]
Steps to reproduce:

1. In the variable height [example](https://tangbc.github.io/vue-virtual-scroll-list/examples/variable/), the list is ~300px tall.
2. scroll the list a few times first.
3. then set two items (which is not on the first page, i.e. index > remain) to height > 300px (i.e. set item 10 and 20 to 500px)
4. slowly scroll pass item 10 and 20
5. when scrolling pass item 10 or 20, item 11 or 21 (correspondingly) will sometimes jump suddenly.

**Comment by xmasong** [comment]
I also encountered this bug, is there a temporary solution? @tangbc

**Comment by tangbc** [comment]
@xmasong Not yet, busy at this time, I will fix when I'm free.

**Comment by tangbc** [comment]
It might be fixed in v2.0, welcome to try and report.
