### ISSUE TITLE
Not working, Nothing display

### ISSUE THREAD

**Issue by BloodSucker123** [tangbc/vue-virtual-scroll-list#84]
I use browserify with `es2015` presets to bundle javascript. I dont know why this is not working. it displays nothing.

![screen shot 2019-02-05 at 12 01 18 pm](https://user-images.githubusercontent.com/41031355/52252515-cc5e8080-293d-11e9-8d91-e4a66272f0c0.png)

Template
```
virtual-list(:size="40", :remain="8", :key="$index")
 item(v-for="item of filtered") item
```

Script
```
import Vue from 'vue'
import virtualList from 'vue-virtual-scroll-list'
var VueResource = require('vue-resource');

Vue.use(VueResource);
Vue.component('virtual-list',virtualList)

Vue.component('car-hire',{
	props:['rental','position'],
	template:'#template-car-hire'
})
new Vue({
	el: '.app-content',
	data: {
		rentals:new Array(1000),
		rowData:[],
		searchTitle:''
	},
	paginate: ['filtered'],
	methods: {

	},
})
```

My Package json
![screen shot 2019-02-05 at 12 03 08 pm](https://user-images.githubusercontent.com/41031355/52252576-147da300-293e-11e9-821a-96827f618956.png)

**Comment by georgemickleburgh** [comment]
I believe this was broken by [Vue commit 653aac2](https://github.com/vuejs/vue/commit/653aac2c57d15f0e93a2c1cc7e6fad156658df19), as I have seen this behaviour when updating my Vue version, but it works without issue for an earlier version.

I haven't found a solution yet.

**Comment by tangbc** [comment]
@BloodSucker123 As I see your `package.json` vue is in version `1.0.28` ?

This libray just support vue version greater than `2.3.0`.

**Comment by BloodSucker123** [comment]
I already tried it with 2.3 and above

**Comment by tangbc** [comment]
@BloodSucker123 so problem solved?
