### ISSUE TITLE
when update nuxt to 2.4.3, and set the offset value is not jump to a right position in list

### ISSUE THREAD

**Issue by yoruponder** [tangbc/vue-virtual-scroll-list#85]
nuxt1.4.2
<img width="395" alt="wx20190212-151054 2x" src="https://user-images.githubusercontent.com/9858714/52618050-af472600-2ed8-11e9-8ddd-65cb06bc7948.png">

nuxt 2.4.3
<img width="392" alt="wx20190212-151028 2x" src="https://user-images.githubusercontent.com/9858714/52618055-b1a98000-2ed8-11e9-8f3f-5ff0206f578f.png">

**Comment by yoruponder** [comment]
@tangbc hi~ Is there any solution to fix the buy?
buremba says that vue 2.6.6 breaks this library, and other library <Akryum/vue-virtual-scroller> had fixed now. 😊😊😊

**Comment by tangbc** [comment]
@yoruponder The same issue in <Akryum/vue-virtual-scroller> just sloved by add `key-field`?

It's better if you can give me a reproduced repo.

**Comment by yoruponder** [comment]
@tangbc Hi, I create two repositories to reproduce the question.
Normal in Nuxt 1.4.5 [https://github.com/yoruponder/virtual-scroll-nobug-1.4.5](url)
Not perfect in Nuxt 2.4.3 [https://github.com/yoruponder/virtual-scroll-bug-2.4.3](url)

**Comment by tangbc** [comment]
@yoruponder I was able to reproduce the bug on your repo, but I couldn't find the exact reason for it for a long time. 

I try to log and found that the `offset` number you pass to `virtual-list` and which we get it from real DOM is same, so, this bug maybe not come from `virtual-list`.

The way `virtual-list` set `offset` just simply use JavaScript API `el.scrollTop = offset`, it maybe some strange behaviors in nuxt or vue latest when set scroll or ui render. 

Continue watch for this ....

![image](https://user-images.githubusercontent.com/6846113/53695669-70caca00-3df9-11e9-9e27-be4815a99a38.png)

**Comment by yoruponder** [comment]
@tangbc maybe this bug like buremba say, that coms from new vue version when Vue update to 2.6.6, maybe some new feature impacts `virtual-list`.  is there any solution to fix it?

**Comment by tangbc** [comment]
Not yet.
