### ISSUE TITLE
Add option for custom container height

### ISSUE THREAD

**Issue by jeancaffou** [tangbc/vue-virtual-scroll-list#86]
Setting a custom container height via CSS seems to be working, but not always right after first mount. 
Items only appear after scroll event.

Inspecting it in vue-devtools shows that the items are not being rendered util the container is scrolled

`<virtual-list :size="108" :remain="10" :style="'height:' + height">
...
</virtual-list>`

**Comment by jeancaffou** [comment]
For now, adding a watcher for items and forcing the render seems to do the trick.
`watch: {
    items () {
      this.$refs.vs.forceRender()
    }
  }`

**Comment by tangbc** [comment]
This virtual-list container viewport height is decided by `size × remian`, can you via changing these two props to achieve `custom container height`?

**Comment by jeancaffou** [comment]
Isn't changing the `size` prop affecting rendering of the list item?

**Comment by tangbc** [comment]
Yes, the same issue is here: https://github.com/tangbc/vue-virtual-scroll-list/issues/20.

You can see if this can solve your problem?

**Comment by jeancaffou** [comment]
No, this is not the same issue. Container size has to be responsive - must support 100% relative height, not dependant on size of the item or remain (number of items).

It works only if I do forceRender after changing the items array.
