### ISSUE TITLE
Dynamically loaded content messes with display

### ISSUE THREAD

**Issue by LorinIonita** [tangbc/vue-virtual-scroll-list#88]
I have a list of items that dynamically re-renders based on a filter (it retrieves the data back from an API). When the list is small (e.g. 7 items in my case) and the filter brings back 1 item, going back to the 7 items list only renders 1 item (a regular list doesn't have this issue).

Do you have any idea how I can fix this?

**Comment by tangbc** [comment]
Sorry, I can't quite understand ` the filter brings back 1 item, going back to the 7 items list only renders 1 item` means, can you explain more?

**Comment by LorinIonita** [comment]
Here is a code sandbox example
https://codesandbox.io/s/4w0xw8w514?fontsize=14

If you use the selectbox and select "two" it renders a list of 2 items. If you select "one" again, it doesn't go back to the 7 items. It just renders the first 2 items in the list.

I managed to fix it by adding a ref="list" to the virtual list and doing `this.$refs.list.$forceUpdate();` after the items are returned from the api.

**Comment by tangbc** [comment]
I have reproduced it, thanks for reporting this.

**Comment by cchuang6** [comment]
I think the problem is if the number of remain plus the number of bench is greater than the data items, it will not re-render the list. I hot fix it by checking the size of the items is smaller than (remain + bench) and call forceUpdate if the condition is true.

Here is the hot fix example:
https://codesandbox.io/s/5yljv9548x

**Comment by tangbc** [comment]
@cchuang6 almost that, but vitrual-list shoud handle it itself, I will fix it in next version.

**Comment by tangbc** [comment]
Fixed and publish by `1.3.1`.

**But** when change new list data, render zone `start` and `end` is still old and cannot know if this update come from new list or by scrolling, so call [`forceRender()`](https://github.com/tangbc/vue-virtual-scroll-list#public-methods) after that is still necessary.
