### ISSUE TITLE
How to handle keyUp and keyDown

### ISSUE THREAD

**Issue by eldor** [tangbc/vue-virtual-scroll-list#89]
Is it possible to detect keyUp and keyDown and scroll accordantly.
Have implemented virtual-scroll-list as a select box when the user are able to use keyUp and keyDown to go through list, but it doesn't change (scroll) the items shown.

Any help are highly appreciated

**Comment by tangbc** [comment]
I think you can listen `keyup` and `keydown` event by yourself, then use `start` or `offset` prop to controll virtual-scroll-list scroll postion.

(**but** it doesn't change (scroll) the items shown). Do you mean go through list but scroll position remain unchanged?

**Comment by eldor** [comment]
I mean that the scroll list change when you go through with `keyUp` and `keyDown`, but figured it out to set `scrollTo` on the element when hitting the bottom or top of the visible list. 

But it would be nice if you where able through `prop` to change the `remain` so it looks like the list is scrolling.

**Comment by tangbc** [comment]
Prop `remain` is also data-reactive now.
