### ISSUE TITLE
momentum scrolling on iOS/iphone

### ISSUE THREAD

**Issue by dmccuskey** [tangbc/vue-virtual-scroll-list#91]
i'm using this library in a app with Cordova & Vuetify.

one of the issues i'm having is that momentum scrolling doesn't work on my iphone unless i add the following to the style block in the render function:

```
 'overflow-y': 'scroll',
 '-webkit-overflow-scrolling': 'touch'
```

in another issue i noticed that you were using an iphone as well so was wondering if you had the same experience.

ref:
* https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/

**Comment by tangbc** [comment]
Better scroll experience on iPhone with using `-webkit-overflow-scrolling: touch`, one of this library's live  demo has added: https://github.com/tangbc/vue-virtual-scroll-list/blob/master/examples/finite/finite.vue#L65.

But if we set `overflow-y: scroll` will however always show the scrollbar even if content not overfollow.

**Comment by dmccuskey** [comment]
thanks for the link. i added the following lines, but am seeing some really strange scrolling behavior:

style:
```
.v-list {
  -webkit-overflow-scrolling: touch;
}
```

template:
```
        <virtual-list
          class="v-list"    << only added this

          ref="virtualList"
          :item="scrollComponent"
          :itemdata="globalArtworkRecords"
          :itemprop="itemProps"
          :remain="4"
          :size="tileHeight"
        />
```

(note: in the videos i'm not letting the scroller stop to re-draw)

with the class added, once i get to the end of the items which have not been drawn, the scroller jumps around. 

https://www.dropbox.com/s/06224oq3v5zomy7/virtual-scroller-with-class.MOV?dl=0

if i remove just the class property on the virtual list, then the behavior is closer to "normal" on iphone. 

https://www.dropbox.com/s/xg05q60c982993l/virtual-scroller-no-class.MOV?dl=0

(btw, behavior on android works great ; im experiencing a few issues on iOS)

**Comment by tangbc** [comment]
```
once i get to the end of the items which have not been drawn, the scroller jumps around
```

 Err, it's a bug if item is such more height, similar to #77, this should be solved by pre-rendering.

**Comment by tangbc** [comment]
@dmccuskey I published v1.3.3 you can try agian.

**Comment by dmccuskey** [comment]
great, thanks for letting me know ! i'll see if i can revisit this week. cheers

**Comment by dmccuskey** [comment]
thanks, that fixed the issue
