### ISSUE TITLE
remain出现的问题

### ISSUE THREAD

**Issue by qiufeihong2018** [tangbc/vue-virtual-scroll-list#94]
尊敬的作者：
我按照官网设置参数
发现remain设置1,并不是保留1条而是2条，设置2,并不是保留2条而是4条，这是为何？
代码如下：
![Screenshot from 2019-04-11 17-20-31](https://user-images.githubusercontent.com/36500514/55945866-2d783c80-5c7e-11e9-9179-deeae70f4005.png)
浏览器dom
![Screenshot from 2019-04-11 17-20-45](https://user-images.githubusercontent.com/36500514/55945871-2fda9680-5c7e-11e9-8412-c08f54ac94fd.png)

**Comment by tangbc** [comment]
`remain` 指的是列表可视区域的条目数。设置 2 是 4 条的原因是 `bench` 参数默认和 `remain` 是相等的。总渲染的条目数就是 `remian + bench` 条，`remian × size` 就是列表可视区域的高度。

详见：https://github.com/tangbc/vue-virtual-scroll-list#props-type

**Comment by qiufeihong2018** [comment]
懂了，谢谢作者大大
