### ISSUE TITLE
Bench is rendered even when exceeding itemcount

### ISSUE THREAD

**Issue by delucasvb** [tangbc/vue-virtual-scroll-list#96]
There seems to be a bug in 1.3.3 that renders the bench, even when there aren't enough items. For instance, we use a virtual list with "remain" set to 3 and "bench" at its default value. "itemcount" is 3 as well. Still "itemprops" is called for indices 0 through 5, instead of 0 through 2. Setting "bench" to 0 doesn't change anything.

This results in Vue errors in our items, because their properties contained illegal values.

After downgrading to 1.3.2, everything worked as normal.

**Comment by tiagoskaneta** [comment]
Here is a code sandbox example:
https://codesandbox.io/s/ym0zrqn21v

Notice that it tries to render elements up to `remain` + `bench` going past the limit of `itemcount`.

**Comment by tangbc** [comment]
I fix it in new version v1.3.4, you can see if the problem has been solved, and reply to me ?

**Comment by tiagoskaneta** [comment]
It's working fine now for me, thank you.
