### ISSUE TITLE
Bug on onscroll events

### ISSUE THREAD

**Issue by ukool** [tangbc/vue-virtual-scroll-list#97]
Hello!
I have some problem with you'r plugin, maybe you can help me.

When i subscribe on `onscroll` event,  first time in data.offsetAll has small value  like 3 or great, when value approaching in data.offsetAll to 300 or less, data.offsetAll becomes great than 1 000.

I tested is on two inputs and everywhere value the same.

![image](https://user-images.githubusercontent.com/20686717/56302817-33b95d80-6143-11e9-9e7c-060204a816d1.png)

Thanks.

**Comment by tangbc** [comment]
Are you using variable height?

**Comment by ukool** [comment]
Thanks, the problem was in dynamic calc.

**Comment by ukool** [comment]
Thanks, the problem was in dynamic calc.
