### ISSUE TITLE
iOS not updating while scrolling

### ISSUE THREAD

**Issue by dmccuskey** [tangbc/vue-virtual-scroll-list#99]
you can see in this video that iOS will come to the end of the rendered tiles as long as scroll momentum hasn't stopped. (ie, list is not being updated during scroll). the list *will only update when the scroll momentum has stopped*. this behavior happens when scrolling in both directions (up/down).

https://www.dropbox.com/s/xg05q60c982993l/virtual-scroller-no-class.MOV?dl=0

additionally, if i attach a listener function using `onscroll`, that function will only fire on iOS *after scrolling has stopped*.

everything is working as expected on Android – list automatically updates during scroll and scroll events seem to properly fire.

(btw, i don't really need `onscroll`, i was just looking for a way to hook into `forceUpdate()`)

using:
vue-virtual-scroll-list v1.3.4
vue v2.5.16

**Comment by tangbc** [comment]
I think it's because the images aren't preloaded when ready to render the next group, and image size  seems to be changed after rendered.

You can compare the  in the project and load real picture avatars by:
https://tangbc.github.io/vue-virtual-scroll-list/demos/item-mode/?avatar
